---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Diese Version von NetApp Backup and Recovery weist die folgenden bekannten Einschränkungen auf. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für KVM-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.

Die folgenden Aktionen und Konfigurationen werden in der privaten Vorschauversion von KVM-Workloads in NetApp Backup and Recovery nicht unterstützt:



== Nicht unterstützte Aktionen

Die folgenden Aktionen werden in der privaten Vorschauversion nicht unterstützt:

* Klonen, Mounten oder Unmounten von VMs
* Wiederherstellen von VMs an einem anderen Standort
* Schützen Sie im SAN gespeicherte VMs
* Anwendungen schützen
* Erstellen Sie benutzerdefinierte Backups (es werden nur Backups unterstützt, die von der NetApp Console aus initiiert werden).




== Nicht unterstützte Konfigurationen

Die folgenden Konfigurationen werden nicht unterstützt:

* Rollenbasierte Zugriffskontrolle (RBAC)
* Direkt an den KVM-Host angeschlossene Festplatten
* Datenträger, die sich über mehrere NFS-Mount-Punkte oder Freigaben erstrecken
* RAW-Festplattenformat
* Andere Speicherpooltypen als NetFS (nur NetFS wird unterstützt)




== Hinweise zur Fehlerbehebung

Beachten Sie Folgendes bei der Verwendung der privaten Vorschau von KVM-Workloads mit NetApp Backup and Recovery.

* Backups können fehlschlagen, wenn der QEMU Guest Agent nicht in einer geschützten VM ausgeführt wird. Um dieses Problem zu umgehen, stellen Sie sicher, dass der  `qemu-guest-agent` Daemon auf der VM ausgeführt wird, bevor Sie das Backup starten.

