---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: Beachten Sie diese NetApp Backup and Recovery-Einschränkungen, bevor Sie Backup and Recovery in Ihrer Umgebung einsetzen. 
---
= Bekannte Einschränkungen mit NetApp Backup and Recovery für Kubernetes-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die aktuellen Einschränkungen und Workarounds für Kubernetes-Workloads in NetApp Backup and Recovery.



[[limitation-in-the-backup-and-recovery-preview-for-netapp-console-local-deployment]]
== Einschränkung in der Backup- und Recovery-Vorschau für die lokale NetApp Console Bereitstellung

In der Backup and Recovery-Vorabversion für die lokale Bereitstellung der NetApp Console werden Backups in Objektspeicher nur für ONTAP S3 und StorageGRID Ziele unterstützt. Backup-Archivierung ist in dieser Vorabversion nicht unterstützt.



[[changing-the-protection-policy-for-an-application]]
== Ändern der Datensicherungsstrategie für eine Anwendung

Wenn die Datensicherungsstrategie einer Applikation so geändert wird, dass ein anderer Bucket oder ein anderes sekundäres Replikationsziel verwendet wird, kann der Schutz fehlschlagen.

*Abhilfe*: Die Anwendung entfernen und erneut hinzufügen.



[[3-2-1-protection-policy-configuration-limitation]]
== Konfigurationsbeschränkung der 3-2-1-Datensicherungsstrategie

Wenn eine 3-2-1 Datensicherungsstrategie erstellt wird, die Objektspeicher-Backups getrennt von der Replikation auf den Sekundärspeicher plant, kann der Schutz hängen bleiben.

*Abhilfe*: Die Anwendung entfernen, erneut hinzufügen und anschließend mit einer anderen Datensicherungsstrategie schützen.
