---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Diese Version von NetApp Backup and Recovery weist die folgenden bekannten Einschränkungen auf. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für KVM-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die aktuellen Einschränkungen für KVM-Workloads in NetApp Backup and Recovery werden dargestellt.

Die folgenden nicht unterstützten Aktionen und Konfigurationen gelten für KVM-Workloads in NetApp Backup and Recovery:



[[unsupported-actions]]
== Nicht unterstützte Aktionen

Folgende Aktionen werden nicht unterstützt:

* In der Backup and Recovery-Vorabversion für die lokale Bereitstellung der NetApp Console werden Backups in Objektspeicher nur für ONTAP S3 und StorageGRID Ziele unterstützt. Backup-Archivierung ist in dieser Vorabversion nicht unterstützt.
* Klonen, Mounten oder Unmounten von VMs
* Schützen Sie im SAN gespeicherte VMs
* Anwendungen schützen
* Erstellen Sie benutzerdefinierte Backups (es werden nur Backups unterstützt, die von der NetApp Console aus initiiert werden).




[[unsupported-configurations]]
== Nicht unterstützte Konfigurationen

Die folgenden Konfigurationen werden nicht unterstützt:

* Rollenbasierte Zugriffskontrolle (RBAC)
* Direkt an den KVM-Host angeschlossene Festplatten
* Datenträger, die sich über mehrere NFS-Mount-Punkte oder Freigaben erstrecken
* RAW-Festplattenformat
* Andere Speicherpooltypen als NetFS (nur NetFS wird unterstützt)




[[troubleshooting-notes]]
== Hinweise zur Fehlerbehebung

Folgendes ist zu beachten, wenn KVM-Workloads mit NetApp Backup and Recovery verwendet werden.

* Backups können fehlschlagen, wenn der QEMU Guest Agent nicht in einer geschützten VM ausgeführt wird. Um dieses Problem zu vermeiden, muss sichergestellt sein, dass der  `qemu-guest-agent` Daemon auf der VM läuft, bevor das Backup gestartet wird.

