---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Diese Version von NetApp Backup and Recovery weist die folgenden bekannten Einschränkungen auf. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für KVM-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.

Die folgenden Aktionen und Konfigurationen werden in der privaten Vorschauversion von KVM-Workloads in NetApp Backup and Recovery nicht unterstützt:



== Nicht unterstützte Aktionen

Die folgenden Aktionen werden in der privaten Vorschauversion nicht unterstützt:

* Klonen, Mounten oder Unmounten von VMs
* Wiederherstellen von VMs an einem anderen Standort
* Schützen Sie im SAN gespeicherte VMs
* Anwendungen schützen
* Schutzgruppen bearbeiten
* Erstellen Sie Schutzgruppen mithilfe von VMs von mehreren KVM-Hosts
* Erstellen Sie benutzerdefinierte Backups (es werden nur Backups unterstützt, die von der NetApp Console aus initiiert werden).




== Nicht unterstützte Konfigurationen

Die folgenden Konfigurationen werden nicht unterstützt:

* Rollenbasierte Zugriffskontrolle (RBAC)
* Direkt an den KVM-Host angeschlossene Festplatten
* Datenträger, die sich über mehrere NFS-Mount-Punkte oder Freigaben erstrecken
* RAW-Festplattenformat
* Andere Speicherpooltypen als NetFS (nur NetFS wird unterstützt)




== Hinweise zur Fehlerbehebung

Beachten Sie Folgendes bei der Verwendung der privaten Vorschau von KVM-Workloads mit NetApp Backup and Recovery:

* Um sicherzustellen, dass die Wiederherstellung von KVM-Workloads vollständig und erfolgreich verläuft, vergewissern Sie sich, dass die Einstellung *VM-konsistenten Snapshot aktivieren* in der Schutzrichtlinie, die Sie für KVM-Backups verwenden, aktiv ist.
* Ein Speicherpool mit KVM-Hosts, die von Apache CloudStack verwaltet werden, kann nur gesichert werden, wenn alle verwalteten Hosts zu NetApp Backup and Recovery hinzugefügt werden. Als Ausweichlösung fügen Sie jeden von CloudStack verwalteten KVM-Host zu NetApp Backup and Recovery hinzu.
* Eine gestoppte VM, die zu einer Schutzgruppe gehört, kann nicht gesichert werden. Als Ausweichlösung sollte die gestoppte VM vor dem Start der Sicherung aus der Schutzgruppe entfernt werden.

