---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery muss zunächst Daten erkennen, damit Sie den Dienst nutzen können.  Während der Erkennung analysiert NetApp Backup and Recovery alle Volumes und Dateien in Systemen innerhalb Ihres Unternehmens. 
---
= Bekannte Einschränkungen bei NetApp Backup und Recovery für Hyper-V-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.



== Nicht unterstützte Aktionen

Die folgenden Aktionen werden in der privaten Vorschauversion von Hyper-V-Workloads in NetApp Backup and Recovery nicht unterstützt:

* Erstellen von Ressourcengruppen
* Spanning-Disks (über mehrere CIFS-Freigaben hinweg)
* Schützen Sie VMs über SAN
* Schutzgruppen bearbeiten
* Schützen Sie Hyper-V-Hosts, die mit System Center Virtual Machine Manager (SCVMM) geclustert sind.




== Nicht unterstützte ältere NetApp Console Konsolenkonten

Ältere NetApp Console unterstützen nicht die Funktionen, die zum Schutz von Hyper-V-Workloads erforderlich sind.  Überprüfen Sie, ob Sie in der Web-Benutzeroberfläche der Konsole ein Legacy-Konto verwenden.  Wenn Sie über ein älteres Konsolenkonto verfügen, erstellen Sie ein neues Konto, bevor Sie Hyper-V-Workloads schützen.

.Schritte
. Wählen Sie im NetApp Console *Administration > Identität und Zugriff*.
. Prüfen Sie unter *Organisation*, ob neben der Organisations-ID eine *Konto-ID* angezeigt wird.
+
Wenn eine *Konto-ID* angezeigt wird, verwenden Sie ein Legacy-Konto.

. Wenn Sie ein Legacy-Konto verwenden, gehen Sie wie folgt vor:
+
.. Melden Sie sich von der Konsole ab und navigieren Sie dann zum https://console.netapp.com/["Anmeldeseite der Konsole"^] .
.. Wählen Sie *Registrieren*, um ein neues Konto zu erstellen.



