---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery muss zunächst Daten erkennen, damit Sie den Dienst nutzen können.  Während der Erkennung analysiert NetApp Backup and Recovery alle Volumes und Dateien in Systemen innerhalb Ihres Unternehmens. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für Hyper-V-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.



== Nicht unterstützte Aktionen

Die folgenden Aktionen werden in der privaten Vorschauversion von Hyper-V-Workloads in NetApp Backup and Recovery nicht unterstützt:

* Erstellen Sie Ressourcengruppen mithilfe von VMs von mehreren Hyper-V-Hosts.
* Wiederherstellen von VMs an einem anderen Standort
* Spanning-Disks (über mehrere CIFS-Freigaben hinweg)
* Schützen Sie VMs über SAN
* Schutzgruppen bearbeiten
* Schützen Sie Hyper-V-Hosts, die mit System Center Virtual Machine Manager (SCVMM) geclustert sind.

