---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery muss zunächst Daten erkennen, damit Sie den Dienst nutzen können.  Während der Erkennung analysiert NetApp Backup and Recovery alle Volumes und Dateien in Systemen innerhalb Ihres Unternehmens. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für Microsoft SQL Server-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.



== Unterstützung des Klon-Lebenszyklus

* Das Klonen aus dem Objektspeicher wird nicht unterstützt.
* Massenklonvorgänge werden für On-Demand-Klone nicht unterstützt.
* Die Auswahl von I-Gruppen wird nicht unterstützt.
* Die Auswahl von QOS-Optionen (maximaler Durchsatz) wird nicht unterstützt.




== Nur Standardbereitstellungsmodus

Diese NetApp Backup and Recovery Version funktioniert nur im Standardbereitstellungsmodus, nicht im eingeschränkten oder privaten Modus.



== Einschränkung des Windows-Clusternamens

Der Windows-Clustername darf keinen Unterstrich (_) enthalten.



== Probleme bei der SnapCenter -Migration

Die Migration von Ressourcen von SnapCenter in NetApp Backup and Recovery unterliegt den folgenden Einschränkungen.

Weitere Informationen zur Migration von SnapCenter -Richtlinien zu NetApp Backup and Recovery -Richtlinien finden Sie unterlink:reference-policy-differences-snapcenter.html["Richtlinien in SnapCenter im Vergleich zu denen in NetApp Backup and Recovery"] .



=== Einschränkungen der Ressourcengruppe

Wenn alle Ressourcen in einer Ressourcengruppe geschützt sind und eine dieser Ressourcen auch außerhalb der Ressourcengruppe geschützt ist, wird die Migration von SnapCenter blockiert.

*Problemumgehung*: Schützen Sie die Ressource entweder in einer Ressourcengruppe oder einzeln, aber nicht in beiden.



=== Ressourcen mit mehreren Richtlinien, die dieselbe Zeitplanebene verwenden, werden nicht unterstützt

Sie können einer Ressource nicht mehrere Richtlinien zuweisen, die dieselbe Zeitplanebene verwenden (z. B. stündlich, täglich, wöchentlich usw.).  NetApp Backup and Recovery importiert diese Ressourcen nicht aus SnapCenter.

*Problemumgehung*: Fügen Sie einer Ressource nur eine Richtlinie mit derselben Zeitplanebene hinzu.



=== Stundenrichtlinien müssen zu Beginn der Stunde beginnen

Wenn Sie über eine SnapCenter -Richtlinie verfügen, die sich stündlich wiederholt, aber zu Beginn der Stunde keine Intervalle verwendet, importiert NetApp Backup and Recovery die Ressource nicht.  Beispielsweise werden Richtlinien mit Zeitplänen von 1:30, 2:30, 3:30 usw. nicht unterstützt, während Richtlinien mit Zeitplänen von 1:00, 2:00, 3:00 usw. unterstützt werden.

*Problemumgehung*: Verwenden Sie eine Richtlinie, die sich ab der vollen Stunde in 1-Stunden-Intervallen wiederholt.



=== Sowohl tägliche als auch monatliche Richtlinien, die an eine Ressource angehängt sind, werden nicht unterstützt

Wenn sich eine SnapCenter -Richtlinie sowohl in Tages- als auch in Monatsintervallen wiederholt, importiert NetApp Backup and Recovery die Richtlinie nicht.

Sie können beispielsweise einer Ressource keine tägliche Richtlinie (mit weniger als oder gleich 7 Tagen oder mehr als 7 Tagen) und derselben Ressource auch eine monatliche Richtlinie zuordnen.

*Problemumgehung*: Verwenden Sie eine Richtlinie, die ein tägliches oder ein monatliches Intervall verwendet, aber nicht beides.



=== On-Demand-Backup-Richtlinien nicht migriert

NetApp Backup and Recovery importiert keine On-Demand-Sicherungsrichtlinien aus SnapCenter.



=== Nur-Protokoll-Sicherungsrichtlinien werden nicht migriert

NetApp Backup and Recovery importiert keine Nur-Protokoll-Sicherungsrichtlinien aus SnapCenter.  Wenn eine SnapCenter -Richtlinie Nur-Protokoll-Backups umfasst, importiert NetApp Backup and Recovery die Ressource nicht.

*Problemumgehung*: Verwenden Sie in SnapCenter eine Richtlinie, die mehr als nur reine Protokollsicherungen verwendet.



=== Host-Zuordnung

SnapCenter verfügt nicht über die Möglichkeit, Speichercluster oder SVMs für die Ressourcen den Hosts zuzuordnen, NetApp Backup and Recovery hingegen schon.  Der lokale ONTAP Cluster oder SVM wird in den Vorschauversionen von NetApp Backup and Recovery keinem Host zugeordnet.  Darüber hinaus unterstützt die NetApp Console keine SVMs.

*Problemumgehung*: Erstellen Sie vor dem Importieren von Ressourcen aus SnapCenter ein System in NetApp Backup and Recovery für alle lokalen ONTAP Speichersysteme, die im lokalen SnapCenter registriert sind.  Importieren Sie dann die Ressourcen für diesen Cluster von SnapCenter in NetApp Backup and Recovery.



=== Fahrpläne nicht im 15-Minuten-Takt

Wenn Sie über einen SnapCenter -Richtlinienzeitplan verfügen, der zu einer bestimmten Zeit beginnt und in anderen Intervallen als 15 Minuten wiederholt wird, importiert NetApp Backup and Recovery den Zeitplan nicht.

*Problemumgehung*: Passen Sie die Richtlinie mithilfe von SnapCenter so an, dass sie in 15-Minuten-Intervallen wiederholt wird.



== Eingeschränkter Support für Virtualisierungsverwaltungssoftware

Wenn Sie KVM-Workloads schützen, unterstützt NetApp Backup and Recovery die Erkennung von KVM-Workloads nicht, wenn Virtualisierungsverwaltungssoftware wie Apache CloudStack oder Red Hat OpenShift Virtualization verwendet wird.
