---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, SAP HANA database, virtual machine, vm 
summary: Beachten Sie diese NetApp Backup and Recovery-Einschränkungen, bevor Sie Backup and Recovery in Ihrer Umgebung einsetzen. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für Hyper-V-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aktuelle Einschränkungen und nicht unterstützte Aktionen für Hyper-V-Workloads in NetApp Backup and Recovery.



[[unsupported-actions]]
== Nicht unterstützte Aktionen

Die folgenden Aktionen werden für Hyper-V-Workloads in NetApp Backup and Recovery nicht unterstützt:

* In der Backup and Recovery-Vorabversion für die lokale Bereitstellung der NetApp Console werden Backups in Objektspeicher nur für ONTAP S3 und StorageGRID Ziele unterstützt. Backup-Archivierung ist in dieser Vorabversion nicht unterstützt.
* Der Schutz von VMs der 2. Generation, die auf SAN Storage abgelegt sind, wird bei Verwendung von Microsoft Windows Server 2025 nicht unterstützt.
* Erstellen von Ressourcengruppen mithilfe von VMs von mehreren Hyper-V Hosts
* Verwendung von Datenträgern, die sich über mehrere CIFS-Freigaben erstrecken
* Unabhängig von der Einstellung „Prozessorkompatibilität“ in Hyper-V können Sie keine VMs oder VM-Daten zwischen Systemen mit unterschiedlichen CPU-Herstellern (Intel zu AMD oder umgekehrt) wiederherstellen. Diese Einstellung unterstützt nur die Kompatibilität zwischen verschiedenen Generationen desselben Herstellers (z. B. Intel zu Intel oder AMD zu AMD).

