---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: Beachten Sie diese NetApp Backup und Recovery-Einschränkungen, bevor Sie Backup und Recovery in Ihrer Umgebung einsetzen. 
---
= Bekannte Einschränkungen bei NetApp Backup and Recovery für Hyper-V-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plattformen, Geräte oder Funktionen, die mit dieser Version nicht oder nicht gut funktionieren, sind hier aufgelistet.  Lesen Sie diese Einschränkungen sorgfältig durch.



== Nicht unterstützte Aktionen

Die folgenden Aktionen werden in Hyper-V-Workloads in NetApp Backup and Recovery nicht unterstützt:

* Erstellen Sie Ressourcengruppen mithilfe von VMs von mehreren Hyper-V-Hosts.
* Spanning-Disks (über mehrere CIFS-Freigaben hinweg)
* Unabhängig von der Einstellung „Prozessorkompatibilität“ in Hyper-V können Sie keine VMs oder VM-Daten zwischen Systemen mit unterschiedlichen CPU-Herstellern (Intel zu AMD oder umgekehrt) wiederherstellen. Diese Einstellung unterstützt nur die Kompatibilität zwischen verschiedenen Generationen desselben Herstellers (z. B. Intel zu Intel oder AMD zu AMD).

