---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: Zur Erhöhung der Sicherheit konfigurieren Sie den Zugriff für bestimmte Rollen in NetApp Backup und Recovery. 
---
= Richten Sie rollenbasierte Zugriffssteuerung in NetApp Backup and Recovery ein
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die rollenbasierte Zugriffssteuerung (RBAC) wird in der NetApp Console konfiguriert, um zu steuern, wer auf NetApp Backup and Recovery Ressourcen zugreifen kann. Administrativen oder Betrachterrollen können Workloads zugewiesen werden, die RBAC unterstützen. Workloads, die RBAC noch nicht unterstützen, bleiben für alle Benutzer mit Backup and Recovery Rollen zugänglich, bis eine Zuordnung auf Projekt- oder Flottenebene verfügbar ist.


NOTE: NetApp Console verwendet Projekte, um Ressourcen in Ordnern zu organisieren, während NetApp Console Local Deployment Projekte als Flotten bezeichnet.

Um den Zugriff auf Ressourcen in Ihrer Organisation zu steuern, sind diese Schritte auf der Seite *Administration > Identität und Zugriff* der NetApp Console auszuführen.


NOTE: Diese Schritte setzen voraus, dass Ihnen in der NetApp Console die Rolle des Organisationsadministrators zugewiesen ist.

.Schritte
. Erstellen Sie die Identitäts- und Zugriffsprojektstruktur.
+
Als Organisationsadministrator die Ordner- und Projektstruktur einrichten, in der die Workloads gespeichert werden.

. Benutzerrollen zuweisen.
+
.. Primäre Option:
+
Fügen Sie jedem für Arbeitslasten vorgesehenen Projekt Benutzer hinzu und weisen Sie ihnen die entsprechende Rolle zu. Beispiel:

+
*** *Organisationsadministrator* und *Backup and Recovery Superadministrator*: Ein Benutzer mit diesen Rollen kann alle Ressourcen organisationsübergreifend einsehen und Backup and Recovery Workloads ermitteln und diese Projekten zuweisen (zum Beispiel US East oder US West).
*** *Ordner- oder Projektadministrator* und *Backup and Recovery Superadministrator*: Ein Benutzer mit diesen Rollen kann nur die Ressourcen in seinem zugewiesenen Ordner oder Projekt anzeigen, kann jedoch Backup and Recovery Workloads erkennen und sie diesem Projekt zuweisen.


.. Alternative Option:
+
Anstatt einem Benutzer vollen Backup and Recovery-Administratorzugriff zu gewähren, können Sie sich selbst die Backup and Recovery-Superadmin-Rolle zuweisen und die Workloads direkt entdecken.



. Workloads in NetApp Backup and Recovery ermitteln.
+
Organisations-, Ordner- oder Projektadministratoren ermitteln die verfügbaren Workloads und wählen das entsprechende Projekt aus (z. B. US East oder US West). Jeder Workload wird automatisch dem ausgewählten Projekt zugeordnet.

. Fügen Sie Benutzer zu Projekten hinzu.
+
Organisations-, Ordner- oder Projektadministratoren fügen NetApp Console-Benutzer zu Projekten mit Workloads hinzu. Benutzern wird die Rolle „Organisationsbetrachter“ und eine „NetApp Backup and Recovery“-Rolle entsprechend ihren Zugriffsanforderungen zugewiesen. Benutzer mit der entsprechenden „NetApp Backup and Recovery“-Rolle erhalten automatisch Zugriff auf neue Workloads in diesen Projekten.





[[related-information]]
== Verwandte Informationen

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["Erfahren Sie mehr über das NetApp Console-Identitäts- und Zugriffsmanagement"^].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Backup and Recovery -Rollen in der NetApp Console"^].

