---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery muss zunächst Workloads erkennen, damit Sie diese schützen können. 
---
= Entdecken Sie Oracle-Workloads in NetApp Backup und Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery muss zuerst Ihre Oracle-Datenbanken erkennen, damit Sie sie schützen können.

*Erforderliche Konsolenrolle* Superadministrator für Backup und Wiederherstellung. Erfahren Sie mehr überlink:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp -Konsole für alle Dienste"^] .



== Hinzufügen eines Oracle-Hosts und Ermitteln von Ressourcen

Fügen Sie Oracle-Hostinformationen hinzu und lassen Sie NetApp Backup and Recovery die Workloads erkennen.  Wählen Sie in jedem Konsolenagenten die Systeme aus, auf denen Sie Workloads ermitteln möchten.

.Schritte
. Wählen Sie im NetApp -Konsolenmenü *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie in der Oracle-Kachel *Erkennen und verwalten* aus.
+
Wenn Sie sich zum ersten Mal bei diesem Dienst anmelden und bereits ein System in der Konsole haben, aber noch keine Ressourcen entdeckt haben, wird die Zielseite „Willkommen beim neuen NetApp Backup and Recovery“ angezeigt und bietet die Option „Ressourcen entdecken“.

. Wählen Sie *Ressourcen entdecken*.
. Geben Sie die folgenden Informationen ein:
+
.. *Workload-Typ*: Wählen Sie *Oracle*.
.. Wenn Sie für diesen Oracle-Host noch keine Anmeldeinformationen gespeichert haben, wählen Sie *Anmeldeinformationen hinzufügen*.
+
... Wählen Sie den Konsolenagenten aus, der mit diesem Host verwendet werden soll.
... Geben Sie einen Namen für diese Anmeldeinformationen ein.
... Geben Sie den Benutzernamen und das Kennwort für das Konto ein.
... Wählen Sie *Fertig*.


.. *Host-Registrierung*: Fügen Sie einen neuen Oracle-Host hinzu.  Geben Sie den FQDN oder die IP-Adresse, die Anmeldeinformationen, den Konsolenagenten und die Portnummer des Hosts ein.


. Wählen Sie *Entdecken*.
+

TIP: Dieser Vorgang kann einige Minuten dauern.



.Ergebnis
Die Oracle-Workload wird in der Liste der Workloads auf der Inventarseite angezeigt.



== Weiter zum NetApp Backup and Recovery Dashboard

. Um das NetApp Backup and Recovery Dashboard anzuzeigen, wählen Sie im oberen Menü *Dashboard*.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.

