---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery muss zunächst Workloads erkennen, damit Sie diese schützen können. 
---
= Entdecken Sie KVM-Workloads in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
KVM-Hosts und virtuelle Maschinen in NetApp Backup und Recovery können erkannt werden, sodass sie mit Schutzrichtlinien geschützt werden können. Die KVM-Umgebung muss vor der Erkennung von einer Managementplattform wie Apache CloudStack verwaltet werden.

*Erforderliche NetApp Console-Rolle* Backup and Recovery Superadministrator. Informationen zu link:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].



[[add-a-management-platform-kvm-host-and-discover-resources]]
== Fügen Sie eine Managementplattform und einen KVM-Host hinzu und ermitteln Sie die Ressourcen.

Fügen Sie Informationen zur Managementplattform und zum KVM-Host hinzu, damit NetApp Backup and Recovery die Workloads automatisch erkennt.


NOTE: Nach dem Hinzufügen eines Speichersystems zur NetApp Console sollte einige Minuten gewartet werden, bevor Ressourcen ermittelt werden. Die Ressourcenermittlung unmittelbar nach dem Hinzufügen eines Speichersystems kann dazu führen, dass die Ermittlung fehlschlägt.

.Schritte
. Wählen Sie im NetApp Console *Schutz* > *Sicherung und Wiederherstellung*.
. Wählen Sie unter *Workloads* die Kachel *KVM* aus.
. Wählen Sie *Ressourcen entdecken*.
. Geben Sie die folgenden Informationen ein:
+
.. *Workload-Typ*: Wählen Sie *KVM*.
.. Falls Sie Ihre Managementplattform noch nicht in Backup and Recovery integriert haben, wählen Sie *Managementplattform hinzufügen*.
+
... Geben Sie die folgenden Informationen ein:
+
**** *IP-Adresse oder FQDN der Managementplattform*: Die IP-Adresse oder ein FQDN der Managementplattform ist einzugeben.
**** *API-Schlüssel*: Geben Sie den API-Schlüssel ein, der zur Authentifizierung von API-Anfragen verwendet werden soll.
**** *Geheimer Schlüssel*: Geben Sie den geheimen Schlüssel ein, der zur Authentifizierung von API-Anfragen verwendet werden soll.
**** *Port*: Geben Sie den Port ein, der für die Kommunikation zwischen Backup und Recovery und der Managementplattform verwendet werden soll.
**** *Agenten*: Wählen Sie einen Konsolenagenten aus, der die Kommunikation zwischen Backup und Recovery und der Managementplattform erleichtern soll.


... Wenn Sie fertig sind, wählen Sie *Hinzufügen*.


.. *KVM-Einstellungen*: Führen Sie Folgendes aus:
+
... Falls noch keine Anmeldeinformationen für diesen KVM-Host gespeichert wurden, ist *Anmeldeinformationen hinzufügen* auszuwählen.
+
**** Wählen Sie den Konsolenagenten aus, der mit diesem Host verwendet werden soll.
**** Geben Sie einen Namen für diese Anmeldeinformationen ein.
**** Geben Sie den Benutzernamen und das Kennwort für das Konto ein.
**** Wählen Sie *Fertig*.


... Einen neuen KVM-Host hinzufügen, indem die folgenden Informationen eingegeben werden:
+
**** *KVM FQDN oder IP-Adresse*: Geben Sie den FQDN oder die IP-Adresse des Hosts ein.
**** *Agenten*: Der Konsolenagent wird für die Kommunikation zwischen Backup and Recovery und dem KVM-Host verwendet.
**** *Anmeldeinformationen*: Eine gespeicherte Anmeldeinformation für den KVM-Host auswählen.




.. *Erweiterte Einstellungen*: Optional kann ein Port für die Kommunikation mit dem KVM-Host eingegeben und die Managementplattform des Hosts aus der Liste ausgewählt werden.


. Wählen Sie *Entdecken*.
+

TIP: Dieser Vorgang kann einige Minuten dauern.



.Ergebnis
Die KVM-Arbeitslast wird in der Liste der Arbeitslasten auf der Inventarseite angezeigt.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Weiter zum NetApp Backup and Recovery Dashboard

.Schritte
. Wählen Sie im NetApp Console *Schutz* > *Sicherung und Wiederherstellung*.
. Die Kachel für die KVM Workload auswählen.
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.

