---
sidebar: sidebar 
permalink: br-start-switch-ui.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup und Recovery unterstützt verschiedene Workload-Typen, und einige Workloads verwenden eine andere Benutzeroberfläche. Mit dem Workload-Umschalter ist ein Wechsel zwischen ihnen möglich. 
---
= Zu einer anderen NetApp Backup und Recovery-Workload wechseln
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup und Recovery unterstützt verschiedene Workload-Typen, und einige Workloads verwenden eine andere Benutzeroberfläche. Mit dem Workload-Umschalter ist ein Wechsel zwischen ihnen möglich.



[[switch-to-a-different-workload]]
== Wechseln Sie zu einer anderen Arbeitslast

Sie können in der NetApp Backup and Recovery -Benutzeroberfläche zu einer anderen Arbeitslast wechseln.

.Schritte
. Wählen Sie in der linken Navigation der Konsole *Schutz* > *Sicherung und Wiederherstellung*.
. Wählen Sie in der oberen rechten Ecke der Seite die Dropdown-Liste *Workload wechseln* aus.
. Wählen Sie die Arbeitslast aus, zu der Sie wechseln möchten.
+
Die Seite wird aktualisiert und zeigt die ausgewählte Arbeitslast an.


