---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery muss zunächst Workloads erkennen, damit Sie diese schützen können. 
---
= Entdecken Sie Oracle-Datenbank-Workloads in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Erkennung von Oracle-Datenbanken ermöglicht es NetApp Backup and Recovery, diese durch das Erstellen und Wiederherstellen von Backups und Snapshots zu schützen.

*Erforderliche Konsolenrolle* Superadministrator für Backup und Wiederherstellung.  Erfahren Sie mehr überlink:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .



== Fügen Sie einen Oracle Database-Host hinzu und entdecken Sie Ressourcen

Fügen Sie Oracle-Hostinformationen hinzu und lassen Sie NetApp Backup and Recovery die Workloads erkennen. Wählen Sie in jedem Konsolenagenten die Systeme aus, auf denen Sie Workloads ermitteln möchten.

.Schritte
. Wählen Sie im NetApp Console *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie unter *Workloads* die Kachel *Oracle* aus.
. Wählen Sie *Ressourcen entdecken*.
. Wählen Sie *Oracle* für das Feld *Workload type* aus.
. Wenn Sie noch keine Anmeldeinformationen für diesen Oracle Database-Host gespeichert haben, wählen Sie *Add credentials*.
+
.. Wählen Sie den Konsolenagenten aus, der mit diesem Host verwendet werden soll.
.. Geben Sie einen Namen für diese Anmeldeinformationen ein.
.. Geben Sie den Benutzernamen und das Kennwort für das Konto ein.
.. Wählen Sie *Fertig*.


. *Hostregistrierung*: Fügen Sie einen neuen Oracle Database Host hinzu. Geben Sie im Feld *Host-FQDN oder IP-Adresse* den FQDN oder die IP-Adresse des Hosts ein – bei Clusterdatenbanken können Sie den FQDN oder die IP-Adresse eines beliebigen Knotens im Cluster eingeben. Geben Sie anschließend die Anmeldeinformationen, den Console Agent und die Portnummer an.
. (Optional) Wenn Sie Anmeldeinformationen für einen Nicht-Root-Benutzer auswählen, führen Sie Folgendes aus:
+
.. Anweisungen zum Hinzufügen des von Ihnen ausgewählten Nicht-Root-Benutzers zur sudoers-Datei auf dem Oracle Database-Host finden Sie unter *Configure sudoers*.
.. Folgen Sie den Anweisungen im Dialog, aktivieren Sie das Kontrollkästchen, wenn Sie fertig sind, und wählen Sie *Fertig*.


. *Erweiterte Einstellungen*: Führen Sie Folgendes aus:
+
.. Geben Sie den Port und den Installationspfad für das NetApp Plug-in ein. Das Plug-in ermöglicht die Kommunikation zwischen dem Oracle-Datenbankhost und NetApp Backup and Recovery.
.. Wählen Sie, ob NetApp Backup und Recovery das Plug-in automatisch auf jedem Host installieren oder die automatische Plug-in-Installation für alle Hosts überspringen soll. Wählen Sie *Anleitung anzeigen*, um Anweisungen zur manuellen Installation zu erhalten.
+
[NOTE]
====
Backup und Recovery verbindet sich per SSH mit jedem Host, um das Plug-in automatisch zu installieren. Aktivieren Sie die Option *manuelle Installation verwenden*, wenn einer der folgenden Punkte zutrifft:

*** Auf einem oder mehreren Hosts läuft der SSH-Dienst nicht.
*** Auf jedem Host ist das NetApp Plug-in bereits vorhanden (auch wenn es nur auf einigen Cluster-Mitgliedern vorhanden ist).
*** Sie bevorzugen es, das Plug-in auf jedem Host manuell zu installieren.


====
.. Wenn der Datenbankhost in einem Cluster organisiert ist, aktivieren Sie die Option *Alle Hosts im Cluster hinzufügen*, um alle Hosts im Cluster zu ermitteln.
.. Wählen Sie, ob vor der automatischen Installation des Plug-ins auf jedem Host Vorabprüfungen durchgeführt werden sollen. Schlagen die Prüfungen fehl, wird die automatische Plug-in-Installation gestoppt. Um die Prüfungen zu umgehen und das Plug-in trotzdem zu installieren, aktivieren Sie *Optionale Vorabprüfungen überspringen* (automatisch aktiviert, wenn Sie die manuelle Installation wählen).


. Wählen Sie *Entdecken*.
+

TIP: Das Hinzufügen von Ressourcen kann einige Minuten dauern. Um den Fortschritt zu sehen, wählen Sie *Fortschritt verfolgen* im Statusdialog unten auf der Inventarseite oder wählen Sie *Überwachung* im Menü auf der linken Seite.



.Ergebnis
Die Oracle Database-Workload wird in der Liste der Workloads auf der Inventarseite angezeigt.



== Weiter zum NetApp Backup and Recovery Dashboard

. Wählen Sie im NetApp Console *Schutz* > *Sicherung und Wiederherstellung*.
. Wählen Sie eine Workload-Kachel aus (z. B. Microsoft SQL Server).
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.

