---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery muss zunächst Workloads erkennen, damit Sie diese schützen können. 
---
= Entdecken Sie KVM-Workloads in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery muss KVM-Hosts und virtuelle Maschinen erkennen, bevor diese geschützt werden können. Bevor Sie Ihre KVM-Hosts und VMs zu Backup und Recovery hinzufügen können, müssen diese über eine Managementplattform wie Apache CloudStack verwaltet werden.

*Erforderliche Konsolenrolle* Superadministrator für Backup und Wiederherstellung.  Erfahren Sie mehr überlink:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .



== Fügen Sie eine Managementplattform und einen KVM-Host hinzu und ermitteln Sie die Ressourcen.

Fügen Sie Informationen zur Managementplattform und zum KVM-Host hinzu, damit NetApp Backup and Recovery die Workloads automatisch erkennt.

.Schritte
. Wählen Sie im NetApp Console *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie unter *Workloads* die Kachel *KVM* aus.
+
Wenn Sie sich zum ersten Mal bei Backup and Recovery anmelden und zwar ein System in der Konsole haben, aber keine Ressourcen erkannt wurden, wird die Seite _Willkommen bei der neuen NetApp Backup and Recovery_ mit einer Option zum *Erkennen von Ressourcen* angezeigt.

. Wählen Sie *Ressourcen entdecken*.
. Geben Sie die folgenden Informationen ein:
+
.. *Workload-Typ*: Wählen Sie *KVM*.
.. Falls Sie Ihre Managementplattform noch nicht in Backup and Recovery integriert haben, wählen Sie *Managementplattform hinzufügen*.
+
... Geben Sie die folgenden Informationen ein:
+
**** *IP-Adresse oder FQDN der Managementplattform*: Geben Sie die IP-Adresse oder den vollqualifizierten Domänennamen der Managementplattform ein.
**** *API-Schlüssel*: Geben Sie den API-Schlüssel ein, der zur Authentifizierung von API-Anfragen verwendet werden soll.
**** *Geheimer Schlüssel*: Geben Sie den geheimen Schlüssel ein, der zur Authentifizierung von API-Anfragen verwendet werden soll.
**** *Port*: Geben Sie den Port ein, der für die Kommunikation zwischen Backup und Recovery und der Managementplattform verwendet werden soll.
**** *Agenten*: Wählen Sie einen Konsolenagenten aus, der die Kommunikation zwischen Backup und Recovery und der Managementplattform erleichtern soll.


... Wenn Sie fertig sind, wählen Sie *Hinzufügen*.


.. *KVM-Einstellungen*: Fügen Sie einen neuen KVM-Host hinzu, indem Sie die folgenden Informationen eingeben:
+
*** *KVM FQDN oder IP-Adresse*: Geben Sie den FQDN oder die IP-Adresse des Hosts ein.
*** *Anmeldedaten*: Geben Sie den Benutzernamen und das Passwort für den KVM-Host ein.
*** *Konsolenagent*: Wählen Sie den Konsolenagenten aus, der für die Kommunikation zwischen Backup und Recovery und dem KVM-Host verwendet werden soll.
*** *Portnummer*: Geben Sie den Port ein, der für die Kommunikation zwischen Backup und Recovery und dem KVM-Host verwendet werden soll.
*** *Verwaltungsplattform*: Wenn der KVM-Host verwaltet wird und Sie die Verwaltungsplattform zu Backup und Wiederherstellung hinzugefügt haben, wählen Sie die Verwaltungsplattform aus der Liste aus.




. Wählen Sie *Entdecken*.
+

TIP: Dieser Vorgang kann einige Minuten dauern.



.Ergebnis
Die KVM-Arbeitslast wird in der Liste der Arbeitslasten auf der Inventarseite angezeigt.



== Weiter zum NetApp Backup and Recovery Dashboard

.Schritte
. Wählen Sie im NetApp Console *Schutz* > *Sicherung und Wiederherstellung*.
. Wählen Sie eine Workload-Kachel aus (z. B. Microsoft SQL Server).
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.

