---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Sie verwenden die NetApp Console , um sich beim NetApp Backup and Recovery -Dienst anzumelden. 
---
= Melden Sie sich bei NetApp Backup and Recovery an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei NetApp Backup and Recovery über die NetApp Console anmelden, um Workloads zu erkennen und Schutzvorgänge zu verwalten.

NetApp Backup and Recovery verwendet Identitäts- und Zugriffsverwaltung, um zu steuern, was jeder Benutzer tun kann.

Einzelheiten zu den Aktionen, die jede Rolle ausführen kann, finden Sie unterlink:reference-roles.html["NetApp Backup and Recovery -Benutzerrollen"] .

Um sich bei der NetApp Console anzumelden, können Sie Ihre NetApp Support Site-Zugangsdaten verwenden oder sich mit Ihrer E-Mail-Adresse und einem Passwort für ein NetApp Console-Konto registrieren https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Erfahren Sie mehr über die Anmeldung"^].

*Erforderliche NetApp Console-Rolle* Backup and Recovery Superadministrator oder Backup and Recovery Restore-Administrator. Für den Schutz von Daten, die auf einem Cloud Volumes ONTAP Cluster gespeichert sind, ist zusätzlich die Cloud Volumes ONTAP Admin-Rolle erforderlich. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

Um einen Konsolenagenten hinzuzufügen, müssen Sie über die Superadministratorrolle „Backup und Wiederherstellung“ verfügen.

.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie die NetApp Console verwenden, einen Webbrowser öffnen und zu  https://console.netapp.com/["NetApp Console"^] gehen.
** Wenn Sie die lokale Bereitstellung der NetApp Console verwenden, einen Webbrowser öffnen und zur IP-Adresse der Web-UI Ihrer lokalen Console-Bereitstellung gehen.
+
Die Anmeldeseite der NetApp Console wird angezeigt.



. Melden Sie sich bei der Konsole an.
. Wählen Sie in der linken Navigation der Konsole *Schutz* > *Sicherung und Wiederherstellung*.
+
** Wenn Sie sich zum ersten Mal bei Backup und Recovery anmelden und noch kein System zur Seite *Systeme* hinzugefügt haben, zeigt der Backup und Recovery-Service die Landingpage „Willkommen beim neuen NetApp Backup und Recovery“ mit einer Option zum Hinzufügen eines Systems an. Einzelheiten zum Hinzufügen eines Systems zur Seite *Systeme* sind unter  https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Erste Schritte mit dem Standardmodus der NetApp Console"^] zu finden.
** Wenn Sie sich zum ersten Mal bei Backup and Recovery anmelden und zwar ein System in der Konsole haben, aber keine Ressourcen erkannt wurden, wird die Seite _Willkommen bei der neuen NetApp Backup and Recovery_ mit einer Option zum *Erkennen von Ressourcen* angezeigt.


. Falls Sie dies noch nicht getan haben, *Entdecken und verwalten* auswählen.
+
** Informationen zu Microsoft SQL Server Workloads finden Sie unter link:br-start-discover.html["Entdecken Sie Microsoft SQL Server-Workloads"].
** Informationen zu VMware Workloads finden Sie unter link:br-use-vmware-discovery.html["Entdecken Sie VMware-Workloads"].
** Informationen zu KVM-Workloads finden Sie unter link:br-start-discover-kvm.html["Entdecken Sie KVM-Workloads"].
** Informationen zu Oracle Database Workloads finden Sie unter link:br-start-discover-oracle.html["Oracle Database-Workloads entdecken"].
** Informationen zu Hyper-V Workloads finden Sie unter link:br-start-discover-hyperv.html["Entdecken Sie Hyper-V-Workloads"].
** Informationen zu Kubernetes Workloads finden Sie unter link:br-start-discover-kubernetes.html["Entdecken Sie Kubernetes-Workloads"].



