---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: Lizenzieren Sie NetApp Backup and Recovery durch den Erwerb eines Pay-as-you-go- oder jährlichen Marketplace-Abonnements von Ihrem Cloud-Anbieter oder durch den Erwerb einer Bring-your-own-license von NetApp. 
---
= Einrichten der Lizenzierung für NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Lizenzierung für NetApp Backup und Recovery in der NetApp Console oder der lokalen NetApp Console-Bereitstellung kann über ein Marketplace-Abonnement oder eine eigene Lizenz (BYOL) von NetApp erfolgen. Eine gültige Lizenz ist erforderlich, damit der Service aktiviert, Backups erstellt und Daten auf Produktionssysteme wiederhergestellt werden können.

Ein paar Anmerkungen zur Funktionsweise von Lizenzen:

* Bei der Verwendung von ONTAP Volumes Workloads können Volumes ohne Lizenz erkannt und wiederhergestellt werden. Wenn Volumes jedoch geschützt (gesichert) werden sollen, ist der Erwerb einer Lizenz erforderlich.
* Wenn Sie Backup and Recovery mit NetApp Console lokaler Bereitstellung verwenden, kann ausschließlich eine Bring-Your-Own-License-(BYOL)-Lizenz erworben werden.
* Die Bring-Your-Own-License (BYOL) von NetApp Backup and Recovery ist eine Floating-Lizenz, die Sie auf allen Systemen verwenden können, die mit Ihrer NetApp Console -Organisation oder Ihrem NetApp Console-Konto verknüpft sind.  Wenn Ihnen also durch eine vorhandene BYOL-Lizenz ausreichend Sicherungskapazität zur Verfügung steht, müssen Sie keine weitere BYOL-Lizenz erwerben.
* Wenn eine BYOL-Lizenz mit NetApp Console verwendet wird, wird zusätzlich ein PAYGO-Abonnement empfohlen. Wenn mehr Daten gesichert werden, als durch die BYOL-Lizenz erlaubt ist, oder wenn die Laufzeit der Lizenz abläuft, wird die Sicherung über das Pay-as-you-go (PAYGO) Abonnement fortgesetzt, ohne dass es zu einer Unterbrechung des Service kommt.
* Beim Sichern von On-Premises ONTAP Daten in StorageGRID wird eine BYOL-Lizenz benötigt, für den Speicherplatz des Cloud-Anbieters fallen jedoch keine Kosten an.


link:concept-backup-to-cloud.html["Erfahren Sie mehr über die Kosten im Zusammenhang mit der Verwendung von NetApp Backup and Recovery."]



[[licensing-options-for-netapp-backup-and-recovery]]
== Lizenzierungsoptionen für NetApp Backup und Recovery

Es gibt drei Lizenzierungsoptionen für NetApp Backup and Recovery:

* Eine Direktlizenz, auch bekannt als Bring-Your-Own-License (BYOL), kann von NetApp erworben werden. Diese Option gilt sowohl für die NetApp Console als auch für die lokale Console-Bereitstellung.
* Ein Jahresvertrag kann über einen Hyperscaler Marketplace erworben werden. Diese Option gilt nur für die NetApp Console.
* Ein Abonnement für eine Pay-as-you-go-Lizenz (PAYGO) aus einem Hyperscaler-Marktplatz ist möglich. Diese Option gilt nur für die NetApp Console.




[[30-day-free-trial]]
=== 30 Tage kostenlos testen

Eine 30-tägige NetApp Backup and Recovery Testversion ist für alle nicht lizenzierten Workloads außer ONTAP Volumes Workloads verfügbar. Der Testzeitraum kann beim Beginn der Nutzung eines Workloads gestartet werden, noch bevor dessen Ressourcen erkannt werden. Nach dem Start des Testzeitraums werden dessen Status und die genutzte Kapazität unter *Free Trials* auf der NetApp Backup and Recovery Startseite angezeigt.



==== Kostenlose Testversion beenden

Sie können die kostenlose Testphase für eine Arbeitslast jederzeit auf der Startseite beenden, die nach der Anmeldung bei NetApp Backup and Recovery angezeigt wird. Wenn Sie NetApp Backup and Recovery nach Ablauf der kostenlosen Testphase weiterhin nutzen möchten, muss im Bereich *Licenses and subscriptions* der NetApp Console-Oberfläche ein kostenpflichtiges Abonnement eingerichtet werden. Wenn NetApp Backup and Recovery nicht weiter genutzt werden soll, kann die kostenlose Testphase ohne Abschluss eines kostenpflichtigen Abonnements beendet werden. Ein link:prev-ontap-backup-manage.html["Aufheben der Registrierung von NetApp Backup and Recovery vom System"] kann vor Ablauf der Testphase erfolgen, ohne dass Kosten entstehen.

.Schritte
. Auf der Startseite von NetApp Backup and Recovery unter *Kostenlose Testversionen* die gewünschte Testversion auswählen, die beendet werden soll.
. Wählen Sie *Kostenlose Testversion beenden*.
. Geben Sie *Testversion beenden* in das Feld ein.
. *Testversion beenden* auswählen, um zu bestätigen.




[[use-a-byol-license]]
=== Eine BYOL-Lizenz verwenden

Bring-Your-Own-Lizenzen von NetApp haben eine Laufzeit von 1, 2 oder 3 Jahren. Sie zahlen nur für die Daten, die Sie schützen, berechnet anhand der logisch genutzten Kapazität (_vor_ jeglicher Effizienz) der Quell- ONTAP -Volumes, die gesichert werden.  Diese Kapazität wird auch als Front-End-Terabyte (FETB) bezeichnet.

Bei der BYOL NetApp Backup and Recovery -Lizenz handelt es sich um eine Floating-Lizenz, bei der die Gesamtkapazität auf alle Systeme aufgeteilt wird, die mit Ihrer NetApp Console -Organisation oder Ihrem NetApp Console-Konto verknüpft sind.  Für ONTAP -Systeme können Sie eine grobe Schätzung der benötigten Kapazität erhalten, indem Sie den CLI-Befehl ausführen `volume show -fields logical-used-by-afs` für die Volumes, die Sie sichern möchten.

Falls Sie keine NetApp Backup und Recovery BYOL-Lizenz besitzen, kann das Chat-Symbol unten rechts in der Konsole ausgewählt werden, um eine solche zu erwerben.

Wenn Sie über eine nicht zugewiesene knotenbasierte Lizenz für Cloud Volumes ONTAP verfügen, die Sie nicht verwenden, können Sie diese optional in eine NetApp Backup and Recovery -Lizenz mit demselben Dollaräquivalent und demselben Ablaufdatum umwandeln. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Hier finden Sie weitere Einzelheiten"^] .

Sie verwenden die NetApp Console oder die NetApp Console lokale Bereitstellung, um BYOL-Lizenzen zu verwalten. Neue Lizenzen können hinzugefügt, bestehende Lizenzen aktualisiert und der Lizenzstatus in der Console angezeigt werden.

https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html["Informationen zum Hinzufügen von Lizenzen"^].



[[use-a-marketplace-license-applies-to-netapp-console-only]]
=== Eine Marketplace-Lizenz verwenden (gilt nur für die NetApp Console)

Bezahlen Sie jährlich für NetApp Backup and Recovery , indem Sie einen Jahresvertrag abschließen.  Sie sind mit einer Laufzeit von 1, 2 oder 3 Jahren erhältlich.

Wenn Sie einen Jahresvertrag von einem Marktplatz haben, wird der gesamte Verbrauch von NetApp Backup and Recovery über diesen Vertrag abgerechnet.

Wenn Sie AWS verwenden, stehen Ihnen zwei Jahresverträge zur Verfügung: https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWS Marketplace-Seite"^] für Cloud Volumes ONTAP und lokale ONTAP Systeme:

* Ein „Cloud Backup“-Plan, mit dem Sie Cloud Volumes ONTAP -Daten und lokale ONTAP -Daten sichern können.
+
Wenn Sie diese Option nutzen möchten, richten Sie Ihr Abonnement auf der Marketplace-Seite ein und dann https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["Verknüpfen Sie das Abonnement mit Ihren AWS-Anmeldeinformationen"^] . Beachten Sie, dass Sie mit diesem Jahresvertragsabonnement auch für Ihre Cloud Volumes ONTAP -Systeme bezahlen müssen, da Sie Ihren AWS-Anmeldeinformationen in der Konsole nur ein aktives Abonnement zuweisen können.

* Ein „CVO Professional“-Plan, der es Ihnen ermöglicht, Cloud Volumes ONTAP und NetApp Backup and Recovery zu bündeln.  Dies beinhaltet unbegrenzte Backups für das Cloud Volumes ONTAP System unter Verwendung der Lizenz (die Backup-Kapazität wird nicht auf die lizenzierte Kapazität angerechnet).  Mit dieser Option können Sie keine lokalen ONTAP -Daten sichern.
+
Siehe die https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Thema zur Lizenzierung von Cloud Volumes ONTAP"^] um mehr über diese Lizenzierungsoption zu erfahren.

+
Wenn Sie diese Option nutzen möchten, können Sie den Jahresvertrag einrichten, wenn Sie ein Cloud Volumes ONTAP -System erstellen. Die Konsole fordert Sie dann auf, den AWS Marketplace zu abonnieren.



Bei der Nutzung von Azure stehen zwei Jahresverträge vom https://marketplace.microsoft.com/en-us/product/netapp.netapp-bluexp["Azure Marketplace-Seite"^] für Cloud Volumes ONTAP und lokale ONTAP Systeme zur Verfügung:

* Ein „Cloud Backup“-Plan, mit dem Sie Cloud Volumes ONTAP -Daten und lokale ONTAP -Daten sichern können.
+
Wenn Sie diese Option nutzen möchten, richten Sie Ihr Abonnement auf der Marketplace-Seite ein und dann https://docs.netapp.com/us-en/console-setup-admin/task-adding-azure-accounts.html#subscribe["Verknüpfen Sie das Abonnement mit Ihren Azure-Anmeldeinformationen"^] . Beachten Sie, dass Sie mit diesem Jahresvertragsabonnement auch für Ihre Cloud Volumes ONTAP -Systeme bezahlen müssen, da Sie Ihren Azure-Anmeldeinformationen in der Konsole nur ein aktives Abonnement zuweisen können.

* Ein „CVO Professional“-Plan, der es Ihnen ermöglicht, Cloud Volumes ONTAP und NetApp Backup and Recovery zu bündeln.  Dies beinhaltet unbegrenzte Backups für das Cloud Volumes ONTAP System unter Verwendung der Lizenz (die Backup-Kapazität wird nicht auf die lizenzierte Kapazität angerechnet).  Mit dieser Option können Sie keine lokalen ONTAP -Daten sichern.
+
Siehe die https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Thema zur Lizenzierung von Cloud Volumes ONTAP"^] um mehr über diese Lizenzierungsoption zu erfahren.

+
Wenn Sie diese Option nutzen möchten, können Sie den Jahresvertrag einrichten, wenn Sie ein Cloud Volumes ONTAP -System erstellen und die Konsole Sie auffordert, den Azure Marketplace zu abonnieren.



Wenn Sie GCP verwenden, wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um einen Jahresvertrag abzuschließen.  Der Vertrag ist als privates Angebot im Google Cloud Marketplace verfügbar.

Nachdem NetApp Ihnen das private Angebot mitgeteilt hat, können Sie den Jahresplan auswählen, wenn Sie sich während der Aktivierung von NetApp Backup and Recovery über den Google Cloud Marketplace anmelden.



[[use-a-netapp-backup-and-recovery-paygo-subscription-applies-to-netapp-console-only]]
=== Ein NetApp Backup and Recovery PAYGO-Abonnement verwenden (gilt nur für die NetApp Console)

Bei der nutzungsbasierten Abrechnung zahlen Sie Ihrem Cloud-Anbieter die Kosten für Objektspeicherung und NetApp Backup-Lizenzierung stundenweise in einem einzigen Abonnement. Ein Abonnement für *NetApp Intelligent Services* im Marketplace wird auch bei Nutzung einer kostenlosen Testversion oder einer eigenen Lizenz (BYOL) empfohlen.

* Durch das Abonnement wird sichergestellt, dass es nach Ablauf Ihrer kostenlosen Testversion zu keiner Dienstunterbrechung kommt. Nach Ablauf der Testphase werden Ihnen stündlich Gebühren entsprechend der Menge der von Ihnen gesicherten Daten berechnet.
* Wenn Sie mehr Daten sichern, als Ihre BYOL-Lizenz zulässt, werden die Datensicherungs- und Wiederherstellungsvorgänge über Ihr Pay-as-you-go-Abonnement fortgesetzt.  Wenn Sie beispielsweise über eine BYOL-Lizenz mit 10 TiB verfügen, wird die gesamte Kapazität über 10 TiB hinaus über das PAYGO-Abonnement abgerechnet.


Während Ihrer kostenlosen Testphase oder wenn Sie Ihre BYOL-Lizenz nicht überschritten haben, werden Ihnen keine Kosten für Ihr Pay-as-you-go-Abonnement in Rechnung gestellt.

Es gibt einige PAYGO-Pläne für NetApp Backup and Recovery:

* Ein „Cloud Backup“-Paket, mit dem Sie Cloud Volumes ONTAP Daten und lokale ONTAP -Daten sichern können.
* Ein „CVO Professional“-Paket, mit dem Sie Cloud Volumes ONTAP und NetApp Backup and Recovery bündeln können.  Dies beinhaltet unbegrenzte Backups für das Cloud Volumes ONTAP System unter Verwendung der Lizenz (die Backup-Kapazität wird nicht auf die lizenzierte Kapazität angerechnet).  Mit dieser Option können Sie keine lokalen ONTAP -Daten sichern.
+
Diese Option erfordert außerdem ein Backup und Recovery PAYGO-Abonnement, jedoch fallen bei berechtigten Cloud Volumes ONTAP Systemen keine Gebühren an.



https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Erfahren Sie mehr über diese kapazitätsbasierten Lizenzpakete"].

Verwenden Sie diese Links, um NetApp Backup and Recovery über den Marktplatz Ihres Cloud-Anbieters zu abonnieren:

* AWS: https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Preisdetails finden Sie im Marketplace-Angebot für NetApp Intelligent Services."^] Die
* Azure: https://marketplace.microsoft.com/en-us/product/netapp.cloud-manager?tab=Overview["Preisdetails finden Sie im Marketplace-Angebot für NetApp Intelligent Services."^].
* Google Cloud: https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Preisdetails finden Sie im Marketplace-Angebot für NetApp Intelligent Services."^] Die




[[exceeding-license-capacity]]
== Überschreitung der Lizenzkapazität

Das Überschreiten des lizenzierten Speicherkontingents löst PAYGO-Gebühren aus. Ohne PAYGO-Abonnement ist das Erstellen neuer Backups nicht möglich, bestehende Backups können jedoch weiterhin ohne Servicegarantie wiederhergestellt werden. Die Lizenz sollte vor Ablauf erneuert werden, da eine abgelaufene Lizenz neue Backups verhindert und den Service beeinträchtigt.



[[what-happens-when-your-license-expires]]
== Was passiert, wenn Ihre Lizenz abläuft

Wenn Ihre Backup and Recovery Lizenz abläuft:

* Backups aus bestehenden Backup-Richtlinien und Wiederherstellungen funktionieren weiterhin.
* Es ist nicht möglich, neue Sicherungsrichtlinien zu erstellen oder den Schutz auf zusätzliche Workloads und Datenspeicher auszuweiten.
* Neue Backup and Recovery Funktionen und Verbesserungen stehen nicht zur Verfügung.
* NetApp technischer Support für Backup und Recovery ist nicht mehr verfügbar.


Lizenzverlängerung für:

* Backup-Richtlinien können erstellt und geändert werden, einschließlich Richtlinien für applikationskonsistente Backups von Datenbanken, VMs und Kubernetes-Workloads.
* Neue Backup and Recovery Funktionen und Verbesserungen stehen zur Verfügung.
* Sie erhalten weiterhin NetApp technischen Support.

