---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery muss virtuelle Hyper-V-Maschinen erkennen, bevor Sie sie schützen können. 
---
= Entdecken Sie Hyper-V-Workloads in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hyper-V-VMs in NetApp Backup und Recovery können erkannt werden, sodass sie mit Schutzrichtlinien geschützt werden können.

*Erforderliche Konsolenrolle* Backup und Recovery Superadministrator. Informationen zu link:reference-roles.html["Backup und Recovery Rollen und Berechtigungen"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].



[[add-a-hyper-v-host-and-discover-resources]]
== Hinzufügen eines Hyper-V-Hosts und Ermitteln von Ressourcen

Fügen Sie Hyper-V-Hostinformationen hinzu, damit NetApp Backup und Recovery virtuelle Maschinen erkennen kann. Innerhalb jedes Console-Agenten die Systeme auswählen, auf denen Ressourcen erkannt werden sollen.


NOTE: Wenn Sie Hyper-V-Hosts hinzufügen und Ressourcen ermitteln, installiert NetApp Backup and Recovery das NetApp Hyper-V-Plug-in und das NetApp SnapCenter Windows FileSystem-Plug-in auf dem Hyper-V-Host, um die Verwaltung und den Schutz virtueller Maschinen zu unterstützen.

.Schritte
. Im NetApp Console-Menü *Schutz* > *Backup und Recovery* auswählen.
+
Wenn Sie sich zum ersten Mal bei NetApp Backup und Recovery anmelden und bereits ein System in der Console haben, aber noch keine Ressourcen entdeckt wurden, erscheint die Landingpage „Willkommen beim neuen NetApp Backup und Recovery“ mit einer Option zum *Entdecken von Ressourcen*.

. Wählen Sie *Ressourcen entdecken*.
. Geben Sie die folgenden Informationen ein:
+
.. *Workload-Typ*: Wählen Sie *Hyper-V*.
.. Wenn Sie für diesen Hyper-V-Host noch keine Anmeldeinformationen gespeichert haben, wählen Sie *Anmeldeinformationen hinzufügen*.
+
... Wählen Sie den Konsolenagenten aus, der mit diesem Host verwendet werden soll.
... Geben Sie einen Namen für diese Anmeldeinformationen ein.
... Geben Sie den Benutzernamen und das Kennwort für das Konto ein.
... Wählen Sie *Fertig*.


.. *Hostregistrierung*: Fügen Sie einen neuen Hyper-V-Host hinzu, indem Sie den FQDN oder die IP-Adresse des Hosts, die Anmeldeinformationen, den Konsolenagenten und die Portnummer eingeben. Falls der FQDN vom Konsolenagenten nicht aufgelöst werden kann, verwenden Sie stattdessen die IP-Adresse. Geben Sie für FCI-Cluster die Management-IP-Adresse des FCI-Clusters ein.


. Wählen Sie *Entdecken*.
+

TIP: Dieser Vorgang kann einige Minuten dauern.



.Ergebnis
Nachdem NetApp Backup and Recovery Ressourcen erkannt hat, wird auf der Seite „Inventar“ die Hyper-V-Arbeitslast in der Liste der Arbeitslasten angezeigt.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Weiter zum NetApp Backup and Recovery Dashboard

.Schritte
. Im NetApp Console-Menü *Schutz* > *Backup und Recovery* auswählen.
. Die Hyper-V-Workload-Kachel auswählen.
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.

