---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: Bevor Sie NetApp Backup and Recovery verwenden, führen Sie einige Schritte zum Einrichten von Sicherungszielen aus. 
---
= Richten Sie Sicherungsziele ein, bevor Sie NetApp Backup and Recovery verwenden
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bevor Sie NetApp Backup and Recovery verwenden, führen Sie einige Schritte zum Einrichten von Sicherungszielen aus.

Bevor Sie beginnen, überprüfen Sielink:concept-start-prereq.html["Voraussetzungen"] um sicherzustellen, dass Ihre Umgebung bereit ist.



== Vorbereiten des Sicherungsziels

Bereiten Sie eines oder mehrere der folgenden Sicherungsziele vor:

* NetApp StorageGRID.
+
Siehe https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["Entdecken Sie StorageGRID"^] .

+
Siehe https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID -Dokumentation"^] für Details zu StorageGRID.

* Amazon Web Services. Siehe https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Amazon S3-Dokumentation"^] .
+
Gehen Sie wie folgt vor, um AWS als Sicherungsziel vorzubereiten:

+
** Richten Sie ein Konto in AWS ein.
** Konfigurieren Sie die S3-Berechtigungen in AWS, die im nächsten Abschnitt aufgeführt sind.
** Weitere Informationen zur Verwaltung Ihres AWS-Speichers in der Konsole finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Verwalten Sie Ihre Amazon S3-Buckets"^] .




* Microsoft Azure.
+
** Siehe https://docs.netapp.com/us-en/storage-management-azure-netapp-files/index.html["Azure NetApp Files Dokumentation"^] .
** Richten Sie ein Konto in Azure ein.
** Konfigurieren https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure-Berechtigungen"^] in Azure.
** Weitere Informationen zur Verwaltung Ihres Azure-Speichers in der Konsole finden Sie unter https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Verwalten Ihrer Azure-Speicherkonten"^] .




Nachdem Sie Optionen im Sicherungsziel selbst konfiguriert haben, konfigurieren Sie es später als Sicherungsziel in NetApp Backup and Recovery.  Einzelheiten zum Konfigurieren des Sicherungsziels in NetApp Backup and Recovery finden Sie unterlink:br-start-discover-backup-targets.html["Ermitteln von Sicherungszielen"] .



== S3-Berechtigungen einrichten

Sie müssen zwei Sätze von AWS S3-Berechtigungen konfigurieren:

* Berechtigungen für den Konsolenagenten zum Erstellen und Verwalten des S3-Buckets.
* Berechtigungen für den lokalen ONTAP Cluster, damit dieser Daten aus dem S3-Bucket lesen und schreiben kann.


.Schritte
. Stellen Sie sicher, dass der Konsolenagent über die erforderlichen Berechtigungen verfügt. Weitere Einzelheiten finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["Richtlinienberechtigungen für die NetApp Konsole"] .
+

NOTE: Wenn Sie Backups in AWS China-Regionen erstellen, müssen Sie den AWS-Ressourcennamen „arn“ unter allen _Resource_-Abschnitten in den IAM-Richtlinien von „aws“ in „aws-cn“ ändern. Beispiel: `arn:aws-cn:s3:::netapp-backup-*` .

. Wenn Sie den Dienst aktivieren, werden Sie vom Backup-Assistenten aufgefordert, einen Zugriffsschlüssel und einen geheimen Schlüssel einzugeben.  Diese Anmeldeinformationen werden an den ONTAP Cluster weitergegeben, damit ONTAP Daten im S3-Bucket sichern und wiederherstellen kann.  Dazu müssen Sie einen IAM-Benutzer mit den folgenden Berechtigungen erstellen.
+
Weitere Informationen finden Sie im https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS-Dokumentation: Erstellen einer Rolle zum Delegieren von Berechtigungen an einen IAM-Benutzer"^] .

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

