---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery muss zunächst Workloads erkennen, damit Sie den Dienst nutzen können. 
---
= Entdecken Sie Kubernetes-Workloads in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery muss Kubernetes-Workloads erkennen, bevor sie geschützt werden können.

*Erforderliche NetApp Console-Rolle* Backup and Recovery Superadministrator. Für den Schutz von Daten, die auf einem Cloud Volumes ONTAP Cluster gespeichert sind, ist zusätzlich die Cloud Volumes ONTAP Admin-Rolle erforderlich. Informationen zu link:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].



[[discover-kubernetes-workloads]]
== Entdecken Sie Kubernetes-Workloads

Im Backup and Recovery-Inventar werden Kubernetes-Workloads in Ihrer Umgebung erkannt. Das Hinzufügen eines Workloads fügt einen Kubernetes-Cluster zu NetApp Backup and Recovery hinzu. Anschließend können Anwendungen hinzugefügt und Clusterressourcen geschützt werden. Optional lassen sich lokal isolierte Kubernetes-Ressourcen mithilfe der lokalen Bereitstellung der NetApp Console erkennen.

[NOTE]
====
Wenn Sie einen Cluster entdecken, der aktuell mit Trident Protect geschützt ist, werden alle mit Trident Protect verwendeten Sicherungszeitpläne während des Erkennungsprozesses deaktiviert (Trident Protect-Sicherungszeitpläne sind nicht mit Backup and Recovery kompatibel). Um die Anwendungen des Clusters zu schützen, link:br-use-policies-create.html["eine neue Datensicherungsstrategie erstellen"] oder ordnen Sie die Anwendungen einer bestehenden Richtlinie zu. Sie können dann die Trident Protect-Sicherungszeitpläne bei Bedarf entfernen.

====
.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie Kubernetes-Workloads zum ersten Mal entdecken, wählen Sie in NetApp Backup and Recovery unter *Workloads* die Kachel *Kubernetes* aus.
** Wenn Sie Kubernetes-Workloads bereits erkannt haben, wählen Sie in NetApp Backup and Recovery*Inventar* > *Workloads* und dann *Ressourcen erkennen*.


. Wählen Sie den Workloadtyp *Kubernetes* aus.
. Geben Sie einen Clusternamen ein und wählen Sie einen Konsolenagenten aus, der mit dem Cluster verwendet wird.
+
NetApp Backup and Recovery bietet Anweisungen, die sich je nach ausgewähltem Installationstyp ändern. Bei einer lokalen Bereitstellung der NetApp Console können Anweisungen ausgewählt werden, die das Erkennen von vom Netzwerk getrennten Ressourcen ohne externe Netzwerkverbindung ermöglichen.

. Einen Installationstyp auswählen, um die Anweisungen zur Installation von Trident Protect auf Ihrem Kubernetes-Cluster anzuzeigen:
+
** *Verbunden* auswählen, um Cluster mit externer Netzwerkanbindung zu ermitteln.
** *Air-gapped* auswählen, um Cluster zu ermitteln, die keine externe Netzwerkverbindung haben.
+
[role="tabbed-block"]
====
.Vernetzte Entdeckung
--
... Befolgen Sie die Befehlszeilenanweisungen, die in Backup and Recovery angezeigt werden. Diese Schritte gewährleisten, dass Backup and Recovery mit dem Cluster interagieren kann.


--
.Air-gapped Discovery
--
... Geben Sie die URL Ihrer privaten Docker-Container-Registry ein. Diese Registry dient zum Herunterladen der Trident Protect- und Trident Protect Connector-Images während der Installation.
... Wenn Ihre private Container-Registry eine Authentifizierung erfordert, kann eine der folgenden Methoden zur Konfiguration der Registry-Anmeldeinformationen verwendet werden:
+
**** *Authentifizierung auf Knotenebene*: Die Registry-Anmeldeinformationen werden in der Container-Laufzeitumgebung auf jedem Knoten konfiguriert. Nach der Konfiguration können alle Pods Images abrufen, ohne dass zusätzliche Helm-Einstellungen erforderlich sind.
**** *Kubernetes Image Pull Secret*: Ein Kubernetes Image Pull Secret wird im  `trident-protect` Namespace erstellt und anschließend beim Helm-Upgrade-Schritt in den Trident Protect-Installationsanweisungen referenziert:
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Befolgen Sie die Befehlszeilenanweisungen, die in Backup and Recovery angezeigt werden, und fügen Sie während des Helm-Schritts (falls erforderlich) die Informationen zum Image Pull Secret hinzu. Diese Schritte stellen sicher, dass Backup and Recovery mit dem Cluster interagieren kann.


--
====


. Nach Abschluss der Installationsschritte von Trident Protect wird *Entdecken* ausgewählt.
+
Der Cluster wird zum Inventar hinzugefügt.

. Wählen Sie in der zugehörigen Kubernetes-Workload „Anzeigen“ aus, um die Liste der Anwendungen, Cluster und Namespaces für diese Workload anzuzeigen.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Weiter zum NetApp Backup and Recovery Dashboard

Führen Sie die folgenden Schritte aus, um das NetApp Backup and Recovery Dashboard anzuzeigen.

. Wählen Sie im NetApp Console *Schutz* > *Sicherung und Wiederherstellung*.
. Die Kachel „Kubernetes Workload“ auswählen.
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
. Überprüfen Sie den Zustand des Datenschutzes.  Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu entdeckten, geschützten und gesicherten Workloads.
+
link:br-use-dashboard.html["Erfahren Sie, was Ihnen das Dashboard anzeigt"].


