---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: Der Schutz Ihrer Microsoft SQL Server-Anwendungsdaten von lokalen ONTAP Systemen bis zu Amazon Web Services, Microsoft Azure oder StorageGRID erfolgt mit NetApp Backup und Recovery. 
---
= Microsoft SQL Server Workloads mit NetApp Backup und Recovery schützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Microsoft SQL Server-Datenbanken können von lokalen ONTAP-Systemen auf AWS, Azure oder StorageGRID mithilfe von NetApp Backup and Recovery gesichert werden. Eine 3-2-1-Backup-Strategie mit Snapshots auf dem primären Speicher, Replikation auf sekundären Speicher und Kopien auf Objektspeicher lässt sich umsetzen.

NetApp Backup and Recovery verwendet NetApp SnapMirror , um Backups zu synchronisieren, indem Snapshots erstellt und an die Backup-Speicherorte übertragen werden.

Die folgenden Arbeitsabläufe dienen dem Schutz Ihrer Daten:

* link:concept-start-prereq-snapcenter-import.html["Konfigurieren Sie zusätzliche Elemente beim Importieren aus SnapCenter"]
* link:br-start-discover.html["Entdecken Sie Microsoft SQL Server-Workloads und importieren Sie optional SnapCenter -Ressourcen"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads mit lokalen Snapshots auf dem lokalen ONTAP Primärspeicher"]
* link:br-use-mssql-backup.html["Replizieren Sie Workloads auf den sekundären ONTAP -Speicher"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads an einem Objektspeicherort"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads jetzt"]
* link:br-use-mssql-restore.html["Wiederherstellen von Workloads"]
* link:br-use-mssql-clone.html["Klonen von Workloads"]
* link:br-use-manage-inventory.html["Verwalten des Workload-Inventars"]
* link:br-use-manage-snapshots.html["Verwalten von Snapshots"]


Zum Sichern von Workloads erstellen Sie Richtlinien, die Sicherungs- und Wiederherstellungsvorgänge verwalten. Sehenlink:br-use-policies-create.html["Erstellen von Richtlinien"] für weitere Informationen.

.Unterstützte Sicherungsziele
NetApp Backup und Recovery unterstützt Backups von Microsoft SQL Server Instanzen und Datenbanken von den folgenden Quellsystemen zu den aufgeführten Sekundärsystemen und Objektspeichern in öffentlichen und privaten Clouds. Snapshots verbleiben auf dem Quellsystem.

[cols="33,33,33"]
|===
| Quellsystem | Sekundärsystem (Replikation) | Objektspeicher (Backup) 


| Cloud Volumes ONTAP in AWS | Cloud Volumes ONTAP in AWS On-Premises- ONTAP -System | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP in Azure | Cloud Volumes ONTAP in Azure On-Premises- ONTAP -System | Azure Blob ONTAP S3 


| On-Premises- ONTAP -System | Cloud Volumes ONTAP On-Premises ONTAP -System | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===
.Unterstützte Wiederherstellungsziele
Sie können Microsoft SQL Server Instanzen und Datenbanken aus einem Backup, das sich im primären Storage, einem sekundären System (repliziertes Volume) oder im Objektspeicher (Backup-Datei) befindet, auf die folgenden Zielsysteme wiederherstellen. Snapshots befinden sich auf dem Quellsystem und können nur auf demselben System wiederhergestellt werden.

[cols="33,33,33"]
|===
2+| Vom Speicherort der Sicherungsdatei | Zum Zielsystem 


| *Objektspeicher (Backup)* | *Sekundärsystem (Replikation)* |  


| Amazon S3 | Cloud Volumes ONTAP in AWS On-Premises- ONTAP -System | Cloud Volumes ONTAP in AWS On-premises ONTAP System ONTAP S3 


| Azure-Blob | Cloud Volumes ONTAP in Azure On-Premises- ONTAP -System | Cloud Volumes ONTAP in Azure Lokales ONTAP -System ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP On-Premises ONTAP -System | On-Premises ONTAP -System ONTAP S3 
|===

NOTE: Verweise auf „On-Premises ONTAP -Systeme“ umfassen FAS und AFF Systeme.
