---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: Manuelle Erstellung von On-Demand-Backups von Kubernetes-Anwendungen über die NetApp Backup und Recovery Web-Benutzeroberfläche. 
---
= Eine Kubernetes-Anwendung mit der NetApp Backup und Recovery Web-Oberfläche sichern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Web-UI kann verwendet werden, um eine bedarfsgesteuerte Sicherung einer Kubernetes-Anwendung durchzuführen.

.Erforderliche NetApp Console
Organisationsadministrator oder SnapCenter Administrator. link:reference-roles.html["Erfahren Sie mehr über die Zugriffsrollen für NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .



[[back-up-a-kubernetes-application]]
== Sichern einer Kubernetes-Anwendung

Erstellen Sie manuell ein Backup einer Kubernetes-Anwendung, um eine Basis für zukünftige Backups und Snapshots zu schaffen oder um sicherzustellen, dass die aktuellsten Daten geschützt sind.

.Schritte
. Wählen Sie in NetApp Backup and Recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz aus und wählen Sie *Anzeigen*, um auf die mit dieser Instanz verknüpften Ressourcen zuzugreifen.
. Wählen Sie die Registerkarte *Anwendungen*.
. In der Anwendungsliste eine Anwendung auswählen, die gesichert werden soll, und das zugehörige Aktionsmenü öffnen.
. Wählen Sie *Jetzt sichern*.
. Bestätigen Sie, dass die richtige Anwendung ausgewählt ist.
. Wählen Sie *Sichern*.


.Ergebnis
Die Konsole erstellt eine Sicherungskopie der Anwendung und zeigt den Fortschritt im Bereich *Überwachung* von Sicherung und Wiederherstellung an. Das Backup wird basierend auf der mit der Anwendung verknüpften Schutzrichtlinie erstellt.
