---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Schützen Sie Ihre Hyper-V-Workloads mit NetApp Backup and Recovery. 
---
= Wiederherstellen von Hyper-V-Workloads mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Stellen Sie Hyper-V-Workloads aus Snapshots, aus einer auf Sekundärspeicher replizierten Workload-Sicherung oder aus in Objektspeichern gespeicherten Sicherungen mithilfe von NetApp Backup and Recovery wieder her.

.Von diesen Speicherorten wiederherstellen
Sie können Workloads von verschiedenen Startorten wiederherstellen:

* Wiederherstellung von einem primären Standort (lokaler Snapshot)
* Wiederherstellen von einer replizierten Ressource auf einem sekundären Speicher
* Wiederherstellung aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten bis zu diesen Punkten wiederherstellen:

* Am ursprünglichen Speicherort wiederherstellen


.Überlegungen zur Wiederherstellung aus dem Objektspeicher
Wenn Sie eine Sicherungsdatei im Objektspeicher auswählen und für diese Sicherung der Ransomware-Schutz aktiv ist (wenn Sie DataLock und Ransomware Resilience in der Sicherungsrichtlinie aktiviert haben), werden Sie aufgefordert, vor der Wiederherstellung der Daten eine zusätzliche Integritätsprüfung der Sicherungsdatei durchzuführen.  Wir empfehlen Ihnen, den Scan durchzuführen.


TIP: Für den Zugriff auf den Inhalt der Sicherungsdatei fallen bei Ihrem Cloud-Anbieter zusätzliche Kosten für den Datenverkehr an.



== So funktioniert die Wiederherstellung von Workloads

Beim Wiederherstellen von Workloads geschieht Folgendes:

* Wenn Sie eine Workload aus einer lokalen Sicherungsdatei wiederherstellen, erstellt NetApp Backup and Recovery mithilfe der Daten aus der Sicherung eine _neue_ Ressource.
* Wenn Sie eine Wiederherstellung aus einem replizierten Workload durchführen, können Sie den Workload auf dem ursprünglichen System oder auf einem lokalen ONTAP System wiederherstellen.


Auf der Seite „Wiederherstellen“ (auch als „Suchen und Wiederherstellen“ bezeichnet)* können Sie eine Ressource wiederherstellen, auch wenn Sie sich nicht an den genauen Namen, den Speicherort oder das Datum erinnern, an dem sie zuletzt in gutem Zustand war. Sie können mithilfe von Filtern nach dem Schnappschuss suchen.



== Wiederherstellen von Workload-Daten über die Option „Wiederherstellen“ (Suchen und Wiederherstellen)

Stellen Sie Hyper-V-Workloads mit der Option „Wiederherstellen“ wieder her. Sie können nach dem Snapshot anhand seines Namens oder mithilfe von Filtern suchen.

*Erforderliche Konsolenrolle* Superadministrator für Backup und Wiederherstellung oder Administratorrolle für Backup und Wiederherstellung zur Wiederherstellung. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .

.Schritte
. Wählen Sie im NetApp Backup and Recovery -Menü *Wiederherstellen* aus.
. Wählen Sie aus der Dropdown-Liste rechts neben dem Namenssuchfeld *Hyper-V* aus.
. Geben Sie den Namen der Ressource ein, die Sie wiederherstellen möchten, oder filtern Sie nach dem VM-Namen, VM-Host oder Speicherpool, in dem sich die wiederherzustellende Ressource befindet.
+
Es wird eine Liste mit Snapshots angezeigt, die Ihren Suchkriterien entsprechen.

. Wählen Sie die Schaltfläche *Wiederherstellen* für den Snapshot, den Sie wiederherstellen möchten.
+
Es wird eine Liste möglicher Wiederherstellungspunkte angezeigt.

. Wählen Sie den Wiederherstellungspunkt aus, den Sie verwenden möchten.
. Wählen Sie einen Quellspeicherort für den Snapshot aus.
. Wählen Sie *Weiter*, um fortzufahren.
. Wählen Sie das Wiederherstellungsziel und die Einstellungen aus:


[discrete]
===== Zielauswahl

[role="tabbed-block"]
====
.Am ursprünglichen Speicherort wiederherstellen
--
Wenn Sie zum ursprünglichen Speicherort zurückkehren, können Sie die Zieleinstellungen einsehen, indem Sie den Abschnitt *Zieleinstellungen* erweitern. Sie können diese jedoch nicht ändern.

. Im Abschnitt *Optionen nach der Wiederherstellung* sollten Sie folgende Option in Betracht ziehen:
+
*Virtuelle Maschine neu starten*: Aktivieren Sie diese Option, um die neue virtuelle Maschine nach der Wiederherstellung zu starten.

. Wählen Sie *Wiederherstellen*.


--
.An einem anderen Speicherort wiederherstellen
--
Nicht verfügbar für Hyper-V-Workloads in der Vorschau.

--
====