---
sidebar: sidebar 
permalink: br-use-hyperv-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Sie können virtuelle Hyper-V-Maschinen von lokalen ONTAP Systemen auf primärem und sekundärem Speicher schützen und so sicherstellen, dass Ihre Daten geschützt sind. 
---
= Hyper-V-Workloads mit NetApp Backup und Recovery schützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup und Recovery ermöglicht das Sichern und Wiederherstellen von eigenständigen Hyper-V-VMs, FCI-Clusterinstanzen und von SCVMM bereitgestellten VMs, die auf einer CIFS-Freigabe gehostet werden.

Hyper-V-Workloads können in Amazon S3 oder StorageGRID gesichert und auf einem lokalen Hyper-V-Host wiederhergestellt werden.

NetApp Backup und Recovery ermöglicht die Umsetzung einer 3-2-1-Schutzstrategie, bei der 3 Kopien Ihrer Quelldaten auf 2 verschiedenen Speichersystemen und 1 Kopie in der Cloud gespeichert werden. Zu den Vorteilen des 3-2-1-Ansatzes gehören:

* Mehrere Datenkopien schützen vor internen und externen Cybersicherheitsbedrohungen.
* Mehrere Medientypen gewährleisten die Failover-Funktionalität im Falle eines physischen oder logischen Ausfalls eines Medientyps.
* Die vor Ort Kopie ermöglicht eine schnelle Wiederherstellung von Daten, und die externen Kopien stehen zur Verfügung, falls die vor Ort Kopie kompromittiert ist.


Wenn Hyper-V-Hosts hinzugefügt und Ressourcen ermittelt werden, installiert NetApp Backup and Recovery das NetApp Hyper-V Plug-in und das NetApp SnapCenter Windows FileSystem Plug-in auf jedem Hyper-V-Host, um die Verwaltung und den Schutz virtueller Maschinen zu unterstützen.

Mit NetApp Backup and Recovery können Sie die folgenden Aufgaben im Zusammenhang mit Hyper-V-Workloads ausführen:

* link:br-start-discover-hyperv.html["Entdecken Sie Hyper-V-Workloads"]
* link:br-use-hyperv-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für Hyper-V-Workloads"]
* link:br-use-hyperv-backup.html["Sichern Sie Hyper-V-Workloads"]
* link:br-use-hyperv-restore.html["Wiederherstellen von Hyper-V-Workloads"]

