---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Schützen Sie Ihre Hyper-V-Workloads mit NetApp Backup and Recovery. 
---
= Wiederherstellen von Hyper-V-Workloads mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hyper-V-Workloads können mithilfe von NetApp Backup und Recovery aus lokalen Snapshots, replizierten Backups auf Sekundärspeichern oder Backups im Objektspeicher wiederhergestellt werden.

.Von diesen Speicherorten wiederherstellen
Sie können Workloads von diesen Speicherorten wiederherstellen:

* Wiederherstellung von einem primären Standort (lokaler Snapshot)
* Wiederherstellen von einer replizierten Ressource auf einem sekundären Speicher
* Wiederherstellung aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten an diesen Zielen wiederherstellen:

* Wiederherstellung am ursprünglichen Speicherort (vom primären, sekundären und Objektspeicher)
* Wiederherstellung an einem alternativen Speicherort (aus primärem, sekundärem und Objektspeicher)


.Überlegungen zur Wiederherstellung aus dem Objektspeicher
Wenn Sie eine Sicherungsdatei im Objektspeicher auswählen und für diese Sicherung der Ransomware-Schutz aktiviert ist, weil Sie DataLock und den Ransomware-Schutz in der Sicherungsrichtlinie aktiviert haben, erfolgt eine Aufforderung, vor der Wiederherstellung der Daten eine zusätzliche Integritätsprüfung durchzuführen. Das Ausführen des Scans wird empfohlen.


TIP: Für den Zugriff auf den Inhalt der Sicherungsdatei fallen bei Ihrem Cloud-Anbieter zusätzliche Kosten für den Datenverkehr an.



[[how-restoring-workloads-works]]
== So funktioniert die Wiederherstellung von Workloads

Wenn eine Arbeitslast wiederhergestellt wird, tritt Folgendes auf:

* Wenn Sie eine Workload aus einer lokalen Sicherungsdatei wiederherstellen, erstellt NetApp Backup and Recovery mithilfe der Daten aus der Sicherung eine _neue_ Ressource.
* Wenn Sie eine Wiederherstellung aus einem replizierten Workload durchführen, können Sie den Workload auf dem ursprünglichen System oder auf einem lokalen ONTAP System wiederherstellen.


Auf der Wiederherstellungsseite können Sie eine Ressource wiederherstellen, selbst wenn Sie sich nicht mehr an ihren genauen Namen, Speicherort oder das Datum der letzten funktionierenden Sicherung erinnern. Sie können mithilfe von Filtern nach dem Snapshot suchen.



[[restore-hyper-v-workloads]]
== Wiederherstellen von Hyper-V-Workloads

Hyper-V-Workloads können über das Menü „Wiederherstellen“ wiederhergestellt werden. Nach einem Snapshot kann anhand des Namens oder mithilfe von Filtern gesucht werden.

*Erforderliche NetApp Console-Rolle* Backup und Recovery Super-Admin- oder Backup und Recovery Restore-Admin-Rolle https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Wählen Sie im NetApp Backup and Recovery -Menü *Wiederherstellen* aus.
. Wählen Sie aus der Dropdown-Liste rechts neben dem Namenssuchfeld *Hyper-V* aus.
. Geben Sie den Namen der Ressource ein, die Sie wiederherstellen möchten, oder filtern Sie nach VM-Name, VM-Host oder dem Storage-Pool, in dem sich die Ressource befindet.
+
Es wird eine Liste mit Snapshots angezeigt, die Ihren Suchkriterien entsprechen.

. Wählen Sie die Schaltfläche *Wiederherstellen* für den Snapshot, den Sie wiederherstellen möchten.
+
Es wird eine Liste möglicher Wiederherstellungspunkte angezeigt.

. Wählen Sie den Wiederherstellungspunkt aus, den Sie verwenden möchten.
. Wählen Sie einen Quellspeicherort für den Snapshot aus.
. Wählen Sie *Weiter*, um fortzufahren.
. Wählen Sie das Wiederherstellungsziel und die Einstellungen aus:
+
[discrete]
===== Zielauswahl

+
[role="tabbed-block"]
====
.Am ursprünglichen Speicherort wiederherstellen
--
.. Wählen Sie den Bereich *Ursprünglicher Speicherort* aus. Wenn Sie zum ursprünglichen Speicherort wiederherstellen, können Sie die Zieleinstellungen anzeigen, indem Sie den Abschnitt *Zieleinstellungen* erweitern, aber Sie können sie nicht ändern.
.. Im Abschnitt *Optionen nach der Wiederherstellung* sollten Sie folgende Option in Betracht ziehen:
+
*** *Starten der virtuellen Maschine*: Aktivieren Sie diese Option, um die neue virtuelle Maschine nach der Wiederherstellung zu starten.




--
.An einem anderen Speicherort wiederherstellen
--
.. Wählen Sie den Bereich *Alternativer Standort* aus.
.. Im Abschnitt *Zieleinstellungen* sind die folgenden Informationen einzugeben:
+
*** *Hyper-V FQDN oder IP-Adresse*: Geben Sie den vollqualifizierten Domänennamen oder die IP-Adresse des Ziel-Hyper-V-Hosts ein.
*** *Netzwerk*: Wählen Sie das Zielnetzwerk aus, in dem Sie den Snapshot wiederherstellen möchten.
*** *Name der virtuellen Maschine*: Geben Sie den Namen der VM ein, die Sie wiederherstellen möchten.
*** *Zielort*: Geben Sie den Zielordner oder die CIFS-Freigabe ein, die die wiederhergestellten Daten enthalten soll.


.. Im Abschnitt *Zielspeicher* (nur sichtbar beim Wiederherstellen aus dem Objektspeicher):
+
*** *Standardspeicherort ändern*: Diese Option ermöglicht die Wiederherstellung eines Objektspeicher-Backups an einem anderen Speicherort, falls der Quellspeicherort nicht erreichbar oder voll ist. Ein anderer Cluster, eine andere Storage-VM oder ein anderes Aggregat kann ausgewählt werden.


.. Im Abschnitt *Optionen vor der Wiederherstellung* sind folgende Optionen zu berücksichtigen:
+
*** *Schnellwiederherstellung*: Aktivieren Sie diese Option, um die wiederhergestellte VM sofort verfügbar zu machen. Aus dem Objektspeicher werden nur die zum Ausführen der VM benötigten Dateien wiederhergestellt, nicht das gesamte Volume.


.. Im Abschnitt *Optionen nach der Wiederherstellung* sind folgende Optionen zu berücksichtigen:
+
*** *Starten der virtuellen Maschine*: Aktivieren Sie diese Option, um die neue virtuelle Maschine nach der Wiederherstellung zu starten.




--
====
. Wählen Sie *Wiederherstellen*.

