---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: Durch die Überwachung des Zustands Ihrer Workloads wird sichergestellt, dass Sie über Probleme beim Workload-Schutz informiert sind und Schritte zu deren Lösung unternehmen können.  Zeigen Sie den Status Ihrer Backups und Wiederherstellungen an und reagieren Sie auf alle Warnungen, die im NetApp Backup and Recovery Dashboard angezeigt werden.  Sie können die Schutzzusammenfassung, die Wiederherstellungszusammenfassung, die Systemzusammenfassung und mehr überprüfen. 
---
= Schutzstatus im Backup und Recovery Dashboard anzeigen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der Zustand Ihrer Workloads kann überwacht werden, um Schutzprobleme zu erkennen und auf Warnmeldungen zu reagieren. Der Status von Backups und Wiederherstellungen sowie die System-, Schutz-, Job- und Wiederherstellungsübersichten sind im NetApp Backup und Recovery Dashboard einsehbar.

*Erforderliche NetApp Console-Rolle* Storage Viewer, Backup and Recovery Super Admin, Backup and Recovery Backup Admin, Backup and Recovery Restore Admin, Backup and Recovery Clone Admin oder Backup and Recovery Viewer Role. Für den Schutz von Daten, die auf einem Cloud Volumes ONTAP Cluster gespeichert sind, ist zusätzlich die Cloud Volumes ONTAP Admin-Rolle erforderlich. Informationen zu link:reference-roles.html["Backup und Recovery Rollen und Berechtigungen"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Im NetApp Console-Menü *Schutz* > *Backup und Recovery* auswählen.
. Wählen Sie eine Workload-Kachel aus (z. B. Microsoft SQL Server).
. Wählen Sie im Menü „Sichern und Wiederherstellen“ die Option „Dashboard“ aus.
+
Sie können die folgenden Arten von Informationen überprüfen:

+
** Anzahl der erkannten Hosts oder VMs
** Anzahl der erkannten Kubernetes-Cluster
** Anzahl der Sicherungsziele im Objektspeicher
** Anzahl der vCenter
** Anzahl der Speichercluster in ONTAP






[[view-the-protection-summary]]
== Schutzübersicht anzeigen

Überprüfen Sie die folgenden Informationen in der Schutzzusammenfassung:

* Die Gesamtzahl der geschützten und ungeschützten Datenbanken, VMs und Datenspeicher.
+

TIP: Eine geschützte Datenbank ist eine Datenbank, der eine Sicherungsrichtlinie zugewiesen ist.  Eine ungeschützte Datenbank ist eine Datenbank, der keine Sicherungsrichtlinie zugewiesen ist.

* Die Anzahl der Sicherungen, die erfolgreich waren, eine Warnung aufweisen oder fehlgeschlagen sind.
* Die vom Sicherungsdienst ermittelte Gesamtkapazität und die geschützte bzw. ungeschützte Kapazität.  Bewegen Sie den Mauszeiger über das Symbol „*i*“, um die Details anzuzeigen.




[[view-the-job-summary]]
== Jobzusammenfassung anzeigen

In der Jobübersicht ist die Gesamtzahl der abgeschlossenen, laufenden und fehlgeschlagenen Jobs ersichtlich.

.Schritte
. Für jede Jobverteilung kann der Filter geändert werden, sodass die Zusammenfassung der fehlgeschlagenen, laufenden und abgeschlossenen Jobs basierend auf der Anzahl der Tage angezeigt wird, zum Beispiel die letzten 30 Tage, die letzten 7 Tage, die letzten 24 Stunden oder das letzte Jahr.
. Details zu fehlgeschlagenen, laufenden und abgeschlossenen Aufträgen sind über die Option *Auftragsüberwachung anzeigen* einsehbar.




[[view-the-restore-summary]]
== Wiederherstellungszusammenfassung anzeigen

In der Wiederherstellungszusammenfassung finden sich die folgenden Informationen:

* Die Gesamtzahl der durchgeführten Wiederherstellungsaufträge
* Die Gesamtmenge der wiederhergestellten Kapazität
* Die Anzahl der Wiederherstellungsaufträge, die auf lokalem, sekundärem und Objektspeicher ausgeführt wurden.  Bewegen Sie den Mauszeiger über das Diagramm, um die Details anzuzeigen.

