---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre Oracle-Datenbank-Workloads mit NetApp Backup und Recovery. 
---
= Wiederherstellung von Oracle-Datenbank-Workloads mit NetApp Backup und Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle Database-Workloads lassen sich aus Snapshots, replizierten Backups auf Sekundärspeicher oder in Objektspeicher gespeicherten Backups mit NetApp Backup and Recovery wiederherstellen.

.Von diesen Speicherorten wiederherstellen
Sie können Datenbanken von verschiedenen Startorten wiederherstellen:

* Wiederherstellung von einem primären Standort (lokaler Snapshot)
* Wiederherstellen von einer replizierten Ressource auf einem sekundären Speicher
* Wiederherstellung aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten am ursprünglichen Speicherort wiederherstellen. Die Wiederherstellung an einem anderen Speicherort ist in dieser privaten Vorschauversion nicht verfügbar.

* Am ursprünglichen Speicherort wiederherstellen




[[how-oracle-database-restore-works]]
== Wie die Wiederherstellung einer Oracle Database funktioniert

Beim Wiederherstellen von Oracle Database Workloads geschieht Folgendes:

* Wenn Sie eine Datenbank aus einem lokalen Snapshot wiederherstellen, erstellt NetApp Backup and Recovery eine _neue_ Ressource mithilfe der Daten aus dem Backup.
* Wenn Sie aus einem replizierten Speicher wiederherstellen, können Sie es am ursprünglichen Speicherort wiederherstellen.
* Wenn Sie ein Backup aus dem Objektspeicher wiederherstellen, können Sie die Daten im Quellspeicher oder auf einem lokalen ONTAP -System wiederherstellen und die Datenbank von dort wiederherstellen.


Auf der Seite „Wiederherstellen“ (auch als „Suchen und Wiederherstellen“ bezeichnet) können Sie eine Datenbank wiederherstellen, auch wenn Sie sich nicht an den genauen Namen, den Speicherort oder das Datum erinnern, an dem sie zuletzt in gutem Zustand war.  Sie können mithilfe von Filtern nach der Datenbank suchen.



[[restore-an-oracle-database]]
== Wiederherstellen einer Oracle-Datenbank

Je nach Bedarf lässt sich eine Oracle Datenbank auf einen bestimmten Zeitpunkt, eine bestimmte Systemänderungsnummer (SCN) oder den letzten funktionierenden Zustand wiederherstellen. Die Datenbank kann auch aus Snapshots wiederhergestellt werden, wobei der automatisierte Wiederherstellungsprozess übersprungen werden kann, zum Beispiel wenn die Wiederherstellung manuell erfolgen soll. Die Datenbank lässt sich anhand ihres Namens oder mit spezifischen Filtern suchen.

*Erforderliche NetApp Console-Rolle* Backup und Recovery Super-Admin- oder Backup und Recovery Restore-Admin-Rolle https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Wählen Sie im NetApp Console *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie im NetApp Backup and Recovery -Menü *Wiederherstellen* aus.
. Wählen Sie aus der Dropdown-Liste rechts neben dem Namenssuchfeld *Oracle* aus.
. Geben Sie den Namen der Datenbank ein, die Sie wiederherstellen möchten, oder filtern Sie nach dem Datenbankhost, auf dem sich die wiederherzustellende Datenbank befindet.
+
Es wird eine Liste mit Snapshots angezeigt, die Ihren Suchkriterien entsprechen.

. Wählen Sie die Schaltfläche *Wiederherstellen* für die Datenbank, die Sie wiederherstellen möchten.
. Wählen Sie eine Wiederherstellungsoption:
+
[role="tabbed-block"]
====
.Wiederherstellung zu einem bestimmten Zeitpunkt
--
.. Wählen Sie *Zu einem bestimmten Zeitpunkt wiederherstellen*.
.. Wählen Sie *Weiter*.
.. Wählen Sie ein Datum aus der Dropdown-Liste und wählen Sie *Suchen*.
+
Es wird eine Liste mit passenden Schnappschüssen zum angegebenen Datum angezeigt.



--
.Wiederherstellen auf eine bestimmte Systemänderungsnummer (SCN)
--
.. Wählen Sie *Auf eine bestimmte Systemänderungsnummer (SCN) wiederherstellen*.
.. Wählen Sie *Weiter*.
.. Geben Sie die SCN ein, die als Wiederherstellungspunkt verwendet werden soll, und wählen Sie *Suchen*.
+
Es wird eine Liste mit passenden Snapshots für die angegebene SCN angezeigt.



--
.Wiederherstellen auf die letzte Sicherung (letzter guter Zustand)
--
.. Wählen Sie *Auf die neueste Sicherung wiederherstellen*.
.. Wählen Sie *Weiter*.
+
Es werden die neuesten Voll- und Protokollsicherungen angezeigt.



--
.Wiederherstellen aus Snapshots ohne Wiederherstellung
--
.. Wählen Sie *Aus Snapshots ohne Wiederherstellung wiederherstellen*.
.. Wählen Sie *Weiter*.
+
Die passenden Schnappschüsse werden angezeigt.



--
====
. Wählen Sie einen Quellspeicherort für den Snapshot aus.
. Wählen Sie *Weiter*, um fortzufahren.
. Wählen Sie das Wiederherstellungsziel und die Einstellungen aus:


[discrete]
===== Zielauswahl

[role="tabbed-block"]
====
.Am ursprünglichen Speicherort wiederherstellen
--
. *Zieleinstellungen*:
+
** Wählen Sie, ob die gesamte Datenbank oder nur die Tablespaces für die Datenbank wiederhergestellt werden sollen.
** *Steuerdateien*: Aktivieren Sie diese Option optional, um auch die Datenbank-Steuerdateien wiederherzustellen.


. *Optionen vor der Wiederherstellung*:
+
** Aktivieren Sie diese Option optional und geben Sie den vollständigen Pfad für ein Skript ein, das vor dem Wiederherstellungsvorgang ausgeführt werden soll, sowie alle Argumente, die das Skript verwendet.
** Wählen Sie einen Zeitüberschreitungswert für das Skript. Wenn das Skript innerhalb dieses Zeitraums nicht ausgeführt werden kann, wird die Wiederherstellung dennoch fortgesetzt.


. *Optionen nach der Wiederherstellung*:
+
** *Postscript*: Aktivieren Sie diese Option optional und geben Sie den vollständigen Pfad für ein Skript ein, das nach dem Wiederherstellungsvorgang ausgeführt werden soll, sowie alle Argumente, die das Skript verwendet.
** *Öffnen der Datenbank oder Container-Datenbank nach der Wiederherstellung im READ-WRITE-Modus*: Nach Abschluss des Wiederherstellungsvorgangs wird von Backup and Recovery der READ-WRITE-Modus für die Datenbank aktiviert.


. Abschnitt *Benachrichtigung*:
+
** *E-Mail-Benachrichtigungen aktivieren*: Wählen Sie diese Option aus, um E-Mail-Benachrichtigungen über den Wiederherstellungsvorgang zu erhalten, und geben Sie an, welche Art von Benachrichtigungen Sie erhalten möchten.


. Wählen Sie *Wiederherstellen*.


--
.An einem anderen Speicherort wiederherstellen
--
In dieser Vorabversion nicht für Oracle Database Workloads verfügbar.

--
====