---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: Mit NetApp Backup and Recovery können Sie den Schutz Ihrer Kubernetes-Anwendungen und der zugehörigen Ressourcen aufheben und diese löschen. 
---
= Verwalten von Kubernetes-Anwendungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit NetApp Backup and Recovery können Sie den Schutz Ihrer Kubernetes-Anwendungen und der zugehörigen Ressourcen aufheben und diese löschen.

.Erforderliche NetApp Console
Organisationsadministrator oder SnapCenter Administrator. link:reference-roles.html["Erfahren Sie mehr über die Zugriffsrollen für NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .



== Aufheben des Schutzes einer Kubernetes-Anwendung

Sie können den Schutz einer Anwendung aufheben, wenn Sie sie nicht mehr schützen möchten. Wenn Sie den Schutz einer Anwendung aufheben, beendet NetApp Backup and Recovery den Schutz der Anwendung, behält jedoch alle zugehörigen Backups und Snapshots bei.

.Schritte
. Wählen Sie in NetApp Backup and Recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz und wählen Sie *Anzeigen*, um die mit dieser Instanz verknüpften Ressourcen anzuzeigen.
. Wählen Sie die Registerkarte *Anwendungen*.
. Wählen Sie in der Anwendungsliste eine Anwendung aus, deren Schutz Sie aufheben möchten, und wählen Sie das zugehörige Aktionsmenü.
. Wählen Sie *Schutz aufheben*.
. Lesen Sie den Hinweis und wählen Sie anschließend „Schutz aufheben“ aus.




== Löschen einer Kubernetes-Anwendung

Löschen Sie eine Anwendung, die Sie nicht mehr benötigen.  NetApp Backup and Recovery beendet den Schutz und entfernt alle Backups und Snapshots für gelöschte Anwendungen.

.Schritte
. Wählen Sie in NetApp Backup and Recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz und wählen Sie *Anzeigen*, um die mit dieser Instanz verknüpften Ressourcen anzuzeigen.
. Wählen Sie die Registerkarte *Anwendungen*.
. Wählen Sie in der Anwendungsliste eine Anwendung aus, die Sie löschen möchten, und wählen Sie das zugehörige Aktionsmenü.
. Wählen Sie *Löschen*.
. Aktivieren Sie *Snapshots und Backups löschen*, um alle Snapshots und Backups der Anwendung zu entfernen.
+

CAUTION: Sie können die Anwendung mithilfe dieser Snapshots und Backups nicht mehr wiederherstellen.

. Bestätigen Sie die Aktion und wählen Sie *Löschen*.

