---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Sie können virtuelle Oracle-Maschinen von lokalen ONTAP -Systemen bis hin zu Amazon Web Services, Microsoft Azure, Google Cloud Platform und StorageGRID schützen und so sicherstellen, dass Ihre Daten geschützt sind. 
---
= Oracle Datenbank-Workloads mit NetApp Backup und Recovery schützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup und Recovery schützt Oracle Database Workloads und Protokolle mit schnellen, platzsparenden, absturzkonsistenten und datenbankkonsistenten Backups und Wiederherstellungen. Workloads können in AWS S3, StorageGRID, Azure Blob oder ONTAP S3 gesichert und Backups auf einem lokalen Oracle Host wiederhergestellt werden.

Verwenden Sie NetApp Backup and Recovery , um eine 3-2-1-Schutzstrategie zu implementieren, bei der Sie 3 Kopien Ihrer Quelldaten auf 2 verschiedenen Speichersystemen sowie 1 Kopie in der Cloud haben. Zu den Vorteilen des 3-2-1-Ansatzes gehören:

* Mehrere Datenkopien schützen vor internen und externen Cybersicherheitsbedrohungen.
* Die Verwendung unterschiedlicher Medientypen erleichtert Ihnen die Wiederherstellung, wenn ein Typ ausfällt.
* Sie können die Wiederherstellung schnell von der Vor-Ort-Kopie durchführen und die Offsite-Kopien verwenden, wenn die Vor-Ort-Kopie kompromittiert ist.


Sie können NetApp Backup und Recovery verwenden, um die folgenden Aufgaben im Zusammenhang mit Oracle Database-Workloads durchzuführen:

* link:br-start-discover-oracle.html["Oracle Database-Workloads entdecken"]
* link:br-use-oracle-protection-groups.html["Schutzgruppen für Oracle Database Workloads verwalten"]
* link:br-use-oracle-backup.html["Oracle-Datenbank-Workloads sichern"]
* link:br-use-oracle-clone.html["Oracle-Datenbank-Workloads klonen"]
* link:br-use-oracle-restore.html["Oracle-Datenbank-Workloads wiederherstellen"]

