---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: Erstellen Sie in NetApp Backup and Recovery Berichte, um den Status Ihrer Sicherungen anzuzeigen, einschließlich der Anzahl der Sicherungen, der Anzahl der erfolgreichen Sicherungen und der Anzahl der fehlgeschlagenen Sicherungen.  Sie können auch die Details jeder Sicherung anzeigen, einschließlich des Sicherungstyps, des für die Sicherung verwendeten Speichersystems und der Sicherungszeit. 
---
= Erstellen von Microsoft SQL Server-Schutzberichten in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Berichte für Microsoft SQL Server Workloads in NetApp Backup and Recovery ermöglichen eine Überprüfung des Sicherungsstatus und der Details, einschließlich der Anzahl erfolgreicher und fehlgeschlagener Sicherungen, Sicherungstypen, Storage-Systeme und Zeitstempel.



[[create-a-protection-report]]
== Erstellen Sie einen Schutzbericht

*Erforderliche NetApp Console-Rolle* Backup and Recovery Super Admin, Backup and Recovery Backup Admin, Backup and Recovery Restore Admin, Backup and Recovery Clone Admin. Für den Schutz von Daten, die auf einem Cloud Volumes ONTAP Cluster gespeichert sind, ist zusätzlich die Cloud Volumes ONTAP Admin-Rolle erforderlich. Informationen dazu link:reference-roles.html["Rollen und Berechtigungen für Backup und Wiederherstellung"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Im NetApp Backup und Recovery-Menü die Option *Berichte* auswählen.
. Wählen Sie *Bericht erstellen*.
. Geben Sie Details zum Berichtsumfang ein:
+
** *Berichtsname*: Geben Sie einen eindeutigen Namen für den Bericht ein.
** *Berichtstyp*: Wählen Sie, ob Sie einen Bericht nach Konto oder nach Arbeitslast (Microsoft SQL Server) wünschen.
** *Host auswählen*: Wenn Sie nach Arbeitslast ausgewählt haben, wählen Sie den Host aus, für den Sie den Bericht erstellen möchten.
** *Inhalt auswählen*: Wählen Sie, ob der Bericht eine Zusammenfassung aller Sicherungen oder Details zu jeder Sicherung enthalten soll.  (Wenn Sie „Nach Konto“ gewählt haben)


. Geben Sie den Berichtszeitraum ein: Es kann ausgewählt werden, ob der Bericht Daten vom letzten Tag, den letzten 7 Tagen, den letzten 30 Tagen, dem letzten Quartal oder dem letzten Jahr enthalten soll.
. Geben Sie die Details zur Berichtszustellung ein: Wenn der Bericht per E-Mail zugestellt werden soll, *Bericht per E-Mail senden* auswählen. Die E-Mail-Adresse eingeben, an die der Bericht gesendet werden soll.
+
E-Mail-Benachrichtigungen können auf der Einstellungsseite konfiguriert werden. Weitere Informationen zur Konfiguration von E-Mail-Benachrichtigungen sind unter link:br-start-configure.html["Konfigurieren der Einstellungen"] zu finden.


