---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: 'Sie können Dateien oder Ordner von einer virtuellen Maschinenfestplatte (VMDK) auf einem Windows-Gastbetriebssystem wiederherstellen.' 
---
= Anforderungen an die Wiederherstellung von VMware-Gastdateien in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit der Gastdateiwiederherstellung lassen sich Dateien oder Ordner von einer virtuellen Maschinenfestplatte (VMDK) auf einem Windows- oder Linux-Gastbetriebssystem wiederherstellen.



[[guest-file-restore-workflow]]
== Workflow zur Wiederherstellung von Gastdateien

Die Wiederherstellung der Gastdateien umfasst die folgenden Schritte:

. Befestigen
+
Binden Sie eine virtuelle Festplatte an eine Gast-VM oder eine Proxy-VM an und starten Sie eine Gast-VM-Dateiwiederherstellungssitzung.

. Warten
+
Warten Sie, bis der Anfügevorgang abgeschlossen ist, bevor Sie durchsuchen und wiederherstellen können. Nach Abschluss des Anfügevorgangs wird automatisch eine Gastdatei-Wiederherstellungssitzung erstellt.

. Dateien oder Ordner auswählen
+
Durchsuchen Sie die virtuellen Festplattendateien und wählen Sie eine oder mehrere Dateien oder Ordner zur Wiederherstellung aus.

. Wiederherstellen
+
Stellen Sie die ausgewählten Dateien oder Ordner an einem angegebenen Speicherort wieder her.





[[prerequisites-for-restoring-guest-files-and-folders]]
== Voraussetzungen für die Wiederherstellung von Gastdateien und -ordnern

Prüfen Sie alle Voraussetzungen, bevor Sie Dateien oder Ordner aus einer VMDK wiederherstellen.

* VMware Tools muss installiert sein und ausgeführt werden.
+
NetApp Backup and Recovery verwendet Informationen von VMware Tools, um eine Verbindung zum VMware-Gastbetriebssystem herzustellen.

* Sie müssen den Sicherungs-Snapshot und das VMDK kennen, von dem die Wiederherstellung durchgeführt werden soll.
* Die virtuelle Festplatte, die Sie einbinden, muss sich in einer NetApp Backup and Recovery Sicherung befinden.
+
Die virtuelle Festplatte, die die wiederherzustellende Datei oder den Ordner enthält, muss sich in einer VM-Sicherung befinden, die mit NetApp Backup and Recovery erstellt wurde.

* Um eine Proxy-VM zu verwenden, muss die Proxy-VM konfiguriert werden.
+
Wenn Sie eine virtuelle Festplatte an eine Proxy-VM anhängen möchten, muss die Proxy-VM konfiguriert werden, bevor der Anhänge- und Wiederherstellungsvorgang beginnt.

* Für Dateien mit nicht-englischen Zeichen im Namen ist eine Wiederherstellung in einem Verzeichnis erforderlich, nicht als einzelne Datei.
+
Dateien mit nicht-englischen Zeichen, wie japanischen Kanji, lassen sich wiederherstellen, indem das Verzeichnis wiederhergestellt wird, in dem sich die Dateien befinden.



Für die aktuellsten Informationen zur Unterstützung von Gastbetriebssystemen konsultieren Sie bitte die  https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool (IMT)"^].



[[windows-guests]]
=== Windows-Gäste

* Als Gastbetriebssystem muss Windows Server 2008 R2 oder höher ausgeführt werden.
+
Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool (IMT)"^] .

* Die Anmeldeinformationen für die Ziel-VM verwenden das integrierte Domänen- oder lokale Administratorkonto mit dem Benutzernamen „Administrator“. Bevor Sie mit dem Wiederherstellungsvorgang beginnen, konfigurieren Sie die Anmeldeinformationen für die VM, an die Sie die virtuelle Festplatte anhängen möchten. Für den Anfüge- und Wiederherstellungsvorgang werden Anmeldeinformationen benötigt. Benutzer von Arbeitsgruppen können das integrierte lokale Administratorkonto verwenden.
+

IMPORTANT: Wenn Sie ein Konto verwenden müssen, das nicht das integrierte Administratorkonto ist, aber über Administratorrechte innerhalb der VM verfügt, müssen Sie die Benutzerkontensteuerung auf der Gast-VM deaktivieren.





[[linux-guests]]
=== Linux-Gastsysteme

* Folgende Gastbetriebssystemdistributionen werden unterstützt:
+
** Red Hat Enterprise Linux
** Ubuntu
** Debian


* Das Benutzerkonto „Ausführen als“ benötigt Root- oder Sudo-Berechtigungen.
* Für eine VM-übergreifende Wiederherstellung (Wiederherstellung auf einer anderen Linux-VM) muss SSH auf der Ziel-VM ausgeführt werden.




[[guest-file-restore-limitations]]
== Einschränkungen bei der Wiederherstellung von Gastdateien

Vor der Wiederherstellung einer Datei oder eines Ordners aus einem Gastbetriebssystem gelten diese Einschränkungen.

* Sie können dynamische Datenträgertypen nicht innerhalb eines Gastbetriebssystems wiederherstellen.
* Wenn Sie eine verschlüsselte Datei oder einen verschlüsselten Ordner wiederherstellen, bleibt das Verschlüsselungsattribut nicht erhalten.
* Sie können keine Dateien oder Ordner in einem verschlüsselten Ordner wiederherstellen.
* Versteckte Dateien und Ordner werden auf der Dateiauswahlseite angezeigt und können nicht gefiltert werden.
* Dateien oder Ordner können nicht zwischen Gastsystemen mit unterschiedlichen Betriebssystemen wiederhergestellt werden (bei der Wiederherstellung auf eine andere Gast-VM muss der Zielbetriebssystemtyp mit dem Quellbetriebssystemtyp übereinstimmen).
* Eine Wiederherstellung von einem NTFS-Dateisystem auf ein FAT-Dateisystem ist nicht möglich.
+
Wenn Sie versuchen, vom NTFS-Format ins FAT-Format wiederherzustellen, wird der NTFS-Sicherheitsdeskriptor nicht kopiert, da das FAT-Dateisystem keine Windows-Sicherheitsattribute unterstützt.

* Sie können keine Gastdateien aus einem geklonten VMDK oder einem nicht initialisierten VMDK wiederherstellen.
* Sie können die Verzeichnisstruktur einer Datei nicht wiederherstellen.
+
Wenn Sie eine Datei aus einem verschachtelten Verzeichnis wiederherstellen, stellt das System nur die Datei selbst wieder her, nicht aber die Verzeichnisstruktur. Um die gesamte Verzeichnisstruktur wiederherzustellen, kopieren Sie das oberste Verzeichnis.

* Sie können keine Gastdateien von einer vVol-VM auf einem alternativen Host wiederherstellen.
* Sie können verschlüsselte Gastdateien nicht wiederherstellen.

