---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: 'Sie können Dateien oder Ordner von einer virtuellen Maschinenfestplatte (VMDK) auf einem Windows-Gastbetriebssystem wiederherstellen.' 
---
= Anforderungen und Einschränkungen beim Wiederherstellen von Gastdateien und -ordnern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können Dateien oder Ordner von einer virtuellen Maschinenfestplatte (VMDK) auf einem Windows- oder Linux-Gast-OS wiederherstellen.



== Workflow zur Gastwiederherstellung

Die Wiederherstellungsvorgänge des Gastbetriebssystems umfassen die folgenden Schritte:

. Befestigen
+
Binden Sie eine virtuelle Festplatte an eine Gast-VM an und starten Sie eine Gastdatei-Wiederherstellungssitzung.

. Warten
+
Warten Sie, bis der Anfügevorgang abgeschlossen ist, bevor Sie durchsuchen und wiederherstellen können. Nach Abschluss des Anfügevorgangs wird automatisch eine Gastdatei-Wiederherstellungssitzung erstellt.

. Dateien oder Ordner auswählen
+
Durchsuchen Sie die VMDK-Dateien und wählen Sie eine oder mehrere Dateien oder Ordner zur Wiederherstellung aus.

. Wiederherstellen
+
Stellen Sie die ausgewählten Dateien oder Ordner an einem angegebenen Speicherort wieder her.





== Voraussetzungen für die Wiederherstellung von Gastdateien und -ordnern

Prüfen Sie alle Voraussetzungen, bevor Sie Dateien oder Ordner aus einer VMDK wiederherstellen.

* VMware-Tools müssen installiert und ausgeführt werden.
+
NetApp Backup and Recovery nutzt Informationen von VMware Tools, um eine Verbindung zum VMware-Gastbetriebssystem herzustellen.

* Sie müssen den Sicherungs-Snapshot und das VMDK kennen, von dem die Wiederherstellung durchgeführt werden soll.
* Die anzuhängende virtuelle Festplatte muss sich in einem NetApp Backup and Recovery -Backup befinden.
+
Die virtuelle Festplatte, die die wiederherzustellende Datei oder den Ordner enthält, muss sich in einer VM-Sicherung befinden, die mit NetApp Backup and Recovery erstellt wurde.



* Dateien mit Namen, die nicht aus dem englischen Alphabet stammen, müssen Sie in einem Verzeichnis und nicht als einzelne Datei wiederherstellen.
+
Sie können Dateien mit nicht-alphabetischen Namen, wie etwa japanische Kanji, wiederherstellen, indem Sie das Verzeichnis wiederherstellen, in dem sich die Dateien befinden.



Für die aktuellsten Informationen zur Unterstützung von Gastbetriebssystemen konsultieren Sie bitte die  https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool (IMT)"^].



=== Windows-Gäste

* Als Gastbetriebssystem muss Windows Server 2008 R2 oder höher ausgeführt werden.
+
Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool (IMT)"^] .

* Die Anmeldeinformationen für die Ziel-VM verwenden das integrierte Domänen- oder lokale Administratorkonto mit dem Benutzernamen „Administrator“. Bevor Sie mit dem Wiederherstellungsvorgang beginnen, konfigurieren Sie die Anmeldeinformationen für die VM, an die Sie die virtuelle Festplatte anhängen möchten. Für den Anfüge- und Wiederherstellungsvorgang werden Anmeldeinformationen benötigt. Benutzer von Arbeitsgruppen können das integrierte lokale Administratorkonto verwenden.
+

IMPORTANT: Wenn Sie ein Konto verwenden müssen, das nicht das integrierte Administratorkonto ist, aber über Administratorrechte innerhalb der VM verfügt, müssen Sie die Benutzerkontensteuerung auf der Gast-VM deaktivieren.





=== Linux-Gastsysteme

* Folgende Gastbetriebssystemdistributionen werden unterstützt:
+
** Red Hat Enterprise Linux
** Ubuntu
** Debian


* Das Benutzerkonto „Ausführen als“ benötigt Root- oder Sudo-Berechtigungen.
* Für eine VM-übergreifende Wiederherstellung (Wiederherstellung auf einer anderen Linux-VM) muss SSH auf der Ziel-VM ausgeführt werden.




== Einschränkungen bei der Wiederherstellung von Gastdateien

Bevor Sie eine Datei oder einen Ordner aus einem Gastbetriebssystem wiederherstellen, sollten Sie sich über die Funktionsbeschränkungen im Klaren sein.

* Sie können dynamische Datenträgertypen nicht innerhalb eines Gastbetriebssystems wiederherstellen.
* Wenn Sie eine verschlüsselte Datei oder einen verschlüsselten Ordner wiederherstellen, bleibt das Verschlüsselungsattribut nicht erhalten.
* Sie können keine Dateien oder Ordner in einem verschlüsselten Ordner wiederherstellen.
* Versteckte Dateien und Ordner werden auf der Dateiauswahlseite angezeigt und können nicht gefiltert werden.
* Dateien oder Ordner können nicht zwischen Gastsystemen mit unterschiedlichen Betriebssystemen wiederhergestellt werden (bei der Wiederherstellung auf eine andere Gast-VM muss der Zielbetriebssystemtyp mit dem Quellbetriebssystemtyp übereinstimmen).
* Sie können keine Wiederherstellung von einem NTFS-Dateisystem auf ein FAT-Dateisystem durchführen.
+
Wenn Sie versuchen, vom NTFS-Format ins FAT-Format wiederherzustellen, wird der NTFS-Sicherheitsdeskriptor nicht kopiert, da das FAT-Dateisystem keine Windows-Sicherheitsattribute unterstützt.

* Sie können keine Gastdateien aus einem geklonten VMDK oder einem nicht initialisierten VMDK wiederherstellen.
* Sie können die Verzeichnisstruktur einer Datei nicht wiederherstellen.
+
Wenn Sie eine Datei aus einem verschachtelten Verzeichnis wiederherstellen, stellt das System nur die Datei selbst wieder her, nicht aber die Verzeichnisstruktur. Um die gesamte Verzeichnisstruktur wiederherzustellen, kopieren Sie das oberste Verzeichnis.

* Sie können keine Gastdateien von einer vVol-VM auf einem alternativen Host wiederherstellen.
* Sie können verschlüsselte Gastdateien nicht wiederherstellen.

