---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-clusters.html 
keywords: discover, backup and recovery, snapcenter, kubernetes, k8s, clusters, applications, inventory 
summary: Mit NetApp Backup and Recovery können Sie Ihre Kubernetes-Cluster erkennen und verwalten, sodass Sie die von den Clustern gehosteten Ressourcen schützen können. 
---
= Verwalten von Kubernetes-Clustern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit NetApp Backup and Recovery können Sie Ihre Kubernetes-Cluster erkennen und verwalten, sodass Sie die von den Clustern gehosteten Ressourcen schützen können.

.Erforderliche NetApp Console
Organisationsadministrator oder SnapCenter Administrator. link:reference-roles.html["Erfahren Sie mehr über die Zugriffsrollen für NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .


NOTE: Informationen zum Erkennen von Kubernetes-Clustern finden Sie unterlink:br-start-discover.html["Entdecken Sie Kubernetes-Workloads"] .



== Kubernetes-Clusterinformationen bearbeiten

Sie können einen Cluster bearbeiten, wenn Sie seinen Namen ändern müssen.

.Schritte
. Wählen Sie in NetApp Backup and Recovery*Inventar* > *Cluster*.
. Wählen Sie in der Liste der Cluster einen Cluster aus, den Sie bearbeiten möchten, und wählen Sie das zugehörige Aktionsmenü aus.
. Wählen Sie *Cluster bearbeiten*.
. Nehmen Sie alle erforderlichen Änderungen am Clusternamen vor. Der Clustername muss mit dem Namen übereinstimmen, den Sie während des Erkennungsprozesses mit dem Helm-Befehl verwendet haben.
. Wählen Sie *Fertig*.




== Entfernen eines Kubernetes-Clusters

Um den Schutz eines Kubernetes-Clusters zu beenden, deaktivieren Sie den Schutz und löschen Sie die zugehörigen Anwendungen. Entfernen Sie anschließend den Cluster aus NetApp Backup and Recovery.  NetApp Backup and Recovery löscht weder den Cluster noch seine Ressourcen, sondern entfernt den Cluster lediglich aus dem Inventar der NetApp Console .

.Schritte
. Wählen Sie in NetApp Backup and Recovery*Inventar* > *Cluster*.
. Wählen Sie in der Liste der Cluster einen Cluster aus, den Sie bearbeiten möchten, und wählen Sie das zugehörige Aktionsmenü aus.
. Wählen Sie *Cluster entfernen*.
. Überprüfen Sie die Informationen im Bestätigungsdialogfeld und wählen Sie *Entfernen*.

