---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp Backup and Recovery. 
---
= VMware-Workloads mit NetApp Backup and Recovery schützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery kann zum Schutz von VMware-VMs und Datenspeichern eingesetzt werden. Schnelle, platzsparende, absturzkonsistente und VM-konsistente Backups können erstellt, auf unterstützten Backup-Zielen gespeichert und VMware-Workloads auf einem lokalen VMware-Host wiederhergestellt werden.


NOTE: Diese Version von NetApp Backup and Recovery unterstützt nur VMware vCenter und erkennt keine vVols oder VMs auf vVols.

Mit NetApp Backup and Recovery lässt sich eine 3-2-1-Strategie umsetzen, bei der drei Kopien Ihrer Quelldaten auf zwei verschiedenen Storage-Systemen und eine Kopie in der Cloud gespeichert werden. Zu den Vorteilen des 3-2-1-Ansatzes zählen:

* Mehrere Datenkopien schützen vor internen und externen Cybersicherheitsbedrohungen.
* Die Verwendung unterschiedlicher Medientypen erleichtert Ihnen die Wiederherstellung, wenn ein Typ ausfällt.
* Eine schnelle Wiederherstellung von der vor Ort Kopie ist möglich, und die externen Kopien können genutzt werden, falls die vor Ort Kopie kompromittiert ist.


Mit NetApp Backup and Recovery können Sie die folgenden Aufgaben im Zusammenhang mit VMware-Workloads ausführen:

* link:br-use-vmware-discovery.html["Entdecken Sie VMware-Workloads"]
* link:br-use-vmware-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für VMware-Workloads"]
* link:br-use-vmware-backup.html["Sichern Sie VMware-Workloads"]
* link:br-use-vmware-restore.html["Wiederherstellen von VMware-Workloads"]

