---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Schützen Sie Ihre Microsoft SQL Server-Anwendungsdaten von lokalen ONTAP -Systemen auf Amazon Web Services, Microsoft Azure oder StorageGRID mit NetApp Backup and Recovery. 
---
= Schützen Sie Microsoft SQL-Workloads mit NetApp Backup and Recovery – Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sichern Sie Ihre Microsoft SQL Server-Anwendungsdaten von lokalen ONTAP -Systemen auf AWS, Azure oder StorageGRID mit NetApp Backup and Recovery.  Das System erstellt und speichert automatisch Backups in Ihrem Cloud-Konto und befolgt dabei Ihre Richtlinien.  Verwenden Sie eine 3-2-1-Strategie: Bewahren Sie drei Kopien Ihrer Daten auf zwei Speichersystemen und eine Kopie in der Cloud auf.

Zu den Vorteilen des 3-2-1-Ansatzes gehören:

* Mehrere Datenkopien schützen vor internen und externen Cybersicherheitsbedrohungen.
* Die Verwendung unterschiedlicher Medientypen erleichtert Ihnen die Wiederherstellung, wenn ein Typ ausfällt.
* Sie können die Wiederherstellung schnell von der Vor-Ort-Kopie durchführen und die Offsite-Kopien verwenden, wenn die Vor-Ort-Kopie kompromittiert ist.


NetApp Backup and Recovery verwendet NetApp SnapMirror , um Backups zu synchronisieren, indem Snapshots erstellt und an die Backup-Speicherorte übertragen werden.

Zum Schutz Ihrer Daten können Sie Folgendes tun:

* link:concept-start-prereq-snapcenter-import.html["Konfigurieren Sie zusätzliche Elemente beim Importieren aus SnapCenter"]
* link:br-start-discover.html["Entdecken Sie Microsoft SQL Server-Workloads und importieren Sie optional SnapCenter -Ressourcen"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads mit lokalen Snapshots auf dem lokalen ONTAP Primärspeicher"]
* link:br-use-mssql-backup.html["Replizieren Sie Workloads auf den sekundären ONTAP -Speicher"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads an einem Objektspeicherort"]
* link:br-use-mssql-backup.html["Sichern Sie Workloads jetzt"]
* link:br-use-mssql-restore.html["Wiederherstellen von Workloads"]
* link:br-use-mssql-clone.html["Klonen von Workloads"]
* link:br-use-manage-inventory.html["Verwalten des Workload-Inventars"]
* link:br-use-manage-snapshots.html["Verwalten von Snapshots"]


Zum Sichern von Workloads erstellen Sie Richtlinien, die Sicherungs- und Wiederherstellungsvorgänge verwalten. Sehenlink:br-use-policies-create.html["Erstellen von Richtlinien"] für weitere Informationen.

.Unterstützte Sicherungsziele
NetApp Backup and Recovery ermöglicht die Sicherung von Microsoft SQL Server-Instanzen und -Datenbanken von den folgenden Quellsystemen auf die folgenden Sekundärsysteme und Objektspeicher bei öffentlichen und privaten Cloud-Anbietern. Die Snapshots werden auf dem Quellsystem gespeichert.

[cols="33,33,33"]
|===
| Quellsystem | Sekundärsystem (Replikation) | Zielobjektspeicher (Backup) 


| Cloud Volumes ONTAP in AWS | Cloud Volumes ONTAP in AWS On-Premises- ONTAP -System | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP in Azure | Cloud Volumes ONTAP in Azure On-Premises- ONTAP -System | Azure Blob ONTAP S3 


| On-Premises- ONTAP -System | Cloud Volumes ONTAP On-Premises ONTAP -System | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===
.Unterstützte Wiederherstellungsziele
Sie können Microsoft SQL Server-Instanzen und -Datenbanken aus einer Sicherung, die sich im Primärspeicher oder einem Sekundärsystem (einem replizierten Volume) oder im Objektspeicher (einer Sicherungsdatei) befindet, auf den folgenden Systemen wiederherstellen. Snapshots befinden sich auf dem Quellsystem und können nur auf demselben System wiederhergestellt werden.

[cols="33,33,33"]
|===
2+| Vom Speicherort der Sicherungsdatei | Zum Zielsystem 


| *Objektspeicher (Backup)* | *Sekundäres System (Replikation)* |  


| Amazon S3 | Cloud Volumes ONTAP in AWS On-Premises- ONTAP -System | Cloud Volumes im AWS On-Premises ONTAP -System ONTAP S3 


| Azure-Blob | Cloud Volumes ONTAP in Azure On-Premises- ONTAP -System | Cloud Volumes ONTAP in Azure Lokales ONTAP -System ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP On-Premises ONTAP -System | On-Premises ONTAP -System ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===

NOTE: Verweise auf „On-Premises ONTAP -Systeme“ umfassen FAS und AFF Systeme.
