---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre KVM-Workloads mit NetApp Backup and Recovery. 
---
= Wiederherstellen virtueller KVM-Maschinen mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
KVM-VMs können aus primären Snapshots, replizierten sekundären Kopien oder Objektspeicher-Backups wiederhergestellt werden.

.Von diesen Speicherorten wiederherstellen
Virtuelle Maschinen lassen sich von diesen Speicherorten wiederherstellen:

* Wiederherstellung von einem primären Standort (lokaler Snapshot)
* Wiederherstellen von einer replizierten Ressource auf einem sekundären Speicher
* Wiederherstellung aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten bis zu diesen Punkten wiederherstellen:

* Am ursprünglichen Speicherort wiederherstellen
* An einem alternativen Speicherort wiederherstellen


.Überlegungen zur Wiederherstellung aus dem Objektspeicher
Wenn Sie eine Sicherung im Objektspeicher auswählen und für diese Sicherung der Ransomware-Schutz aktiviert ist (sofern Sie DataLock und den Ransomware-Schutz in der Sicherungsrichtlinie aktiviert haben), erfolgt eine Aufforderung, vor der Wiederherstellung der Daten eine zusätzliche Integritätsprüfung durchzuführen. Ein Scan wird empfohlen.


TIP: Für den Zugriff auf den Inhalt der Sicherungsdatei fallen bei Ihrem Cloud-Anbieter zusätzliche Kosten für den Datenverkehr an.



[[how-restoring-virtual-machines-works]]
== So funktioniert die Wiederherstellung virtueller Maschinen

Beim Wiederherstellen virtueller Maschinen gilt Folgendes:

* Wenn Sie eine Workload aus einer lokalen Sicherungsdatei wiederherstellen, erstellt NetApp Backup and Recovery mithilfe der Daten aus der Sicherung eine _neue_ Ressource.
* Wenn Sie eine Wiederherstellung von einer replizierten VM durchführen, können Sie diese auf dem Originalsystem oder auf einem lokalen ONTAP -System wiederherstellen.
* Wenn Sie eine Sicherung aus dem Objektspeicher wiederherstellen, können Sie die Daten auf dem ursprünglichen System oder auf einem lokalen ONTAP -System wiederherstellen.


Auf der Wiederherstellungsseite können Sie eine VM wiederherstellen, selbst wenn Sie sich nicht mehr an ihren genauen Namen, Speicherort oder das Datum des letzten bekannten funktionierenden Zustands erinnern. Sie können mithilfe von Filtern nach dem Snapshot suchen.



[[restore-kvm-virtual-machines]]
== Wiederherstellen von KVM-VMs

KVM-VMs können über das Menü „Wiederherstellen“ wiederhergestellt werden. Snapshots lassen sich nach Name oder mit Filtern suchen.

*Erforderliche NetApp Console-Rolle* Backup und Recovery Super-Admin- oder Backup und Recovery Restore-Admin-Rolle https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^].

.Schritte
. Wählen Sie im NetApp Console *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie im NetApp Backup and Recovery -Menü *Wiederherstellen* aus.
. Wählen Sie aus der Dropdown-Liste rechts neben dem Namenssuchfeld *KVM* aus.
. Den Namen der VM eingeben, die wiederhergestellt werden soll, oder nach dem VM-Host oder dem Speicherpool filtern, in dem sich die VM befindet.
+
Es wird eine Liste mit Snapshots angezeigt, die Ihren Suchkriterien entsprechen.

. Für den Snapshot, den Sie wiederherstellen möchten, *Wiederherstellen* auswählen.
+
Es wird eine Liste möglicher Wiederherstellungspunkte angezeigt.

. Wählen Sie den Wiederherstellungspunkt aus, den Sie verwenden möchten.
. Wählen Sie einen Quellspeicherort für den Snapshot aus.
. Wählen Sie *Weiter*, um fortzufahren.
. Wählen Sie das Wiederherstellungsziel und die Einstellungen aus:
+
[discrete]
===== Zielauswahl

+
[role="tabbed-block"]
====
.Am ursprünglichen Speicherort wiederherstellen
--
.. Wählen Sie den Bereich *Ursprünglicher Speicherort* aus.
.. Aktivieren Sie im Abschnitt *Optionen nach der Wiederherstellung* die Option *Virtuelle Maschine neu starten*, um die VM nach Abschluss des Wiederherstellungsvorgangs neu zu starten.


--
.An einem anderen Speicherort wiederherstellen
--
.. Wählen Sie den Bereich *Alternativer Standort* aus.
.. Im Abschnitt *CloudStack settings* sind folgende Informationen anzugeben:
+
*** *Zone*: Wählen Sie eine Zielzone CloudStack aus der Liste.
*** *Pod*: Wählen Sie aus der Liste einen Ziel-Pod innerhalb der ausgewählten Zone aus.
*** *Cluster*: Wählen Sie einen Ziel-Cluster innerhalb des ausgewählten Pods aus der Liste aus.
*** *Host*: Wählen Sie aus der Liste einen Zielhost im Cluster aus.
*** *Speicherpool*: Wählen Sie einen Zielspeicherpool aus der Liste (das Zielvolume sollte sich hier befinden).
*** *Netzwerk*: Wählen Sie das Netzwerk aus, mit dem die wiederhergestellte VM verbunden wird.
*** *VM-Name*: Geben Sie einen Namen für die wiederherzustellende VM ein.
*** *Anzeigename*: Geben Sie den Namen ein, der für diese VM in Backup and Recovery angezeigt werden soll.
*** *Speicherpoolpfad*: Geben Sie den Speicherpoolpfad ein, in dem die VM-Volumes gespeichert werden sollen.


.. Wählen Sie aus der Liste *Serviceangebot auswählen* das Serviceangebot aus, das Ihrem bevorzugten Ressourceneinsatz entspricht.
.. Aktivieren Sie die Option *Erzwungen*, um die wiederhergestellte VM auch dann zu importieren, wenn eine oder mehrere MAC-Adressen der Netzwerkkarte der VM bereits vorhanden sind. Existiert eine MAC-Adresse bereits, wird für diese Netzwerkkarte eine neue MAC-Adresse generiert.
.. Im Abschnitt *Optionen nach der Wiederherstellung* sind folgende Optionen zu berücksichtigen:
+
*** *Virtuelle Maschine neu starten*: Aktivieren Sie diese Option, um die neue virtuelle Maschine nach der Wiederherstellung zu starten.




--
====
. Wählen Sie *Wiederherstellen*.

