---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre Oracle-Workloads mit NetApp Backup and Recovery. 
---
= Stellen Sie Oracle-Datenbanken mit NetApp Backup and Recovery wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Stellen Sie Oracle-Datenbanken aus Snapshots, aus einem auf Sekundärspeicher replizierten Backup oder aus in Objektspeichern gespeicherten Backups mithilfe von NetApp Backup and Recovery wieder her.

.Von diesen Speicherorten wiederherstellen
Sie können Datenbanken von verschiedenen Startorten wiederherstellen:

* Wiederherstellung von einem primären Standort (lokaler Snapshot)
* Wiederherstellen von einer replizierten Ressource auf einem sekundären Speicher
* Wiederherstellung aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten am ursprünglichen Speicherort wiederherstellen. Die Wiederherstellung an einem anderen Speicherort ist in dieser privaten Vorschauversion nicht verfügbar.

* Am ursprünglichen Speicherort wiederherstellen




== So funktioniert die Wiederherstellung von Oracle-Datenbanken

Wenn Sie Oracle-Datenbanken wiederherstellen, geschieht Folgendes:

* Wenn Sie eine Datenbank aus einem lokalen Snapshot wiederherstellen, erstellt NetApp Backup and Recovery eine _neue_ Ressource mithilfe der Daten aus dem Backup.
* Wenn Sie aus einem replizierten Speicher wiederherstellen, können Sie es am ursprünglichen Speicherort wiederherstellen.
* Wenn Sie ein Backup aus dem Objektspeicher wiederherstellen, können Sie die Daten im Quellspeicher oder auf einem lokalen ONTAP -System wiederherstellen und die Datenbank von dort wiederherstellen.


Auf der Seite „Wiederherstellen“ (auch als „Suchen und Wiederherstellen“ bezeichnet) können Sie eine Datenbank wiederherstellen, auch wenn Sie sich nicht an den genauen Namen, den Speicherort oder das Datum erinnern, an dem sie zuletzt in gutem Zustand war.  Sie können mithilfe von Filtern nach der Datenbank suchen.



== Wiederherstellen einer Oracle-Datenbank

Stellen Sie je nach Bedarf eine Oracle-Datenbank zu einem bestimmten Zeitpunkt, zu einer bestimmten Systemänderungsnummer (SCN) oder zum letzten fehlerfreien Zustand wieder her.  Sie können die Datenbank auch einfach aus Snapshots wiederherstellen und den automatisierten Wiederherstellungsprozess überspringen.  Wenn Sie die Wiederherstellung manuell durchführen möchten, können Sie den automatisierten Wiederherstellungsprozess überspringen.  Sie können die Datenbank anhand ihres Namens oder mit bestimmten Filtern suchen.

*Erforderliche Konsolenrolle* Superadministrator für Backup und Wiederherstellung oder Administratorrolle für Backup und Wiederherstellung zur Wiederherstellung. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Zugriffsrollen der NetApp Console für alle Dienste"^] .

.Schritte
. Wählen Sie im NetApp Console *Schutz > Sicherung und Wiederherstellung*.
. Wählen Sie im NetApp Backup and Recovery -Menü *Wiederherstellen* aus.
. Wählen Sie aus der Dropdown-Liste rechts neben dem Namenssuchfeld *Oracle* aus.
. Geben Sie den Namen der Datenbank ein, die Sie wiederherstellen möchten, oder filtern Sie nach dem Datenbankhost, auf dem sich die wiederherzustellende Datenbank befindet.
+
Es wird eine Liste mit Snapshots angezeigt, die Ihren Suchkriterien entsprechen.

. Wählen Sie die Schaltfläche *Wiederherstellen* für die Datenbank, die Sie wiederherstellen möchten.
. Wählen Sie eine Wiederherstellungsoption:
+
[role="tabbed-block"]
====
.Wiederherstellung zu einem bestimmten Zeitpunkt
--
.. Wählen Sie *Zu einem bestimmten Zeitpunkt wiederherstellen*.
.. Wählen Sie *Weiter*.
.. Wählen Sie ein Datum aus der Dropdown-Liste und wählen Sie *Suchen*.
+
Es wird eine Liste mit passenden Schnappschüssen zum angegebenen Datum angezeigt.



--
.Wiederherstellen auf eine bestimmte Systemänderungsnummer (SCN)
--
.. Wählen Sie *Auf eine bestimmte Systemänderungsnummer (SCN) wiederherstellen*.
.. Wählen Sie *Weiter*.
.. Geben Sie die SCN ein, die als Wiederherstellungspunkt verwendet werden soll, und wählen Sie *Suchen*.
+
Es wird eine Liste mit passenden Snapshots für die angegebene SCN angezeigt.



--
.Wiederherstellen auf die letzte Sicherung (letzter guter Zustand)
--
.. Wählen Sie *Auf die neueste Sicherung wiederherstellen*.
.. Wählen Sie *Weiter*.
+
Es werden die neuesten Voll- und Protokollsicherungen angezeigt.



--
.Wiederherstellen aus Snapshots ohne Wiederherstellung
--
.. Wählen Sie *Aus Snapshots ohne Wiederherstellung wiederherstellen*.
.. Wählen Sie *Weiter*.
+
Die passenden Schnappschüsse werden angezeigt.



--
====
. Wählen Sie einen Quellspeicherort für den Snapshot aus.
. Wählen Sie *Weiter*, um mit der Seite „Zieleinstellungen wiederherstellen“ fortzufahren.
+
Als Nächstes können Sie die Zieleinstellungen sowie die Optionen vor und nach der Wiederherstellung auswählen.



[discrete]
===== Zielauswahl

. Wählen Sie die Zieleinstellungen und die Optionen vor und nach der Wiederherstellung.


[role="tabbed-block"]
====
.Am ursprünglichen Speicherort wiederherstellen
--
. *Zieleinstellungen*:
+
** Wählen Sie, ob die gesamte Datenbank oder nur die Tablespaces für die Datenbank wiederhergestellt werden sollen.
** *Steuerdateien*: Aktivieren Sie diese Option optional, um auch die Datenbank-Steuerdateien wiederherzustellen.


. *Optionen vor der Wiederherstellung*:
+
** Aktivieren Sie diese Option optional und geben Sie den vollständigen Pfad für ein Skript ein, das vor dem Wiederherstellungsvorgang ausgeführt werden soll, sowie alle Argumente, die das Skript verwendet.
** Wählen Sie einen Timeout-Wert für das Skript.  Wenn die Ausführung des Skripts innerhalb dieses Zeitraums fehlschlägt, wird die Wiederherstellung trotzdem fortgesetzt.


. *Optionen nach der Wiederherstellung*:
+
** *Postscript*: Aktivieren Sie diese Option optional und geben Sie den vollständigen Pfad für ein Skript ein, das nach dem Wiederherstellungsvorgang ausgeführt werden soll, sowie alle Argumente, die das Skript verwendet.
** *Öffnen Sie die Datenbank oder Containerdatenbank nach der Wiederherstellung im LESE-/SCHREIB-Modus*: Nachdem der Wiederherstellungsvorgang abgeschlossen ist, aktiviert Backup and Recovery den LESE-/SCHREIB-Modus für die Datenbank.


. Abschnitt *Benachrichtigung*:
+
** *E-Mail-Benachrichtigungen aktivieren*: Wählen Sie diese Option aus, um E-Mail-Benachrichtigungen über den Wiederherstellungsvorgang zu erhalten, und geben Sie an, welche Art von Benachrichtigungen Sie erhalten möchten.


. Wählen Sie *Wiederherstellen*.


--
.An einem anderen Speicherort wiederherstellen
--
Nicht für die Vorschau von Oracle-Workloads verfügbar.

--
====