---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Beginnen Sie mit NetApp Backup and Recovery, indem Sie die Bereitschaft Ihrer Betriebsumgebung, Ihres Konsolenagenten und Ihres Konsolenkontos überprüfen.  Um NetApp Backup and Recovery verwenden zu können, benötigen Sie diese Voraussetzungen. 
---
= NetApp Backup and Recovery-Anforderungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie mit der Nutzung von NetApp Backup and Recovery beginnen, stellen Sie sicher, dass Ihre NetApp Console und Ihre Betriebsumgebung die folgenden Anforderungen erfüllen.



[[prepare-to-use-netapp-backup-and-recovery]]
== Vorbereitung auf die Nutzung von NetApp Backup and Recovery

Auf NetApp Backup and Recovery wird über die NetApp Console zugegriffen. Folgende Aufgaben bereiten die Console für Backup and Recovery vor, abhängig davon, ob NetApp Console oder NetApp Console lokale Bereitstellung verwendet wird.



[[prepare-to-use-backup-and-recovery-on-netapp-console]]
=== Vorbereitung auf die Nutzung von Backup und Recovery auf der NetApp Console

Zur Vorbereitung der NetApp Console für Backup und Recovery sind folgende Schritte erforderlich:

* Vollständige Ersteinrichtung
* Fügen Sie einen Konsolenagenten hinzu
* Fügen Sie mindestens ein Speichersystem hinzu
* Backup and Recovery aktivieren
* Konfigurieren einer Console-Organisation und Benutzerrollen


Sie benötigen die Rolle „Organisationsadministrator“ oder „Superadministrator“ in der NetApp Console, um diese Vorbereitung abzuschließen.

Weitere Informationen zu NetApp Console finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console für einheitliches Speichermanagement"^].



==== Vollständige Ersteinrichtung der NetApp Console

Schließen Sie die Ersteinrichtung für NetApp Console ab, falls Sie dies noch nicht getan haben.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Einstiegsarbeitsablauf für die NetApp Console"^]



==== Einen Console-Agenten bereitstellen

Ein Console-Agent ist eine schlanke Softwarekomponente, die Sie in Ihrem Netzwerk installieren, um Ihre Speicherinfrastruktur mit NetApp Console zu verbinden. Er ermöglicht erweiterte Speicherorchestrierung, Datendienste und sichere Cloud-Integration.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Erfahren Sie mehr über Konsolenagenten"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Einen Console-Agenten bereitstellen"^]



==== Fügen Sie ein Speichersystem hinzu

Bevor Sie Workloads in NetApp Backup and Recovery schützen können, müssen Sie ein ONTAP Storage-System zur NetApp Console hinzufügen.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Lokale ONTAP Cluster in der NetApp Console entdecken"^]



==== Backup und Recovery in der NetApp Console aktivieren

Die Sicherung und Wiederherstellung kann auf einem System beim Hinzufügen oder zu einem späteren Zeitpunkt aktiviert werden.

link:br-start-enable.html#enable-backup-and-recovery-in-netapp-console["Backup und Recovery für ein System aktivieren"^].



==== Konfigurieren einer Organisation und von Benutzerrollen

Informationen zu Organisationen, Projekten, Flotten und Benutzerrollen sowie zur Konfiguration von Benutzern mit den entsprechenden Berechtigungen, die für die Ausführung ihrer Aufgaben erforderlich sind.

Informationen zur Kontrolle des Ressourcenzugriffs sind unter  https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["Fügen Sie einer NetApp Console-Organisation Benutzer hinzu"] zu finden.

Weitere Informationen zu den Rollen und Berechtigungen, die für die Durchführung von Vorgängen in NetApp Backup and Recovery erforderlich sind, finden Sie unter  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Backup and Recovery -Rollen in der NetApp Console"].



[[prepare-to-use-backup-and-recovery-on-netapp-console-local-deployment]]
=== Vorbereitung der Nutzung von Backup und Recovery auf der lokalen NetApp Console-Bereitstellung

Um die Verwendung von NetApp Backup and Recovery auf der lokalen NetApp Console vorzubereiten, müssen Sie Folgendes beachten:

* Abschließen der anfänglichen NetApp Console Einrichtung für die lokale Bereitstellung
* Für die Vorschauanmeldung registrieren
* Fügen Sie mindestens ein Speichersystem hinzu
* Backup and Recovery aktivieren
* Benutzern Zugriff auf Ressourcen gewähren


Sie benötigen die Rolle „Organisationsadministrator“ oder „Superadministrator“ in der lokalen NetApp Console-Bereitstellung, um diese Vorbereitung abzuschließen.

Weitere Informationen zur lokalen Bereitstellung der NetApp Console sind unter  https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Informationen zur lokalen Bereitstellung der NetApp Console"^] zu finden.



==== Abschließen der anfänglichen NetApp Console Einrichtung für die lokale Bereitstellung

Die Ersteinrichtung für die lokale Bereitstellung der NetApp Console sollte abgeschlossen sein, falls dies noch nicht erfolgt ist. Zur Ersteinrichtung gehört das Hinzufügen von Lizenzen für Datendienste (einschließlich Backup und Recovery).

https://docs.netapp.com/us-en/console-local/task-quick-start-console-setup.html["Erste Schritte mit der lokalen NetApp Console-Bereitstellung"^]



==== Für die Vorschauanmeldung zu NetApp Backup and Recovery registrieren

Für die Vorschau von NetApp Backup and Recovery bei der lokalen Bereitstellung der NetApp Console anmelden:

https://forms.cloud.microsoft/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOmNJwiQYiM5EhCH6-tDLH1hUMzBMVUY4Vk5DNDlRRzlKV1dORUlKQkUwNS4u&route=shorturl["Das Anmeldeformular für die Vorschau ausfüllen."^]



==== Fügen Sie ein Speichersystem hinzu

Bevor Sie Workloads in NetApp Backup and Recovery schützen können, müssen Sie ein ONTAP Storage-System zur NetApp Console hinzufügen.

https://docs.netapp.com/us-en/console-local/task-discover-storage.html["Speicher in der lokalen NetApp Console-Bereitstellung hinzufügen"^]



==== Backup und Recovery in der lokalen NetApp Console-Bereitstellung aktivieren

Die Sicherung und Wiederherstellung kann auf einem System beim Hinzufügen oder zu einem späteren Zeitpunkt aktiviert werden.

link:br-start-enable.html#enable-backup-and-recovery-in-netapp-console-local-deployment["Backup und Recovery für ein System aktivieren"^].



==== Benutzern Zugriff auf Ressourcen gewähren

Informationen zum Identitäts- und Zugriffsmanagement sowie zur Konfiguration von Benutzern mit den entsprechenden Berechtigungen, die für die Ausführung ihrer Aufgaben erforderlich sind.

Weitere Informationen zu Identität und Zugriff enthält  https://docs.netapp.com/us-en/console-local/task-iam-fleet-mgmt-get-started.html["Erste Schritte mit Identität und Zugriff in der lokalen NetApp Console-Bereitstellung"].

Weitere Informationen zu den Rollen und Berechtigungen, die für die Durchführung von Vorgängen in NetApp Backup and Recovery erforderlich sind, finden Sie unter  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Backup and Recovery -Rollen in der NetApp Console"].



[[requirements-for-backups-to-object-storage]]
== Anforderungen an Backups im Objektspeicher

Um Objektspeicher als Backup-Ziel zu verwenden, benötigen Sie ein Konto bei AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID oder ONTAP und die entsprechenden Zugriffsberechtigungen.



[[requirements-for-protecting-ontap-volume-workloads]]
== Anforderungen zum Schutz von ONTAP-Volume-Workloads

Um NetApp Backup and Recovery für ONTAP-Volume-Workloads zu verwenden, benötigen Sie die folgenden Voraussetzungen hinsichtlich Hostsystem, Speicherplatz und Dimensionierung.

* ONTAP 9.8 oder höher ist erforderlich.
* Für den Schutz von FlexGroup Volumes ist ONTAP 9.12.1 oder höher erforderlich. Weitere Informationen sind unter link:br-reference-limitations.html["Bekannte Einschränkungen bei NetApp Backup and Recovery für ONTAP -Volumes"] verfügbar.
* Für die Sicherung oder Wiederherstellung auf S3-kompatiblem Objektspeicher ist ONTAP 9.17.1 oder höher erforderlich.
* ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen (bis zu maximal 100 Buckets).
* Auf der lokalen ONTAP Instanz muss eine ONTAP One License aktiviert sein.


Weitere Informationen zu unterstützten Funktionen, Volumentypen, Sicherungs- und Wiederherstellungszielen und mehr finden Sie unter link:prev-ontap-protect-overview.html["Schützen Sie Ihre ONTAP Volume-Daten"].



[[requirements-for-protecting-microsoft-sql-server-workloads]]
== Anforderungen zum Schutz von Microsoft SQL Server-Workloads

Um NetApp Backup and Recovery für Microsoft SQL Server-Workloads zu verwenden, benötigen Sie die folgenden Voraussetzungen hinsichtlich Hostsystem, Speicherplatz und Größe.


NOTE: ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen (bis zu maximal 100 Buckets).

[cols="33,66a"]
|===
| Artikel | Anforderungen 


| Betriebssysteme  a| 
Microsoft Windows: Aktuelle Informationen zu unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp Interoperabilitätsmatrix-Tool"^] .



| Microsoft SQL Server-Versionen  a| 
Version 2012 und höher werden für VMware Virtual Machine File System (VMFS) und VMware Virtual Machine Disk (VMDK) NFS unterstützt.



| SnapCenter Server-Version  a| 
Wenn Sie Ihre vorhandenen Daten aus SnapCenter in NetApp Backup and Recovery importieren möchten, ist SnapCenter Server Version 5.0 oder höher erforderlich.


NOTE: Wenn Sie bereits über SnapCenter verfügen, überprüfen Sie zunächst, ob Sie die Voraussetzungen erfüllt haben, bevor Sie aus SnapCenter importieren.  Sehenlink:concept-start-prereq-snapcenter-import.html["Voraussetzungen für den Import von Ressourcen aus SnapCenter"] .



| Mindest-RAM für das Plug-In auf dem SQL Server-Host  a| 
1 GB



| Minimaler Installations- und Protokollspeicherplatz für das Plug-In auf dem SQL Server-Host  a| 
5 GB

Weisen Sie ausreichend Speicherplatz zu und überwachen Sie den Speicherverbrauch des Protokollordners.  Der erforderliche Protokollspeicherplatz variiert je nach Anzahl der durchgeführten Sicherungen und der Häufigkeit der Datenschutzvorgänge.  Wenn nicht genügend Speicherplatz vorhanden ist, werden die Protokolle für die Vorgänge nicht erstellt.



| Erforderliche Softwarepakete  a| 
* ASP.NET Core Runtime 10.0.10 Hosting Bundle
* PowerShell 7.6.4


Die neuesten Informationen zu unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp Interoperabilitätsmatrix-Tool"^] .

|===
[cols="33,66a"]
|===
| Datenbankhost | Unterstützter Speicher 


| Physischer Server  a| 
* LUNs, die über Fibre Channel präsentiert werden
* LUNs, die über iSCSI präsentiert werden




| VMware VM  a| 
* iSCSI-LUNs, die direkt vom Gast-System über den iSCSI-Initiator verbunden sind
* Virtual Machine File Systems (VMFS)
* NFS-Datenspeicher




| Hyper-V-VM  a| 
iSCSI-LUNs, die direkt vom Gast-System über den iSCSI-Initiator verbunden sind


NOTE: Der Schutz von Datenbanken, die auf Passthrough-Disks oder VHD/VHDX-Dateien gespeichert sind, die auf NetApp Speicher bereitgestellt werden, wird nicht unterstützt.

|===


[[requirements-for-protecting-vmware-workloads]]
== Anforderungen zum Schutz von VMware-Workloads

Sie benötigen bestimmte Anforderungen, um Ihre VMware-Workloads zu erkennen und zu schützen.

|===
| Anforderung | Unterstützt 


| Datenspeichertypen | NFSv3, NFSv4.1 und VMFS 


| VMware ESXi Server-Versionen | 7.0U1 und höher 


| VMware vCenter vSphere Versionen | 7.0U1 und höher 


| VMware Tools | VMware Tools wird für die Wiederherstellung von Dateien und Ordnern sowie für VM-konsistente Backups benötigt. Um sicherzustellen, dass die VMware Tools-Version mit Ihrer Version des ESXi Server übereinstimmt, konsultieren Sie die  https://packages.vmware.com/tools/versions["VMware-Versionszuordnungsinformationen"]. 


| IP-Adresstypen | IPv4, IPv6 


| VMware TLS-Versionen | 1.2, 1.3 


| Vernetzter Speicher  a| 
* ONTAP 9.13.1 oder höher (ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen; maximal 100 Buckets)
* Amazon FSx for NetApp ONTAP-Speichersysteme mit Version 9.13.1 oder höher
* ASA r2 SAN-only-Systeme (ONTAP 9.17.1 oder höher erforderlich)


|===
[cols="33,66a"]
|===
| Art des Anschlusses | Vorkonfigurierter Port 


| VMware ESXi-Server-Port  a| 
443 (HTTPS), bidirektional. Die Funktion zum Wiederherstellen von Dateien und Ordnern nutzt diesen Port.



| Speichercluster oder Speicher-VM-Port  a| 
* 443 (HTTPS), bidirektional.
* 80 (HTTP), bidirektional. Dieser Port wird für die Kommunikation zwischen der virtuellen Appliance und der Storage-VM oder dem Cluster, der die Storage-VM enthält, verwendet.


|===
.Anforderungen an die rollenbasierte Zugriffskontrolle (RBAC) zum Schutz von VMware-Workloads
Ihr Console-Benutzerkonto benötigt die Backup und Recovery Super-Admin-Rolle, um mit VMware-Workloads arbeiten zu können.

Weitere Informationen zu Backup- und Recovery-Rollen finden Sie unter  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Backup- und Wiederherstellungsrollen in der NetApp Console"].



[[requirements-for-protecting-kvm-workloads]]
== Anforderungen zum Schutz von KVM-Workloads

Sie benötigen bestimmte Anforderungen, um virtuelle KVM-Maschinen zu erkennen und zu schützen.


NOTE: ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen (bis zu maximal 100 Buckets).

* Eine moderne Linux-Distribution mit Kernelversion 5.14.0-503.22.1.el9_5.x86_64 (longterm) oder höher
* Ihre KVM-Hosts und VMs müssen über eine Managementplattform verwaltet werden. NetApp Backup and Recovery unterstützt die folgenden Managementplattformen:
+
** Apache CloudStack 4.22.0.0


* Stellen Sie sicher, dass eingehender Netzwerkverkehr von der Konsolenagentur zum KVM-Host an Port 22 zugelassen ist.
* QEMU-Gastagent Version 9.0.0 oder höher
* libvirt Version 10.5.0 oder höher



NOTE: Um sicherzustellen, dass die Wiederherstellung von KVM-Workloads vollständig und erfolgreich verläuft, vergewissern Sie sich, dass die Einstellung *VM-konsistenten Snapshot aktivieren* in der Schutzrichtlinie, die Sie für KVM-Backups verwenden, aktiv ist.

[NOTE]
====
Um den Schutz von KVM-VMs zu aktivieren, die von Benutzern ohne Root-Rechte verwaltet werden, führen Sie die folgenden Schritte aus:

. Binden Sie das Volume als NFS3 ein, um die Verwendung von `nobody` Benutzer und Gruppe.
. Verwenden Sie den folgenden Befehl, um einen Nicht-Root-Benutzer hinzuzufügen `qemu` Gruppen bilden und gleichzeitig ihre bestehenden Gruppen erhalten:
+
[source, shell]
----
usermod -aG qemu <non-root-user>
----
. Verwenden Sie den folgenden Befehl, um die Besitzrechte am Mount-Pfad zu übertragen. `qemu` Benutzer- und Gruppenberechtigungen für den Mount-Pfad ändern:
+
[source, shell]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Löschen Sie gegebenenfalls das vorhandene Verzeichnis NetApp_SnapCenter_Backups.


====


[[requirements-for-protecting-oracle-database-workloads]]
== Anforderungen für den Schutz von Oracle Database Workloads

Stellen Sie sicher, dass Ihre Umgebung bestimmte Anforderungen erfüllt, um Oracle Database-Ressourcen zu erkennen und zu schützen.


NOTE: ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen (bis zu maximal 100 Buckets).

|===
| Anforderung | Unterstützt 


| Bereitstellungstopologie  a| 
* Standalone (NFS, SAN, ASM SAN)
* RAC über ASM (VMDK auf VMFS)




| Oracle Database-Versionen  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| Datenbankspeicher | Muss auf NetApp ONTAP (primär oder sekundär) bereitgestellt werden 


| Host-OS  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| Objektspeicher (Backup-Ziele)  a| 
* Azure-Objektspeicher
* Amazon AWS
* NetApp StorageGRID
* ONTAP S3


|===


[[requirements-for-protecting-kubernetes-applications]]
== Anforderungen zum Schutz von Kubernetes-Anwendungen

Sie benötigen spezifische Anforderungen, um Kubernetes-Ressourcen zu erkennen und Ihre Kubernetes-Anwendungen zu schützen.


NOTE: ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen (bis zu maximal 100 Buckets).


NOTE: NetApp empfiehlt dringend, dem für Kubernetes-Workloads verwendeten Console-Agenten eine statische IP-Adresse zuzuweisen, um Probleme zu vermeiden, falls sich die IP-Adresse des Agenten ändert.

* Ein primäres ONTAP System (ASA r2-Systeme werden nicht unterstützt)
* NetApp Trident 25.06 bis 26.06
* NetApp Trident Protect 26.08 oder höher (wird während der Erkennung auf dem Kubernetes-Cluster installiert)
* Ein Kubernetes-Cluster – Unterstützte Kubernetes-Distributionen und -Versionen umfassen diejenigen, die von  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"] unterstützt werden.
+
** Stellen Sie sicher, dass TCP-Port 443 in ausgehender Richtung zwischen dem Kubernetes-Cluster, dem Trident Protect Connector und dem Trident Protect Proxy ungefiltert ist.






[[requirements-for-protecting-hyper-v-workloads]]
== Anforderungen zum Schutz von Hyper-V-Workloads

Stellen Sie sicher, dass Ihre Hyper-V-Instanz bestimmte Anforderungen zum Erkennen und Schützen virtueller Maschinen erfüllt.

|===
| Anforderung | Unterstützt 


| Microsoft Hyper-V | 2019, 2022 & 2025 Ausgaben 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle (und alle nachfolgenden 8.0.x-Patches) 


| PowerShell | 7.4.13 oder später 


| Wenn Benutzer ohne Administratorrechte Hyper-V-VMs schützen sollen, stellen Sie sicher, dass diese Benutzer über die folgenden Berechtigungen verfügen  a| 
* Mitglied der lokalen Administratorengruppe
* Teil der lokalen Sicherheitsrichtlinie „Anmeldung als Dienst“




| Stellen Sie sicher, dass in den Windows-Firewall-Einstellungen bidirektionaler HTTPS-Datenverkehr für die folgenden Ports zugelassen ist  a| 
* TCP 8144 (NetApp Plugin für Hyper-V)
* TCP 8145 (NetApp Plugin für Windows)




| Vernetzter Speicher  a| 
* ONTAP 9.13.1 oder höher
* SMB Shares
* SAN Storage, verbunden über iSCSI oder Fibre Channel


|===
.Hardwareanforderungen für den Hyper-V-Host
* Standalone- und FCI-Cluster-Hosts werden unterstützt
* Mindestens 1 GB RAM für das NetApp Hyper-V-Plug-In auf dem Hyper-V-Host
* Mindestens 5 GB Installations- und Protokollspeicherplatz für das Plug-In auf dem Hyper-V-Host
+

NOTE: Stellen Sie sicher, dass Sie auf dem Hyper-V-Host genügend Speicherplatz für den Protokollordner zuweisen und dessen Nutzung regelmäßig überwachen.  Der erforderliche Speicherplatz hängt davon ab, wie oft Backups und Datenschutzvorgänge durchgeführt werden.  Wenn nicht genügend Speicherplatz vorhanden ist, werden keine Protokolle erstellt.



.NetApp ONTAP Konfigurationsanforderungen
* Ein primäres ONTAP System (ONTAP 9.14.1 oder höher, ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System bei verschiedenen Cloud-Anbietern zu unterstützen; maximal 100 Buckets)
* Für Hyper-V-Bereitstellungen, bei denen SMB-Freigaben zur Speicherung von virtuellen Maschinendaten verwendet werden, muss die Eigenschaft „Kontinuierliche Verfügbarkeit“ der Freigabe auf dem ONTAP System aktiviert sein. Siehe  https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["ONTAP-Dokumentation"^] für Anweisungen.

