---
sidebar: sidebar 
permalink: prev-ontap-discover-no-activate.html 
keywords: activate, backup and recovery, volumes, back up, discover 
summary: Systeme und Volumes erkennen, ohne NetApp Backup and Recovery zu aktivieren. 
---
= ONTAP-Systeme und Volumes erkennen, ohne NetApp Backup und Recovery zu aktivieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP-Systeme und Volumes werden ermittelt, bevor NetApp Backup und Recovery aktiviert wird. Nach der Ermittlung können die Volumes überprüft werden, ein Schutz ist jedoch erst nach der Aktivierung von Backup und Recovery möglich.

.Schritte
. Wechseln Sie zu *Schutz > Sicherung und Wiederherstellung*.
. Die Kachel *Volumes* auswählen.
+
Das Volumes Dashboard wird angezeigt.

. *Systeme ermitteln* auswählen.
. In der Liste alle Systeme auswählen, deren Volumes entdeckt werden sollen.
. Wählen Sie *Entdecken*.
. Wählen Sie in NetApp Backup and Recovery*Inventar* aus.
+
Der Erkennungsprozess beginnt. Status und Ergebnis der Erkennung sind im Jobmonitor sichtbar.


