---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp NetApp Backup and Recovery. 
---
= Erstellen Sie eine Richtlinie zum Sichern von Datenspeichern in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine Richtlinie erstellen oder eine der folgenden vordefinierten Richtlinien verwenden, die in NetApp Backup and Recovery verfügbar sind.

[]
====
*HINWEIS* Informationen zum Wechseln zwischen NetApp Backup and Recovery -Workloads finden Sie unterlink:br-start-switch-ui.html["Wechseln Sie zu anderen NetApp Backup and Recovery -Workloads"] .

====
.Bevor Sie beginnen
* Sie sollten Richtlinien erstellen, wenn Sie die vordefinierten Richtlinien nicht bearbeiten möchten.
* Um Backups vom Objektspeicher in den Archivspeicher zu verschieben, sollten Sie ONTAP 9.10.1 oder höher ausführen und Amazon Web Services oder Microsoft Azure sollte der Cloud-Anbieter sein.
* Sie sollten die Archivzugriffsebene für jeden Cloud-Anbieter konfigurieren.


.Informationen zu diesem Vorgang
Die folgenden vordefinierten Richtlinien sind in der NetApp Console verfügbar:

|===
| Richtlinienname | Etikett | Retentionswert 


 a| 
1 Jahr täglich LTR (Langzeitaufbewahrung)
 a| 
Täglich
 a| 
366



 a| 
5 Jahre täglich LTR
 a| 
Täglich
 a| 
1830



 a| 
7 Jahre wöchentliche LTR
 a| 
Wöchentlich
 a| 
370



 a| 
10 Jahre monatliche LTR
 a| 
Monatlich
 a| 
120

|===
.Schritte
. Wählen Sie auf der Seite „Virtuelle Maschinen“ aus der Dropdownliste „Einstellungen“ die Option „Richtlinien“ aus.
. Wählen Sie *Richtlinie erstellen*.
. Geben Sie im Abschnitt „Richtliniendetails“ den Richtliniennamen an.
. Wählen Sie im Abschnitt „Aufbewahrung“ einen Aufbewahrungstyp aus und geben Sie die Anzahl der aufzubewahrenden Sicherungen an.
. Wählen Sie „Primär“ oder „Sekundär“ als Sicherungsspeicherquelle aus.
. (Optional) Wenn Sie Sicherungen zur Kostenoptimierung nach einer bestimmten Anzahl von Tagen vom Objektspeicher in den Archivspeicher verschieben möchten, aktivieren Sie das Kontrollkästchen *Sicherungen in Archivspeicher verschieben* und geben Sie die Anzahl der Tage ein, nach denen die Sicherung archiviert werden soll.
. Wählen Sie *Erstellen*.
+

NOTE: Sie können eine Richtlinie, die mit einem Datenspeicher verknüpft ist, weder bearbeiten noch löschen.


