---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery unterstützt eine Archivspeicherklasse von Google und die meisten Regionen. 
---
= Unterstützte Google-Archivspeicherebenen mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery unterstützt eine Archivspeicherklasse von Google und die meisten Regionen.

[]
====
*HINWEIS* Informationen zum Wechseln zwischen NetApp Backup and Recovery UI-Versionen finden Sie unterlink:br-start-switch-ui.html["Wechseln Sie zur vorherigen NetApp Backup and Recovery -Benutzeroberfläche"] .

====


== Unterstützte Google-Archivspeicherklassen für NetApp Backup and Recovery

Wenn Sicherungsdateien zunächst erstellt werden, werden sie im _Standard_-Speicher gespeichert.  Diese Ebene ist für die Speicherung selten abgerufener Daten optimiert, ermöglicht Ihnen aber auch den sofortigen Zugriff darauf.

Wenn Ihr Cluster vor Ort ONTAP 9.12.1 oder höher verwendet, können Sie zur weiteren Kostenoptimierung in der NetApp Backup and Recovery Benutzeroberfläche ältere Backups nach einer bestimmten Anzahl von Tagen (normalerweise mehr als 30 Tage) in den Archivspeicher verschieben.  Für die Datenabfrage in dieser Ebene fallen höhere Kosten an. Sie müssen daher berücksichtigen, wie oft Sie Daten aus diesen archivierten Sicherungsdateien wiederherstellen müssen.  Weitere Informationen zum Wiederherstellen von Daten aus dem Archivspeicher finden Sie im Abschnitt auf dieser Seite.

Beachten Sie, dass Sie beim Konfigurieren von NetApp Backup and Recovery mit dieser Art von Lebenszyklusregel beim Einrichten des Buckets in Ihrem Google-Konto keine Lebenszyklusregeln konfigurieren dürfen.

https://cloud.google.com/storage/docs/storage-classes["Informationen zu Google-Speicherklassen"^].



== Daten aus dem Archivspeicher wiederherstellen

Während die Speicherung älterer Sicherungsdateien im Archivspeicher wesentlich günstiger ist als die Speicherung im Standardspeicher, dauert der Zugriff auf Daten aus einer Sicherungsdatei im Archivspeicher für Wiederherstellungsvorgänge etwas länger und ist teurer.

Wie viel kostet die Wiederherstellung von Daten aus dem Google-Archiv?:: Detaillierte Preise für Google Cloud Storage nach Regionen finden Sie auf der https://cloud.google.com/storage/pricing["Preisseite für Google Cloud Storage"^] .
Wie lange dauert die Wiederherstellung meiner im Google-Archiv archivierten Objekte?:: Die gesamte Wiederherstellungszeit besteht aus zwei Teilen:
+
--
* *Abrufzeit*: Die Zeit, die zum Abrufen der Sicherungsdatei aus dem Archiv und zum Platzieren im Standardspeicher benötigt wird.  Dies wird manchmal als „Rehydratationszeit“ bezeichnet.  Im Gegensatz zu den „kältesten“ Speicherlösungen anderer Cloud-Anbieter sind Ihre Daten innerhalb von Millisekunden zugänglich.
* *Wiederherstellungszeit*: Die Zeit, die zum Wiederherstellen der Daten aus der Sicherungsdatei im Standardspeicher benötigt wird.  Diese Zeit unterscheidet sich nicht von der typischen Wiederherstellungsoperation direkt vom Standardspeicher – wenn keine Archivierungsebene verwendet wird.


--

