---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp Backup and Recovery. 
---
= On-Premises ONTAP-Daten auf S3-kompatiblen Speicher mit NetApp Backup und Recovery sichern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Auf dieser Seite kann überprüft werden, ob die Konfiguration unterstützt wird, und Backups von den primären On-Premises ONTAP Systemen in S3-kompatiblen Objektspeicher in NetApp Backup and Recovery konfiguriert werden.



[[verify-support-for-your-configuration]]
== Überprüfen der Unterstützung für Ihre Konfiguration

Lesen Sie die folgenden Anforderungen, um sicherzustellen, dass Sie über eine unterstützte Konfiguration verfügen, bevor Sie mit dem Sichern von Volumes auf S3-kompatiblen Speicher beginnen.

Unterstützte ONTAP-Versionen:: Eine Mindestversion von ONTAP 9.17.1 ist erforderlich.




[[supported-actions]]
=== Unterstützte Aktionen

Folgende Aktionen werden beim Sichern auf S3-kompatiblem Speicher unterstützt:

* Sicherung von absturzkonsistenten und anwendungskonsistenten Snapshots von lokalem ONTAP in S3-kompatible Objektspeicher von Drittanbietern
* Kernprozesse für den Datenschutz: Backup, Wiederherstellung und Backup-Löschung
* Getestet und validiert mit Wasabi Object Storage; Kunden haben auch erfolgreiche Implementierungen mit MinIO und IBM Cloud Object Storage gemeldet.
* NetApp Support nimmt alle Supportanfragen im Zusammenhang mit S3-kompatiblen Objektspeichern von Drittanbietern entgegen und triagiert sie.




[[unsupported-features-and-configurations]]
=== Nicht unterstützte Funktionen und Konfigurationen

Die folgenden Funktionen und Konfigurationen werden bei der Datensicherung auf S3-kompatiblem Speicher nicht unterstützt:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt
* DataLock-Aktivierung in Sicherungsrichtlinien wird nicht unterstützt
* Die Aktivierung des Archivierungsmodus in Sicherungsrichtlinien wird nicht unterstützt
* Verschlüsselungsoptionen auf Bucket-Ebene werden nicht unterstützt
* MetroCluster-Konfigurationen werden nicht unterstützt
* Cloudbasierte ONTAP-Umgebungen werden nicht unterstützt – es wird nur On-Premises-ONTAP unterstützt




[[caveats]]
=== Vorbehalte

Beachten Sie beim Sichern auf S3-kompatiblem Speicher die folgenden Punkte:

* *Die Leistung kann nicht garantiert werden*: NetApp-Produkte reagieren empfindlich auf die Latenz und IOPS der S3-API. Drittanbieter-Objektspeicher müssen eine mit AWS S3 vergleichbare Latenz und IOPS bieten, um eine vergleichbare Leistung zu erzielen. NetApp führt keine Fehlerbehebung bei der Objektspeicher-Performance durch.
* *Keine Haftung für Datenbeschädigung oder -verlust*: NetApp ist nicht verantwortlich für Datenverlust oder Serviceausfälle, die durch Probleme mit S3-Objektspeichern von Drittanbietern verursacht werden.
* *Eingeschränkte Funktionsunterstützung*: Der unterstützte Funktionsumfang für S3-kompatible Drittanbieterziele ist eine Teilmenge dessen, was für native Ziele (AWS S3, Azure Blob, GCP, ONTAP S3, StorageGRID) verfügbar ist.




[[prepare-your-console-agent]]
== Vorbereiten Ihres Konsolenagenten

Der Konsolenagent ist die Hauptsoftware für die NetApp Console .  Zum Sichern und Wiederherstellen Ihrer ONTAP Daten ist ein Konsolenagent erforderlich.



[[create-or-switch-console-agents]]
=== Erstellen oder Wechseln von Konsolenagenten

Wenn Sie Daten auf einem S3-kompatiblen Speicher sichern, muss ein Console Agent lokal oder in der Cloud verfügbar sein. Es ist entweder ein neuer Console Agent zu installieren oder sicherzustellen, dass sich der aktuell ausgewählte Console Agent an einem dieser Standorte befindet. Der lokale Console Agent kann an einem Standort mit oder ohne Internetzugang installiert werden.

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Erfahren Sie mehr über Konsolenagenten"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["Installieren Sie den Konsolenagenten in Ihrer Cloudumgebung"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["Installieren des Konsolenagenten auf einem Linux-Host mit Internetzugang"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Installieren des Konsolenagenten auf einem Linux-Host ohne Internetzugang"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Wechseln zwischen Konsolenagenten"^]




[[prepare-console-agent-networking-requirements]]
=== Netzwerkanforderungen für den Konsolenagenten vorbereiten

Stellen Sie sicher, dass das Netzwerk, in dem der Konsolenagent installiert ist, die folgenden Verbindungen ermöglicht:

* Eine HTTPS-Verbindung über Port 443 zum S3-kompatiblen Server
* Eine HTTPS-Verbindung über Port 443 zu Ihrem Quell ONTAP Cluster-Management-LIF
* Eine ausgehende Internetverbindung über Port 443 zu NetApp Backup and Recovery (nicht erforderlich, wenn der Konsolenagent an einem „dunklen“ Standort installiert ist)




==== Überlegungen zum privaten Modus (Dark Site)

Die NetApp Backup and Recovery Funktionalität ist in den Konsolenagenten integriert.  Wenn es im privaten Modus installiert ist, müssen Sie die Konsolenagent-Software regelmäßig aktualisieren, um Zugriff auf neue Funktionen zu erhalten.  Überprüfen Sie dielink:whats-new.html["NetApp Backup and Recovery – Neuigkeiten"] um die neuen Funktionen in jeder Version von NetApp Backup and Recovery anzuzeigen.  Wenn Sie die neuen Funktionen nutzen möchten, folgen Sie den Schritten zum https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["Aktualisieren Sie die Konsolenagentsoftware"^] .

Wenn NetApp Backup und Recovery in einer Standard-SaaS-Umgebung verwendet wird, werden die NetApp Backup und Recovery-Konfigurationsdaten in der Cloud gesichert. Wenn NetApp Backup und Recovery an einem Standort ohne Internetzugang verwendet wird, werden die NetApp Backup und Recovery-Konfigurationsdaten in dem S3-kompatiblen Bucket gesichert, in dem Ihre Backups gespeichert werden.



[[verify-license-requirements]]
== Überprüfen der Lizenzanforderungen

Bevor Sie NetApp Backup and Recovery für Ihren Cluster aktivieren können, müssen Sie eine NetApp Backup and Recovery BYOL-Lizenz von NetApp erwerben und aktivieren. Die Lizenz gilt für die Datensicherung und -wiederherstellung im Objektspeicher – für die Erstellung von Snapshots oder replizierten Volumes ist keine Lizenz erforderlich. Diese Lizenz gilt für das Konto und kann systemübergreifend verwendet werden.

Sie benötigen die Seriennummer von NetApp , die Ihnen die Nutzung des Dienstes für die Dauer und Kapazität der Lizenz ermöglicht. link:br-start-licensing.html["Erfahren Sie, wie Sie Ihre BYOL-Lizenzen verwalten"].


TIP: PAYGO-Lizenzierung wird bei der Sicherung von Dateien auf S3-kompatiblen Speichern nicht unterstützt.



[[prepare-your-ontap-clusters]]
== Bereiten Sie Ihre ONTAP -Cluster vor

Bereiten Sie Ihr lokales ONTAP -Quellsystem und alle sekundären lokalen ONTAP oder Cloud Volumes ONTAP Systeme vor.

Die Vorbereitung Ihrer ONTAP Cluster umfasst die folgenden Schritte:

* Entdecken Sie Ihre ONTAP -Systeme in der NetApp Console
* Überprüfen der ONTAP Systemanforderungen
* Überprüfen Sie die ONTAP Netzwerkanforderungen für die Datensicherung im Objektspeicher
* Überprüfen Sie die ONTAP Netzwerkanforderungen für die Replikation von Volumes




[[discover-your-ontap-systems-in-netapp-console]]
=== Entdecken Sie Ihre ONTAP -Systeme in der NetApp Console

Sowohl Ihr lokales ONTAP Quellsystem als auch alle sekundären lokalen ONTAP oder Cloud Volumes ONTAP -Systeme müssen auf der Seite *Systeme* der NetApp Console verfügbar sein.

Sie müssen die IP-Adresse der Clusterverwaltung und das Kennwort für das Administratorbenutzerkonto kennen, um den Cluster hinzuzufügen. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Erfahren Sie, wie Sie einen Cluster erkennen"^].



[[verify-ontap-system-requirements]]
=== Überprüfen der ONTAP Systemanforderungen

Stellen Sie sicher, dass Ihr ONTAP -System die folgenden Anforderungen erfüllt:

* Mindestens ONTAP 9.8; ONTAP 9.8P13 und höher wird empfohlen.
* Eine SnapMirror -Lizenz (im Premium-Paket oder Datenschutz-Paket enthalten).
+
*Hinweis:* Das „Hybrid Cloud Bundle“ ist bei der Verwendung von NetApp Backup and Recovery nicht erforderlich.

+
Erfahren Sie, wie Sie https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Verwalten Sie Ihre Cluster-Lizenzen"^] .

* Uhrzeit und Zeitzone sind richtig eingestellt.  Erfahren Sie, wie Sie https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["Konfigurieren Sie Ihre Clusterzeit"^] .
* Wenn Sie Daten replizieren, überprüfen Sie, ob auf den Quell- und Zielsystemen kompatible ONTAP Versionen ausgeführt werden.
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Kompatible ONTAP -Versionen für SnapMirror -Beziehungen anzeigen"^].





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== Überprüfen Sie die ONTAP Netzwerkanforderungen für die Datensicherung im Objektspeicher

Sie müssen sicherstellen, dass die folgenden Anforderungen auf dem System erfüllt sind, das eine Verbindung zum Objektspeicher herstellt.

[NOTE]
====
* Wenn Sie eine Fan-Out-Backup-Architektur verwenden, müssen die Einstellungen auf dem _primären_ Speichersystem konfiguriert werden.
* Wenn Sie eine kaskadierte Sicherungsarchitektur verwenden, müssen die Einstellungen auf dem _sekundären_ Speichersystem konfiguriert werden.
+
link:prev-ontap-protect-journey.html["Erfahren Sie mehr über die Arten der Backup-Architektur"].



====
Die folgenden ONTAP Cluster-Netzwerkanforderungen sind erforderlich:

* Der ONTAP Cluster initiiert eine HTTPS-Verbindung über einen vom Benutzer festgelegten Port vom Intercluster-LIF zum S3-kompatiblen Server für Backup und Recovery. Der Port ist während der Backup-Einrichtung konfigurierbar.
+
ONTAP liest und schreibt Daten in den und aus dem Objektspeicher. Der Objektspeicher wird nie initiiert, er reagiert nur.

* ONTAP erfordert eine eingehende Verbindung vom Konsolenagenten zum Cluster-Management-LIF.
* Auf jedem ONTAP Knoten, der die zu sichernden Volumes hostet, ist ein Intercluster-LIF erforderlich.  Das LIF muss mit dem _IPspace_ verknüpft sein, den ONTAP für die Verbindung mit dem Objektspeicher verwenden soll. https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["Erfahren Sie mehr über IPspaces"^] .
+
Wenn Sie NetApp Backup and Recovery einrichten, werden Sie nach dem zu verwendenden IPspace gefragt. Sie sollten den IPspace auswählen, mit dem jedes LIF verknüpft ist. Dies kann der „Standard“-IP-Bereich oder ein benutzerdefinierter IP-Bereich sein, den Sie erstellt haben.

* Die Intercluster-LIFs der Knoten können auf den Objektspeicher zugreifen (nicht erforderlich, wenn der Konsolenagent an einem „dunklen“ Standort installiert ist).
* Für die Speicher-VM, auf der sich die Volumes befinden, wurden DNS-Server konfiguriert.  Erfahren Sie, wie Sie https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["Konfigurieren Sie DNS-Dienste für die SVM"^] .
* Wenn Sie einen anderen IPspace als den Standard-IPspace verwenden, müssen Sie möglicherweise eine statische Route erstellen, um Zugriff auf den Objektspeicher zu erhalten.
* Aktualisieren Sie bei Bedarf die Firewall-Regeln, um Verbindungen des NetApp Backup and Recovery -Dienstes von ONTAP zum Objektspeicher über den von Ihnen angegebenen Port (normalerweise Port 443) und Namensauflösungsdatenverkehr von der Speicher-VM zum DNS-Server über Port 53 (TCP/UDP) zuzulassen.




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== Überprüfen Sie die ONTAP Netzwerkanforderungen für die Replikation von Volumes

Wenn Sie mit NetApp Backup and Recovery replizierte Volumes auf einem sekundären ONTAP System erstellen möchten, stellen Sie sicher, dass die Quell- und Zielsysteme die folgenden Netzwerkanforderungen erfüllen.

* Wenn sich der Cluster vor Ort befindet, sollten Sie über eine Verbindung von Ihrem Unternehmensnetzwerk zu Ihrem virtuellen Netzwerk beim Cloud-Anbieter verfügen. Dies ist normalerweise eine VPN-Verbindung.
* ONTAP -Cluster müssen zusätzliche Subnetz-, Port-, Firewall- und Clusteranforderungen erfüllen.




[[activate-backups-on-your-ontap-volumes]]
== Aktivieren Sie Backups auf Ihren ONTAP -Volumes

Aktivieren Sie Backups jederzeit direkt von Ihrem lokalen System aus.

Ein Assistent führt Sie durch die folgenden Hauptschritte:

* Wählen Sie die Volumes aus, die Sie sichern möchten
* Definieren Sie die Sicherungsstrategie und -richtlinien
* Überprüfen Sie Ihre Auswahl


Sie können auch<<API-Befehle anzeigen>> im Überprüfungsschritt, damit Sie den Code kopieren können, um die Sicherungsaktivierung für zukünftige Systeme zu automatisieren.



[[start-the-wizard]]
=== Starten des Assistenten

.Schritte
. Der Assistent zum Aktivieren von Backup und Recovery kann auf eine der folgenden Arten aufgerufen werden:
+
** Auf der Seite *Systems* der NetApp Console das System auswählen und im rechten Bereich neben Backup and Recovery die Option *Enable > Backup Volumes* auswählen.
** Wählen Sie in der Leiste „Sichern und Wiederherstellen“ *Volumes* aus.  Wählen Sie auf der Registerkarte „Volumes“ die Option *Aktionen (...)* und wählen Sie *Sicherung aktivieren* für ein einzelnes Volume (für das die Replikation oder Sicherung in den Objektspeicher noch nicht aktiviert ist).


+
Auf der Einführungsseite des Assistenten werden die Schutzoptionen angezeigt, darunter lokale Snapshots, Replikationen und Backups.  Wenn Sie in diesem Schritt die zweite Option gewählt haben, wird die Seite „Sicherungsstrategie definieren“ mit einem ausgewählten Volume angezeigt.

. Fahren Sie mit den folgenden Optionen fort:
+
** Wenn Sie bereits über einen Konsolenagenten verfügen, sind Sie startklar.  Wählen Sie einfach *Weiter*.
** Wenn Sie keinen Konsolenagenten haben, wird die Option *Konsolenagenten hinzufügen* angezeigt.  Siehe<<Vorbereiten Ihres Konsolenagenten>> .






[[select-the-volumes-that-you-want-to-back-up]]
=== Wählen Sie die Volumes aus, die Sie sichern möchten

Wählen Sie die Volumes aus, die Sie schützen möchten.  Ein geschütztes Volume ist ein Volume, das über eine oder mehrere der folgenden Optionen verfügt: Snapshot-Richtlinie, Replikationsrichtlinie, Backup-to-Object-Richtlinie.

Sie können FlexVol oder FlexGroup -Volumes schützen. Sie können jedoch keine Mischung dieser Volumes auswählen, wenn Sie die Sicherung für ein System aktivieren.  Erfahren Sie, wie Sielink:prev-ontap-backup-manage.html["Aktivieren Sie die Sicherung für zusätzliche Volumes im System"] (FlexVol oder FlexGroup), nachdem Sie die Sicherung für die ersten Volumes konfiguriert haben.

[NOTE]
====
* Sie können eine Sicherung jeweils nur auf einem einzigen FlexGroup -Volume aktivieren.
* Bei der Auswahl der zu schützenden Quellvolumes können nur Volumes mit übereinstimmenden SnapLock-Einstellungen ausgewählt werden. Die ausgewählten Volumes müssen entweder alle die SnapLock-Funktion aktiviert haben oder bei allen muss die SnapLock-Funktion deaktiviert sein.


====
.Schritte
Beachten Sie: Wenn auf die von Ihnen ausgewählten Volumes bereits Snapshot- oder Replikationsrichtlinien angewendet wurden, werden diese vorhandenen Richtlinien durch die später ausgewählten Richtlinien überschrieben.

. Wählen Sie auf der Seite „Volumes auswählen“ das oder die Volumes aus, die Sie schützen möchten.
+
** Filtern Sie die Zeilen optional, um nur Datenträger mit bestimmten Datenträgertypen, Stilen usw. anzuzeigen und so die Auswahl zu vereinfachen.
** Nachdem Sie das erste Volume ausgewählt haben, können Sie alle FlexVol Volumes auswählen (FlexGroup Volumes können jeweils nur einzeln ausgewählt werden).  Um alle vorhandenen FlexVol Volumes zu sichern, markieren Sie zuerst ein Volume und aktivieren Sie dann das Kontrollkästchen in der Titelzeile.
** Um einzelne Volumes zu sichern, aktivieren Sie das Kontrollkästchen für jedes Volume.


. Wählen Sie *Weiter*.




[[define-the-backup-strategy]]
=== Definieren Sie die Sicherungsstrategie

Zum Definieren der Sicherungsstrategie müssen die folgenden Optionen konfiguriert werden:

* Schutzoptionen: Ob Sie eine oder alle der Backup-Optionen implementieren möchten: lokale Snapshots, Replikation und Backup auf Objektspeicher
* Architektur: Ob Sie eine Fan-Out- oder eine kaskadierende Backup-Architektur verwenden möchten
* Lokale Snapshot-Richtlinie
* Replikationsziel und -richtlinie
* Informationen zur Sicherung in Objektspeichern (Anbieter, Verschlüsselung, Netzwerk, Sicherungsrichtlinie und Exportoptionen).


.Schritte
. Wählen Sie auf der Seite „Sicherungsstrategie definieren“ eine oder alle der folgenden Optionen aus.  Alle drei sind standardmäßig ausgewählt:
+
** *Lokale Snapshots*: Erstellt lokale Snapshots.
** *Replikation*: Erstellt replizierte Volumes auf einem anderen ONTAP Speichersystem.
** *Backup*: Sichert Volumes in einem Bucket auf einem für S3 konfigurierten ONTAP System.


. *Architektur*: Wenn Sie sowohl Replikation als auch Sicherung gewählt haben, wählen Sie einen der folgenden Informationsflüsse:
+
** *Kaskadierung*: Sicherungsdaten fließen vom primären zum sekundären System und dann vom sekundären zum Objektspeicher.
** *Fan-Out*: Sicherungsdaten fließen vom primären zum sekundären System _und_ vom primären zum Objektspeicher.
+
Weitere Informationen zu diesen Architekturen finden Sie unterlink:prev-ontap-protect-journey.html["Planen Sie Ihren Schutzweg"] .



. *Lokaler Snapshot*: Wählen Sie eine vorhandene Snapshot-Richtlinie oder erstellen Sie eine neue.
+

TIP: Wenn Sie vor der Aktivierung des Snapshots eine benutzerdefinierte Richtlinie erstellen möchten, können Sie den System Manager oder die ONTAP CLI verwenden. `snapmirror policy create` Befehl.  Siehe .

+

TIP: Informationen zum Erstellen einer benutzerdefinierten Richtlinie mithilfe von Backup und Recovery finden Sie unterlink:br-use-policies-create.html["Erstellen einer Richtlinie"] .

+
Um eine Richtlinie zu erstellen, wählen Sie *Neue Richtlinie erstellen* und gehen Sie wie folgt vor:

+
** Geben Sie den Namen der Richtlinie ein.
** Wählen Sie bis zu fünf Zeitpläne aus, normalerweise mit unterschiedlicher Häufigkeit.
** Wählen Sie *Erstellen*.


. *Replikation*: Wenn Sie *Replikation* ausgewählt haben, legen Sie die folgenden Optionen fest:
+
** *Replikationsziel*: Das Zielsystem und die Storage VM auswählen. Optional das Zielaggregat (oder die Zielaggregate für FlexGroup Volumes) sowie ein Präfix oder Suffix auswählen, das dem Namen des replizierten Volumes hinzugefügt wird.
** *Replikationsrichtlinie*: Wählen Sie eine vorhandene Replikationsrichtlinie aus oder erstellen Sie eine neue.
+
Um eine Richtlinie zu erstellen, wählen Sie *Neue Richtlinie erstellen* und gehen Sie wie folgt vor:

+
*** Geben Sie den Namen der Richtlinie ein.
*** Wählen Sie bis zu fünf Zeitpläne aus, normalerweise mit unterschiedlicher Häufigkeit.
*** Wählen Sie *Erstellen*.




. *Sichern auf Objekt*: Wenn Sie *Sichern* ausgewählt haben, legen Sie die folgenden Optionen fest:
+
** *Anbieter*: Wählen Sie * ONTAP S3*.
** *Anbietereinstellungen*: Geben Sie die FQDN-Details, den Port sowie den Zugriffsschlüssel und den geheimen Schlüssel des S3-Servers ein.
+
Der Zugriffsschlüssel und der geheime Schlüssel sind für den von Ihnen erstellten Benutzer, um dem ONTAP Cluster Zugriff auf den S3-Bucket zu gewähren.

** *Netzwerk*: Wählen Sie den IP-Bereich im Quell- ONTAP Cluster aus, in dem sich die Volumes befinden, die Sie sichern möchten.  Die Intercluster-LIFs für diesen IPspace müssen über ausgehenden Internetzugang verfügen (nicht erforderlich, wenn der Konsolenagent an einem „dunklen“ Standort installiert ist).
+

TIP: Durch die Auswahl des richtigen IPspace wird sichergestellt, dass NetApp Backup and Recovery eine Verbindung von ONTAP zu Ihrem ONTAP S3-Objektspeicher herstellen kann.

** *Sicherungsrichtlinie*: Wählen Sie eine vorhandene Sicherungsrichtlinie aus oder erstellen Sie eine neue.
+

TIP: Sie können eine Richtlinie mit System Manager oder der ONTAP CLI erstellen.  So erstellen Sie eine benutzerdefinierte Richtlinie mit der ONTAP CLI `snapmirror policy create` Befehl, siehe .

+

TIP: Informationen zum Erstellen einer benutzerdefinierten Richtlinie mithilfe von Backup und Recovery finden Sie unterlink:br-use-policies-create.html["Erstellen einer Richtlinie"] .

+
Um eine Richtlinie zu erstellen, wählen Sie *Neue Richtlinie erstellen* und gehen Sie wie folgt vor:

+
*** Geben Sie den Namen der Richtlinie ein.
*** Wählen Sie bis zu fünf Zeitpläne aus, normalerweise mit unterschiedlicher Häufigkeit.
*** Für Backup-to-Object-Richtlinien die Einstellungen für DataLock und Ransomware-Schutz festlegen. Weitere Informationen zu DataLock und Ransomware-Schutz finden sich unter link:prev-ontap-policy-object-options.html["Einstellungen der Backup-to-Object-Richtlinie"].
*** Wählen Sie *Erstellen*.


** *Vorhandene Snapshots als Sicherungsdateien in den Objektspeicher exportieren*: Wenn es lokale Snapshots für Volumes in diesem System gibt, die mit der von Ihnen soeben ausgewählten Sicherungszeitplanbezeichnung (z. B. täglich, wöchentlich usw.) übereinstimmen, wird diese zusätzliche Aufforderung angezeigt. Aktivieren Sie dieses Kontrollkästchen, um alle historischen Snapshots als Sicherungsdateien in den Objektspeicher zu kopieren und so den umfassendsten Schutz für Ihre Volumes zu gewährleisten.


. Wählen Sie *Weiter*.




[[review-your-selections]]
=== Überprüfen Sie Ihre Auswahl

Dies ist die Gelegenheit, Ihre Auswahl zu überprüfen und gegebenenfalls Anpassungen vorzunehmen.

.Schritte
. Überprüfen Sie Ihre Auswahl auf der Überprüfungsseite.
. Aktivieren Sie optional das Kontrollkästchen, um *die Snapshot-Richtlinienbezeichnungen automatisch mit den Replikations- und Sicherungsrichtlinienbezeichnungen zu synchronisieren*.  Dadurch werden Snapshots mit einer Bezeichnung erstellt, die mit den Bezeichnungen in den Replikations- und Sicherungsrichtlinien übereinstimmt.  Wenn die Richtlinien nicht übereinstimmen, werden keine Sicherungen erstellt.
. Wählen Sie *Backup aktivieren*.


.Ergebnis
NetApp Backup and Recovery beginnt mit der Durchführung der ersten Sicherungen Ihrer Volumes. Die Basisübertragung des replizierten Volumes und der Sicherungsdatei umfasst eine vollständige Kopie der Quelldaten. Nachfolgende Übertragungen enthalten differentielle Kopien der im Primärspeicher enthaltenen Daten, die in Snapshots gespeichert sind.

Im Zielcluster wird ein repliziertes Volume erstellt, das mit dem primären Speichervolume synchronisiert wird.

Im durch den von Ihnen eingegebenen S3-Zugriffsschlüssel und geheimen Schlüssel angegebenen Dienstkonto wird ein S3-Bucket erstellt und die Sicherungsdateien werden dort gespeichert.

Das Volume-Backup-Dashboard wird angezeigt, damit Sie den Status der Backups überwachen können.

Sie können den Status von Sicherungs- und Wiederherstellungsaufträgen auch mithilfe derlink:br-use-monitor-tasks.html["Seite „Jobüberwachung“"] .



[[show-the-api-commands]]
=== API-Befehle anzeigen

Sie können die im Assistenten „Backup und Recovery aktivieren“ verwendeten API-Befehle anzeigen und optional kopieren. Dies kann hilfreich sein, um die Aktivierung von Backups in zukünftigen Systemen zu automatisieren.

.Schritte
. Im Assistenten „Backup und Recovery aktivieren“ *API-Anfrage anzeigen* auswählen.
. Um die Befehle in die Zwischenablage zu kopieren, wählen Sie das Symbol *Kopieren*.

