---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp NetApp Backup and Recovery. 
---
= Schützen Sie die Workloads virtueller Maschinen in der NetApp Backup and Recovery -Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Schützen Sie die Workloads Ihrer virtuellen Maschinen mit NetApp Backup and Recovery.  NetApp Backup and Recovery bietet schnelle, platzsparende, absturzkonsistente und VM-konsistente Sicherungs- und Wiederherstellungsvorgänge für VMs, Datenspeicher und VMDKs.

Sie können Datenspeicher auf Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform und StorageGRID sichern und virtuelle Maschinen auf dem lokalen SnapCenter Plug-in for VMware vSphere Host wiederherstellen.

[]
====
*HINWEIS* Informationen zum Wechseln zwischen NetApp Backup and Recovery -Workloads finden Sie unterlink:br-start-switch-ui.html["Wechseln Sie zu anderen NetApp Backup and Recovery -Workloads"] .

====
Anweisungen zum Schützen der Workloads virtueller Maschinen finden Sie in den folgenden Themen:

* link:prev-vmware-policy-create.html["Erstellen einer Richtlinie für VMware-Workloads"]
* link:prev-vmware-backup-aws.html["Sichern Sie VMware-Datenspeicher auf Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Sichern Sie VMware-Datenspeicher in Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Sichern Sie VMware-Datenspeicher auf der Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Sichern Sie VMware-Datenspeicher in StorageGRID"]
* link:prev-vmware-restore.html["Wiederherstellen von VMware-Workloads"]
* link:prev-vmware-manage.html["Verwalten Sie den Schutz für VMware-Workloads"]

