---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp NetApp Backup and Recovery. 
---
= Registrieren Sie das SnapCenter Plug-in for VMware vSphere Host zur Verwendung mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten das SnapCenter Plug-in for VMware vSphere Host in NetApp Backup and Recovery registrieren, damit die Datenspeicher und virtuellen Maschinen angezeigt werden.  Nur ein Benutzer mit Administratorzugriff kann das SnapCenter Plug-in for VMware vSphere Host registrieren.

[]
====
*HINWEIS* Informationen zum Wechseln zwischen NetApp Backup und Recovery-Workloads finden Sie unterlink:br-start-switch-ui.html["Wechseln Sie zu anderen NetApp Backup- und Recovery-Workloads"] .

====
.Schritte
. Wählen Sie in der NetApp -Konsolen-Benutzeroberfläche *Schutz* > *Sicherung und Wiederherstellung* > *Virtuelle Maschinen*.
. Wählen Sie im Dropdown-Menü *Einstellungen* die Option * SnapCenter Plug-in for VMware vSphere* aus.
. Wählen Sie * SnapCenter Plug-in for VMware vSphere registrieren*.
. Geben Sie die folgenden Details an:
+
.. Geben Sie im Feld „SnapCenter Plug-in for VMware vSphere“ den FQDN oder die IP-Adresse des SnapCenter Plug-in for VMware vSphere Host an.
.. Geben Sie im Feld „Port“ die Portnummer an, auf der das SnapCenter Plug-in for VMware vSphere Host ausgeführt wird.
+
Sie sollten sicherstellen, dass die Kommunikation zwischen dem lokalen SnapCenter Plug-in for VMware vSphere Host, der auf dem Standardport 8144 ausgeführt wird, und der Konsolen-Agent-Instanz, die entweder bei einem beliebigen Cloud-Anbieter (Amazon Web Services, Microsoft Azure, Google Cloud Platform) oder vor Ort ausgeführt werden kann, offen ist.

.. Geben Sie im Feld „Benutzername“ und „Passwort“ die Anmeldeinformationen des vCenter-Benutzers mit der Administratorrolle an.


. Wählen Sie *Registrieren*.


*Nachdem Sie fertig sind*

Wählen Sie *Sicherung und Wiederherstellung* > *Virtuelle Maschinen*, um alle Datenspeicher und virtuellen Maschinen anzuzeigen, die mit dem registrierten SnapCenter Plug-in for VMware vSphere Host geschützt sind.
