---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery unterstützt eine Archivspeicherklasse von Google und die meisten Regionen. 
---
= Unterstützte Google-Archivspeicherebenen mit NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Diese Informationen dienen dem Verständnis der von NetApp Backup and Recovery unterstützten Archivierungsebene von Google Cloud Storage. Auch die Wiederherstellungskosten und Abrufzeiten für archivierte Backups können überprüft werden.



[[supported-google-archival-storage-classes-for-netapp-backup-and-recovery]]
== Unterstützte Google-Archivspeicherklassen für NetApp Backup and Recovery

Wenn Backup-Dateien initial erstellt werden, werden sie im _Standard_-Speicher gespeichert. Diese Speicherebene ist für die Speicherung von Daten optimiert, auf die selten zugegriffen wird, ermöglicht aber dennoch sofortigen Zugriff.

Wenn Ihr lokaler Cluster ONTAP 9.12.1 oder höher verwendet, kann nach einer bestimmten Anzahl von Tagen (in der Regel mehr als 30 Tagen) zur weiteren Kostenoptimierung ausgewählt werden, ältere Backups in den _Archive_-Speicher in der NetApp Backup and Recovery UI zu verschieben. Daten in dieser Ebene sind mit höheren Wiederherstellungskosten verbunden, daher sollte berücksichtigt werden, wie häufig eine Wiederherstellung von Daten aus diesen archivierten Backup-Dateien erforderlich ist. Siehe den Abschnitt auf dieser Seite zum Wiederherstellen von Daten aus dem Archivspeicher.

Beachten Sie, dass Sie beim Konfigurieren von NetApp Backup and Recovery mit dieser Art von Lebenszyklusregel beim Einrichten des Buckets in Ihrem Google-Konto keine Lebenszyklusregeln konfigurieren dürfen.

https://cloud.google.com/storage/docs/storage-classes["Informationen zu Google-Speicherklassen"^].



[[restore-data-from-archival-storage]]
== Daten aus dem Archivspeicher wiederherstellen

Während die Speicherung älterer Sicherungsdateien im Archivspeicher wesentlich günstiger ist als die Speicherung im Standardspeicher, dauert der Zugriff auf Daten aus einer Sicherungsdatei im Archivspeicher für Wiederherstellungsvorgänge etwas länger und ist teurer.

Wie viel kostet die Wiederherstellung von Daten aus dem Google-Archiv?:: Detaillierte Preise für Google Cloud Storage nach Regionen finden Sie auf der https://cloud.google.com/storage/pricing["Preisseite für Google Cloud Storage"^] .
Wie lange dauert die Wiederherstellung meiner im Google-Archiv archivierten Objekte?:: Die gesamte Wiederherstellungszeit besteht aus zwei Teilen:
+
--
* *Abrufzeit*: Die Zeit, die zum Abrufen der Sicherungsdatei aus dem Archiv und zum Platzieren im Standardspeicher benötigt wird.  Dies wird manchmal als „Rehydratationszeit“ bezeichnet.  Im Gegensatz zu den „kältesten“ Speicherlösungen anderer Cloud-Anbieter sind Ihre Daten innerhalb von Millisekunden zugänglich.
* *Wiederherstellungszeit*: Die Zeit, die zum Wiederherstellen der Daten aus der Sicherungsdatei im Standardspeicher benötigt wird.  Diese Zeit unterscheidet sich nicht von der typischen Wiederherstellungsoperation direkt vom Standardspeicher – wenn keine Archivierungsebene verwendet wird.


--

