---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, Console agent 
summary: 'Im privaten Modus (ohne Internetzugang) speichert NetApp Backup and Recovery seine Konfigurationsdaten im selben StorageGRID- oder ONTAP-S3-Bucket, der auch für Ihre Backups verwendet wird. Sollte das Hostsystem des Console-Agenten ausfallen, können Sie einen neuen Console-Agenten bereitstellen und diese Daten wiederherstellen.' 
---
= Wiederherstellen der NetApp Backup and Recovery -Konfigurationsdaten in einer Dark Site
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Im privaten Modus (ohne Internetzugang) speichert NetApp Backup and Recovery seine Konfigurationsdaten im selben StorageGRID- oder ONTAP-S3-Bucket, der auch für Ihre Backups verwendet wird. Sollte das Hostsystem des Console-Agenten ausfallen, können Sie einen neuen Console-Agenten bereitstellen und diese Daten wiederherstellen.

Es besteht auch die Möglichkeit, diese Schritte auszuführen, um den Console Agent zu ersetzen und Konfigurationsdaten wiederherzustellen, die darauf gespeichert waren, wenn Backup and Recovery im _Standardmodus_ lokal genutzt wurde und keine Cloud-Konten beteiligt sind (zum Beispiel wenn NetApp StorageGRID als Backup-Ziel verwendet wird).


NOTE: Dieses Verfahren gilt nur für ONTAP Volume-Daten.

Wenn Sie NetApp Backup and Recovery in einer SaaS-Umgebung verwenden und der Konsolenagent bei Ihrem Cloud-Anbieter oder auf Ihrem eigenen mit dem Internet verbundenen Host bereitgestellt wird, sichert und schützt das System alle wichtigen Konfigurationsdaten in der Cloud.  Wenn Sie ein Problem mit dem Konsolenagenten haben, erstellen Sie einen neuen Konsolenagenten und fügen Sie Ihre Systeme hinzu.  Die Sicherungsdetails werden automatisch wiederhergestellt.

Es werden zwei Arten von Daten gesichert:

* NetApp Backup and Recovery -Datenbank – enthält eine Liste aller Volumes, Sicherungsdateien, Sicherungsrichtlinien und Konfigurationsinformationen.
* Indizierte Katalogdateien – enthalten detaillierte Indizes, die für die Such- und Wiederherstellungsfunktion verwendet werden und Ihre Suche nach Volumedaten, die Sie wiederherstellen möchten, sehr schnell und effizient machen.


Diese Daten werden einmal täglich um Mitternacht gesichert und es werden maximal 7 Kopien jeder Datei aufbewahrt. Wenn der Konsolenagent mehrere lokale ONTAP -Systeme verwaltet, werden die NetApp Backup and Recovery im Bucket des zuerst aktivierten Systems gespeichert.


TIP: In der NetApp Backup and Recovery -Datenbank oder in den indizierten Katalogdateien sind niemals Volumedaten enthalten.



[[restore-netapp-backup-and-recovery-data-to-a-new-console-agent]]
== Wiederherstellen von NetApp Backup and Recovery -Daten auf einem neuen Konsolenagenten

Wenn Ihr lokaler Konsolenagent nicht mehr funktioniert, müssen Sie einen neuen Konsolenagenten installieren und dann die NetApp Backup and Recovery -Daten auf dem neuen Konsolenagenten wiederherstellen.

Sie müssen die folgenden Aufgaben ausführen, um Ihr NetApp Backup and Recovery -System wieder in einen funktionsfähigen Zustand zu versetzen:

* Installieren Sie einen neuen Konsolenagenten
* Wiederherstellen der NetApp Backup and Recovery -Datenbank
* Wiederherstellen der indizierten Katalogdateien
* Erkennen Sie alle Ihre On-Premise ONTAP -Systeme und StorageGRID Systeme erneut in der NetApp Console Benutzeroberfläche.


Nachdem Sie überprüft haben, ob Ihr System funktioniert, erstellen Sie neue Sicherungsdateien.

.Was du brauchst
Sie müssen auf die aktuellsten Datenbank- und Indexsicherungen aus dem StorageGRID oder ONTAP S3-Bucket zugreifen, in dem Ihre Sicherungsdateien gespeichert sind:

* NetApp Backup and Recovery MySQL-Datenbankdatei
+
Diese Datei befindet sich am folgenden Speicherort im Bucket `netapp-backup-<GUID>/mysql_backup/` und es heißt `CBS_DB_Backup_<day>_<month>_<year>.sql` .

* ZIP-Sicherungsdatei des indizierten Katalogs
+
Diese Datei befindet sich am folgenden Speicherort im Bucket `netapp-backup-<GUID>/catalog_backup/` und es heißt `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip` .





[[install-a-new-console-agent-on-a-new-on-premises-linux-host]]
=== Installieren Sie einen neuen Konsolen-Agenten auf einem neuen lokalen Linux-Host

Laden Sie beim Installieren eines neuen Konsolenagenten dieselbe Softwareversion wie den ursprünglichen Agenten herunter. Änderungen an der NetApp Backup and Recovery Datenbank können dazu führen, dass neuere Softwareversionen nicht mit alten Datenbanksicherungen funktionieren. Sie können https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["Aktualisieren Sie die Konsolen-Agent-Software auf die neueste Version, nachdem Sie die Backup-Datenbank wiederhergestellt haben."^].

. https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Installieren Sie den Konsolen-Agenten auf einem neuen lokalen Linux-Host"^]
. Melden Sie sich mit den Administrator-Benutzerdaten, die Sie soeben erstellt haben, bei der NetApp Console an.




[[restore-the-netapp-backup-and-recovery-database]]
=== Wiederherstellen der NetApp Backup and Recovery -Datenbank

. Das MySQL-Backup wird vom Backup-Speicherort auf den neuen Console-Agent-Host kopiert. Im folgenden Beispiel wird der Dateiname  `CBS_DB_Backup_23_05_2023.sql` verwendet.
. Kopieren Sie die Sicherung mit einem der folgenden Befehle in den MySQL-Docker-Container, je nachdem, ob Sie einen Docker- oder Podman-Container verwenden:
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Rufen Sie die MySQL-Container-Shell mit einem der folgenden Befehle auf, je nachdem, ob Sie einen Docker- oder Podman-Container verwenden:
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. Stellen Sie in der Container-Shell die „Umgebung“ bereit.
. Sie benötigen das MySQL-DB-Passwort. Kopieren Sie daher den Wert des Schlüssels „MYSQL_ROOT_PASSWORD“.
. Stellen Sie die MySQL-Datenbank von NetApp Backup and Recovery mit dem folgenden Befehl wieder her:
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Überprüfen Sie mit den folgenden SQL-Befehlen, ob die MySQL-Datenbank von NetApp Backup and Recovery korrekt wiederhergestellt wurde:
+
[source, cli]
----
mysql -u root -p cloud_backup
----
. Geben Sie das Passwort ein.
+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
. Stellen Sie sicher, dass die angezeigten Volumina mit denen Ihrer ursprünglichen Umgebung übereinstimmen.




[[restore-the-indexed-catalog-files]]
=== Wiederherstellen der indizierten Katalogdateien

. Die ZIP-Datei des Indexed Catalog-Backups ist vom Sicherungsspeicherort in den  `/opt/application/netapp/cbs` Ordner auf dem neuen Console Agent-Host zu kopieren. Im folgenden Beispiel wird der Dateiname  `Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip` verwendet.
. Entpacken Sie die Datei „Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip“ mit dem folgenden Befehl:
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Führen Sie den Befehl *ls* aus, um sicherzustellen, dass der Ordner "catalogdb1" erstellt wurde und dass er die Unterordner  `files`, `versions` und  `snapshots` enthält.




[[discover-your-ontap-clusters-and-storagegrid-systems]]
=== Entdecken Sie Ihre ONTAP -Cluster und StorageGRID Systeme

. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Entdecken Sie alle On-Premise ONTAP Systeme"^]die in Ihrer vorherigen Umgebung verfügbar waren. Dazu gehört auch das ONTAP -System, das Sie als S3-Server verwendet haben.
. https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["Entdecken Sie Ihre StorageGRID -Systeme"^].




[[set-up-the-storagegrid-environment-details]]
=== Einrichten der StorageGRID -Umgebungsdetails

Fügen Sie die Details des StorageGRID Systems hinzu, das mit Ihren ONTAP Systemen verknüpft ist, wie sie in der ursprünglichen Console Agent Einrichtung konfiguriert wurden, indem Sie die  https://docs.netapp.com/us-en/console-automation/index.html["NetApp Console -APIs"^] verwenden.

Die folgenden Informationen gelten für Installationen im privaten Modus ab NetApp Console 3.9.xx.  Bei älteren Versionen gehen Sie wie folgt vor: https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite Cloud Backup: MySQL und indizierter Katalog sichern und wiederherstellen"^] .

Sie müssen diese Schritte für jedes System ausführen, das Daten auf StorageGRID sichert.

. Extrahieren Sie das Autorisierungstoken mithilfe der folgenden OAuth/Token-API.
+
[source, shell]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
Während IP-Adresse, Benutzername und Passwort frei wählbar sind, ist der Kontoname nicht frei wählbar. Der Kontoname ist immer `account-DARKSITE1`. Außerdem muss der Benutzername im E-Mail-Format angegeben werden.

+
Diese API gibt eine Antwort wie die folgende zurück. Das Autorisierungstoken kann wie unten gezeigt abgerufen werden.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Extrahieren Sie die System-ID und die X-Agent-ID mithilfe der Tenancy/External/Resource-API.
+
[source, shell]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Diese API gibt eine Antwort wie die folgende zurück. Der Wert unter `resourceIdentifier` bezeichnet die _WorkingEnvironment ID_, und der Wert unter `agentId` bezeichnet die _x-agent-id_.

+
[source, text]
----
[{"resourceIdentifier":"OnPremWorkingEnvironment-pMtZND0M","resourceType":"ON_PREM","agentId":"vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients","resourceClass":"ON_PREM","name":"CBSFAS8300-01-02","metadata":"{\"clusterUuid\": \"2cb6cb4b-dc07-11ec-9114-d039ea931e09\"}","workspaceIds":["workspace2wKYjTy9"],"agentIds":["vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients"]}]
----
. Die NetApp Backup and Recovery Datenbank wird mit den Details des StorageGRID Systems aktualisiert, das den Systemen zugeordnet ist. Es ist sicherzustellen, dass der vollqualifizierte Domainname von StorageGRID zusammen mit dem Zugriffsschlüssel und dem Speicherschlüssel wie unten gezeigt eingegeben wird:
+
[source, shell]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




[[verify-netapp-backup-and-recovery-settings]]
=== Überprüfen der NetApp Backup and Recovery -Einstellungen

. Jedes ONTAP-System auswählen und im rechten Bereich neben dem Backup and Recovery Service *Sicherungen anzeigen* auswählen.
+
Sie sollten alle für Ihre Volumes erstellten Backups sehen.

. Im Wiederherstellungs-Dashboard im Abschnitt „Suchen & Wiederherstellen“ die Option „Indexierungseinstellungen“ auswählen.
+
Stellen Sie sicher, dass die Systeme, bei denen die Indizierung zuvor aktiviert war, weiterhin aktiviert bleiben.

. Führen Sie auf der Seite „Suchen und Wiederherstellen“ einige Katalogsuchen durch, um zu bestätigen, dass die Wiederherstellung des indizierten Katalogs erfolgreich abgeschlossen wurde.

