---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Erstellen Sie ein Sicherheitszertifikat, um die Kommunikation zwischen NetApp Backup and Recovery und StorageGRID oder ONTAP zu ermöglichen. 
---
= CA-Zertifikate für NetApp Backup and Recovery einrichten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
CA-Zertifikate werden eingerichtet, damit NetApp Backup and Recovery sichere Verbindungen zu StorageGRID oder ONTAP validieren kann. Es sind die Schritte zu befolgen, die für Ihre Umgebung und die zu schützenden Systeme relevant sind.



[[create-a-ca-certificate-for-storagegrid]]
== Ein CA-Zertifikat für StorageGRID erstellen

Falls die Kommunikation zwischen den NetApp Backup and Recovery Containern und StorageGRID das StorageGRID-Zertifikat überprüfen soll, sind die folgenden Schritte erforderlich.

Das generierte Zertifikat sollte denselben allgemeinen Namen (CN) und denselben Subject Alternative Name verwenden, die Sie in NetApp Backup and Recovery bei der Aktivierung der Sicherung angegeben haben.

.Schritte
. Befolgen Sie die Schritte in der StorageGRID -Dokumentation, um das StorageGRID -Zertifikat zu erstellen.
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["StorageGRID Informationen zum Konfigurieren von Zertifikaten"]

. Aktualisieren Sie StorageGRID mit dem Zertifikat, falls Sie dies noch nicht getan haben.
. Melden Sie sich beim Console-Agenten als Root-Benutzer an. Führen Sie Folgendes aus:
+
[source, shell]
----
sudo su
----
. Das NetApp Backup and Recovery (Cloud Backup Service) Docker-Volume ermitteln. Folgendes ausführen:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Ausgabebeispiel:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: Der Volumename ist in den Bereitstellungsmodi „Standard“, „Privat“ und „Eingeschränkt“ unterschiedlich. In diesem Beispiel wird der Standardmodus verwendet. Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

. Suchen Sie den Einhängepunkt des NetApp Backup and Recovery -Volumes. Laufen:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ausgabebeispiel:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: Der Einhängepunkt ist in den Bereitstellungsmodi „Standard“, „Privat“ und „Eingeschränkt“ unterschiedlich. Dieses Beispiel zeigt eine Standard-Cloud-Bereitstellung. Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

. Wechseln Sie in das Mount-Verzeichnis. Führen Sie Folgendes aus:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Wenn das StorageGRID-Zertifikat von der Root-CA und einer Intermediate-CA signiert ist, beide  `pem` Dateien in einer Datei mit dem Namen  `sgws.crt` im aktuellen Verzeichnis zusammenfügen. Das Leaf-Zertifikat darf dieser Datei nicht hinzugefügt werden.




[[steps-for-the-cloudmanagercbs-container]]
=== Schritte für den cloudmanager_cbs Container

Die StorageGRID Serverzertifikatsprüfung in NetApp Backup and Recovery (Cloud Backup Service) kann aktiviert werden.

. Zu dem Docker-Volume wechseln, das in den vorherigen Schritten gefunden wurde.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. In das Konfigurationsverzeichnis wechseln.
+
[source, shell]
----
cd cbs_config
----
. Eine Konfigurationsdatei wie unten gezeigt mit einem der folgenden Namen entsprechend Ihrer Bereitstellungsumgebung erstellen und speichern:
+
** `production-customer.json` für Bereitstellungen im Standardmodus und im eingeschränkten Modus
** `darksite-customer.json` für Private Mode-Bereitstellungen
+
Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

+
*Konfigurationsdatei*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Verlassen Sie den Container. Laufen:
+
[source, shell]
----
exit
----
. Neustart `cloudmanager_cbs` . Laufen:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Schritte für den cloudmanager_cbs_catalog Container

Anschließend wird die StorageGRID Serverzertifikatsprüfung für den Katalogisierungsdienst aktiviert.

. Wechseln Sie zum Docker-Volume:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Konfigurieren Sie den Katalog. Laufen:
+
[source, shell]
----
cd cbs_catalog_config
----
. Eine Konfigurationsdatei wie unten gezeigt mit einem der folgenden Namen, abhängig von der jeweiligen Bereitstellungsumgebung, erstellen:
+
** `production-customer.json` für Bereitstellungen im Standardmodus und im eingeschränkten Modus
** `darksite-customer.json` für Private Mode-Bereitstellungen
+
Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

+
*Katalogkonfigurationsdatei*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Starten Sie den Katalog neu. Laufen:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[update-the-console-agent-certificate-with-the-storagegrid-certificate-based-on-the-agent-operating-system]]
=== Aktualisieren Sie das Konsolen-Agent-Zertifikat mit dem StorageGRID -Zertifikat basierend auf dem Agent-Betriebssystem



==== Ubuntu

. Kopieren Sie das SGWS-Zertifikat nach  `/usr/local/share/ca-certificates`. Hier ist ein Beispiel:
+
[source, shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
Wo `sgws.crt` ist das Stamm-CA-Zertifikat.

. Die Hostzertifikate werden mit dem StorageGRID Zertifikat aktualisiert. Dazu ist Folgendes auszuführen:
+
[source, shell]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Kopieren Sie das SGWS-Zertifikat nach `/etc/pki/ca-trust/source/anchors/` .
+
[source, shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
Wo `sgws.crt` ist das Stamm-CA-Zertifikat.

. Aktualisieren Sie die Hostzertifikate mit dem StorageGRID -Zertifikat.
+
[source, shell]
----
update-ca-trust extract
----
. Aktualisieren Sie die `ca-bundle.crt`
+
[source, shell]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Um zu überprüfen, ob die Zertifikate vorhanden sind, führen Sie den folgenden Befehl aus:
+
[source, shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




[[create-a-ca-certificate-for-ontap]]
== Ein CA-Zertifikat für ONTAP erstellen

Falls die Kommunikation zwischen den NetApp Backup and Recovery Containern und ONTAP das ONTAP-Zertifikat validieren soll, sind die folgenden Schritte erforderlich.

NetApp Backup and Recovery verwendet die Cluster-Management-IP-Adresse, um eine Verbindung zu ONTAP herzustellen. Die Cluster-IP-Adresse ist in die Felder für den Subject Alternative Name des Zertifikats einzutragen. Dieser Wert ist bei der Generierung der CSR im System Manager anzugeben.

Verwenden Sie die System Manager-Dokumentation, um ein neues CA-Zertifikat für ONTAP zu erstellen.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Zertifikate mit System Manager verwalten"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["So verwalten Sie ONTAP SSL-Zertifikate mit System Manager"]


.Schritte
. Melden Sie sich als Root beim Console-Agenten an. Führen Sie Folgendes aus:
+
[source, shell]
----
sudo su
----
. Das NetApp Backup and Recovery Docker-Volume ermitteln. Folgender Befehl wird ausgeführt:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Ausgabebeispiel:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: Der Volumename ist in den Bereitstellungsmodi „Standard“, „Privat“ und „Eingeschränkt“ unterschiedlich. Dieses Beispiel zeigt eine Standard-Cloud-Bereitstellung. Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

. Der Mountpunkt für das Volume kann ermittelt werden. Folgendes ist auszuführen:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Ausgabebeispiel:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: Der Einhängepunkt ist in den Bereitstellungsmodi „Standard“, „Privat“ und „Eingeschränkt“ unterschiedlich. Dieses Beispiel zeigt eine Standard-Cloud-Bereitstellung. Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

. Wechseln Sie in das Mount-Verzeichnis. Führen Sie Folgendes aus:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn das ONTAP -Zertifikat von der Stammzertifizierungsstelle und einer Zwischenzertifizierungsstelle signiert ist, fügen Sie die `pem` Dateien von beiden in eine Datei mit dem Namen `ontap.crt` am aktuellen Standort.
** Wenn das ONTAP -Zertifikat von einer einzigen Zertifizierungsstelle signiert ist, benennen Sie das `pem` Datei als `ontap.crt` und kopieren Sie es an den aktuellen Speicherort. Fügen Sie das Blattzertifikat nicht zu dieser Datei hinzu.






[[steps-for-the-cloudmanagercbs-container]]
=== Schritte für den cloudmanager_cbs Container

Anschließend wird die ONTAP Serverzertifikatsprüfung in NetApp Backup und Recovery (Cloud Backup Service) aktiviert.

. Zu dem Docker-Volume wechseln, das in den vorherigen Schritten gefunden wurde.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Wechseln Sie in das Konfigurationsverzeichnis. Laufen:
+
[source, shell]
----
cd cbs_config
----
. Eine Konfigurationsdatei wie unten gezeigt mit einem der folgenden Namen, abhängig von der jeweiligen Bereitstellungsumgebung, erstellen:
+
** `production-customer.json` für Bereitstellungen im Standardmodus und im eingeschränkten Modus
** `darksite-customer.json` für Private Mode-Bereitstellungen
+
Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

+
*Konfigurationsdatei*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Verlassen Sie den Container. Laufen:
+
[source, shell]
----
exit
----
. Starten Sie NetApp Backup and Recovery neu. Laufen:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Schritte für den cloudmanager_cbs_catalog Container

Die ONTAP Serverzertifikatsprüfung für den Katalogisierungsdienst aktivieren.

. Wechseln Sie zum Docker-Volume. Führen Sie Folgendes aus:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Laufen:
+
[source, shell]
----
cd cbs_catalog_config
----
. Eine Konfigurationsdatei wie unten gezeigt mit einem der folgenden Namen, abhängig von der jeweiligen Bereitstellungsumgebung, erstellen:
+
** `production-customer.json` für Bereitstellungen im Standardmodus und im eingeschränkten Modus
** `darksite-customer.json` für Private Mode-Bereitstellungen
+
Siehe https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"] .

+
*Konfigurationsdatei*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Starten Sie NetApp Backup and Recovery neu. Laufen:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[create-a-certificate-for-both-ontap-and-storagegrid]]
== Erstellen Sie ein Zertifikat für ONTAP und StorageGRID

Wenn Sie das Zertifikat sowohl für ONTAP als auch für StorageGRID aktivieren müssen, sieht die Konfigurationsdatei folgendermaßen aus:

*Konfigurationsdatei für ONTAP und StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----