= Hyper-V-Workload-Verbesserungen
:allow-uri-read: 




=== Hyper-V-Workload-Verbesserungen

In dieser Version werden fĂĽr Hyper-V-Workloads die folgenden Verbesserungen eingefĂĽhrt:

* *VMs auf SAN-Speicher schĂĽtzen*: Sie kĂ¶nnen jetzt VMs auf SAN-Objektspeicher schĂĽtzen.
* *Verbesserungen bei der Wiederherstellung an alternativen Speicherorten*: Sie kĂ¶nnen jetzt von primĂ¤ren und sekundĂ¤ren Speicherorten fĂĽr VMs auf SAN-Speicher an einem alternativen Speicherort wiederherstellen.
* *Dateien und Ordner in einer Gast-VM*: Sie kĂ¶nnen jetzt Dateien und Ordner aus einem Snapshot auf dem primĂ¤ren Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nur fĂĽr CIFS-VMs unterstĂĽtzt.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Ăśbersicht zum SchĂĽtzen von Hyper-V-Workloads"] .



=== Verbesserungen fĂĽr KVM-Workloads

In dieser Version wird fĂĽr KVM-Workloads die folgende Verbesserung eingefĂĽhrt:

*Wiederherstellung an alternativem Speicherort*: Sie kĂ¶nnen KVM-VMs jetzt an einem alternativen Zielort wiederherstellen (diese Funktion ist jetzt allgemein verfĂĽgbar).

Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Ăśbersicht ĂĽber den Schutz von KVM-Workloads"] .



=== Verbesserungen der Oracle Database Workloads

In dieser Version werden die folgenden Verbesserungen fĂĽr Oracle Database workloads eingefĂĽhrt:

* *UnterstĂĽtzung fĂĽr Oracle AI Database 26ai*: Backup und Recovery unterstĂĽtzen jetzt Oracle AI Database 26ai.
* *UnterstĂĽtzung fĂĽr die Backup-Verifizierung*: Sie kĂ¶nnen jetzt Backup-Richtlinien konfigurieren, um die IntegritĂ¤t Ihrer Oracle Datenbank-Backups automatisch zu ĂĽberprĂĽfen.


Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Ăśbersicht ĂĽber den Schutz von Oracle Database-Workloads"].



=== VMware-Workload-Verbesserungen

In dieser Version fĂĽhrt VMware workloads die folgenden Verbesserungen ein:

* *UnterstĂĽtzung fĂĽr datenspeicherĂĽbergreifende Schutzgruppen*: Sie kĂ¶nnen nun das Verhalten von Schutzgruppen beim Schutz virtueller Maschinen auswĂ¤hlen, deren virtuelle Festplatten sich ĂĽber mehrere Datenspeicher erstrecken.
* *KlonunterstĂĽtzung*: Sie kĂ¶nnen jetzt Klone von Snapshots virtueller Maschinen aus dem primĂ¤ren und sekundĂ¤ren Speicher erstellen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Ăśbersicht zum SchĂĽtzen von VMware-Workloads"] .
