= ONTAP Volumes Workloads-Verbesserung
:allow-uri-read: 




[[ontap-volumes-workloads-enhancement]]
=== ONTAP Volumes Workloads-Verbesserung

In dieser Version wird für ONTAP Volumes Workloads die folgende Vorschau-Verbesserung eingeführt:

*Verbesserte Unterstützung für Dark Sites*: NetApp Backup and Recovery for dark sites bietet jetzt dieselben ONTAP Volumes Datenschutzfunktionen wie NetApp Backup and Recovery. Diese Verbesserung umfasst aktualisierte Backup-, Wiederherstellungs- und Job-Management-Services sowie eine neue Metadaten-Datenbank. Während eines Upgrades bleiben vorhandene Datenbankdaten erhalten und werden automatisch migriert. Nach dem Upgrade ist eine Überprüfung der Audit-Protokolle erforderlich, um sicherzustellen, dass die Migration erfolgreich abgeschlossen wurde. NetApp Backup and Recovery for dark sites unterstützt nur ONTAP Volumes Workloads.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Informationen zum ONTAP Volumeschutz mit NetApp Backup und Recovery"].



[[kubernetes-workloads-enhancements]]
=== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.09*: Diese Version enthält Trident Protect 26.09.
* *Cluster- und Namespace-granulare rollenbasierte Zugriffskontrolle (RBAC)*: Bei der Kubernetes Cluster-Erkennung kann der Zugriff auf Ressourcen durch die Auswahl eines Projekts oder Ordners gesteuert werden, das bzw. der dem neuen Cluster zugeordnet wird. Außerdem können bestimmte Namespaces für die Zugriffskontrolle registriert werden. Dadurch wird eine granularere Zugriffskontrolle entweder auf Cluster- oder Namespace-Ebene ermöglicht.
* *Dateien und Ordner wiederherstellen*: Es ist jetzt möglich, bestimmte Dateien und Ordner aus Kubernetes VM-basierten Anwendungssicherungen wiederherzustellen oder herunterzuladen.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Informationen zum Schutz von Kubernetes Workloads mit NetApp Backup and Recovery"].
