= ONTAP Volumes Workloads-Verbesserungen
:allow-uri-read: 




=== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*NetApp MetroCluster Aktiv/Aktiv-Konfigurationen unterstützt*: NetApp Backup and Recovery for Volumes-Workloads unterstützt jetzt MetroCluster in der Aktiv/Aktiv-Konfiguration.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



=== Kubernetes-Workloads-Erweiterungen

In dieser Version führt Kubernetes-Workloads die folgenden Verbesserungen der Datensicherungsstrategie ein:

* *Bearbeitung der Schutzrichtlinien*: Sie können jetzt die Kubernetes-Workload-Schutzrichtlinien bearbeiten, falls Sie sie ändern müssen.
* *Disk-to-Disk-Unterstützung*: Sie können jetzt Kubernetes-Schutzrichtlinien mit einer Disk-to-Disk-Backup-Architektur konfigurieren.
* *Unterstützung für Google Cloud Platform storage bucket*: Sie können jetzt Kubernetes-Datensicherungsstrategien so konfigurieren, dass Backups in Google Cloud Platform storage buckets gespeichert werden.


Weitere Informationen zu den Datensicherungsstrategien finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Erstellen und Verwalten von Datensicherungsstrategien in NetApp Backup and Recovery"].

Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schützen von Kubernetes-Workloads"] .



=== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.
* *SAN-Unterstützung (Vorschau)*: Backup and Recovery unterstützt jetzt den Schutz von Hyper-V-VMs, die auf SAN-Speichern abgelegt sind.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schützen von Hyper-V-Workloads"] .



=== Verbesserungen für KVM-Workloads

In dieser Version werden für KVM-Workloads die folgenden Verbesserungen eingeführt:

* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.
* *Wiederherstellung an alternativem Speicherort (Vorschau)*: Sie können KVM-VMs jetzt an einem alternativen Ziel wiederherstellen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-restore.html["Wiederherstellen virtueller KVM-Maschinen mit NetApp Backup and Recovery"].


Weitere Informationen zum Schutz von KVM-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Übersicht über den Schutz von KVM-Workloads"] .



=== VMware-Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Tagbasierter Schutz*: Backup and Recovery für VMware-Workloads unterstützt jetzt tagbasierten Schutz für VMs, die auf NFS- und VMFS-Volumes gespeichert sind, sodass Sie Schutzgruppen aus vCenter-Tags anstatt aus einzelnen VMs oder Datenspeichern erstellen können. Wenn Sie VMs und Datenspeicher in vCenter taggen, erkennt Backup and Recovery diese automatisch und schließt sie in zukünftige Backups ein, ohne dass eine manuelle Gruppenverwaltung erforderlich ist. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Schutzgruppen erstellen und verwalten"].
* *Wiederherstellung auf alternativem Speichersystem*: Sie können virtuelle Maschinen jetzt auch dann auf einem alternativen Speichersystem wiederherstellen, wenn das ursprüngliche (primäre) Speichersystem vollständig ausgefallen ist. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore.html["Wiederherstellen von VMware-Workloads"].
* *Dateien auf Linux-VMs wiederherstellen*: Sie können jetzt VM-Dateien und -Ordner auf Linux-VMs wiederherstellen. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Unterstützung für Proxy-VMs beim Wiederherstellen von Dateien und Ordnern* – Sie können jetzt Dateien und Ordner von virtuellen Festplatten mithilfe einer Proxy-VM wiederherstellen, wenn Sie die virtuelle Festplatte nicht an die ursprüngliche VM anbinden möchten. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Rekursive Datei- und Ordnersuche* – Sie können jetzt eine gesamte virtuelle Festplatte nach einer bestimmten Datei oder einem bestimmten Ordner durchsuchen. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Dateien und Ordner wiederherstellen"].
* *Verbesserte Auftragsabwicklung*: Backup and Recovery verarbeitet jetzt mehrere gleichzeitig laufende Aufträge effizienter.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Übersicht zum Schützen von VMware-Workloads"] .
