= Datenübertragungs-Zeitüberschreitung-Anmerkung
:allow-uri-read: 




== Datenübertragungs-Zeitüberschreitung-Anmerkung

Verwenden Sie die Annotation `protect.trident.netapp.io/data-mover-timeout-sec`, um ein Timeout (in Sekunden) für den Datentransfer pro Vorgang während der Sicherung und Wiederherstellung festzulegen. Sie gibt an, wie lange ein Datentransfer auf den Fortschritt eines Vorgangs wartet, bevor eine Zeitüberschreitung eintritt. Dies ist nützlich, um blockierte Übertragungen zu erkennen und zu behandeln (zum Beispiel, wenn Netzwerkprobleme den Fortschritt der Wiederherstellung von Volumendaten verhindern).

Sie können diese Annotation in Ihrer YAML-Datei wie unten gezeigt verwenden:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
In diesem Beispiel schlägt die Annotation beim  `BackupRestore`-Vorgang fehl, wenn innerhalb von 2 Sekunden kein Fortschritt beim Wiederherstellungsvorgang erzielt wird.


NOTE: Ist der Wert der Annotation kleiner oder gleich 0, schlägt die Operation sofort fehl.
