= Namespace-Annotationen und -Labels während Wiederherstellungs- und Failover-Operationen
:allow-uri-read: 




== Namespace-Annotationen und -Labels während Wiederherstellungs- und Failover-Operationen

Bei Wiederherstellung und Failover werden die Namespace-Bezeichnungen und -Annotationen des Ziels aktualisiert, um mit denen der Quelle übereinzustimmen: Schlüssel aus der Quelle werden zu den Zielschlüsseln hinzugefügt oder überschrieben, während Schlüssel, die nur im Ziel existieren, unverändert bleiben.


NOTE: In Red Hat OpenShift sind Namespace-Annotationen wichtig, da sie sicherstellen, dass wiederhergestellte Pods die korrekten Sicherheitskontextbeschränkungen und Berechtigungen erhalten, sodass sie auf Volumes zugreifen und ohne Berechtigungsfehler ausgeführt werden können. Weitere Informationen finden Sie unter link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift security context constraints Dokumentation"^].

Setzen Sie die Kubernetes-Umgebungsvariable

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
Vor der Wiederherstellung oder dem Failover sollte verhindert werden, dass bestimmte Ziel-Namespace-Annotationen überschrieben werden. Zum Beispiel:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Während der Wiederherstellung oder des Failovers werden alle in `restoreSkipNamespaceAnnotations` und `restoreSkipNamespaceLabels` angegebenen Namespace-Annotationen und -Labels von der Wiederherstellungs- oder Failover-Operation ausgeschlossen. Stellen Sie sicher, dass diese Einstellungen während der initialen Helm-Installation konfiguriert sind. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Konfigurieren Sie zusätzliche Trident Protect Helm-Chart-Einstellungen"].

Wenn Sie Helm mit dem  `--create-namespace` Flag zur Installation der Quellanwendung verwendet haben, kopiert Trident Protect die Namensbezeichnung in den Ziel-Namespace. Stimmt der Wert der Bezeichnung mit dem Namen des Quell-Namespace überein, wird er durch den Namen des Ziel-Namespace ersetzt; andernfalls bleibt er unverändert.



=== Beispiel

Das folgende Beispiel zeigt Quell- und Ziel-Namensräume mit unterschiedlichen Bezeichnungen und Annotationen und zeigt den Ziel-Namensraum vor und nach der Operation, um zu veranschaulichen, wie Schlüssel hinzugefügt, zusammengeführt oder überschrieben werden.



==== Vor dem Wiederherstellungs- oder Failover-Vorgang

Die folgende Tabelle veranschaulicht den Zustand der Beispiel-Quell- und Ziel-Namespaces vor der Wiederherstellungs- oder Failover-Operation:

[cols="1,2a,2a"]
|===
| Namensraum | Anmerkungen | Etiketten 


| Namespace ns-1 (Quelle)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"

 a| 
* environment=production
* compliance=hipaa
* name=ns-1




| Namespace ns-2 (Ziel)  a| 
* annotation.one/key: "true"
* annotation.three/key: "false"

 a| 
* role=database


|===


==== Nach dem Wiederherstellungsvorgang

Die folgende Tabelle veranschaulicht den Zustand des Beispiel-Ziel-Namespace nach der Wiederherstellung oder dem Failover. Einige Schlüssel wurden hinzugefügt, einige wurden überschrieben, und das  `name` Label wurde aktualisiert, um dem Ziel-Namespace zu entsprechen:

[cols="1,2a,2a"]
|===
| Namensraum | Anmerkungen | Etiketten 


| Namespace ns-2 (Ziel)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"

 a| 
* name=ns-2
* compliance=hipaa
* environment=production
* role=database


|===